namespace Dominio.ObjetosDeValor.Embarcador.Enumeradores
{
    public enum TipoProcessoMovimento
    {       
        EmissaoCTENFSe = 1,
        CancelamentoCTENFSe = 2,
        AnulacaoCTENFSe = 3,
        ValePedagioCTENFSe = 4,
        CancelamentoValePedagioCTENFSe = 5,
        EmissaodeSubContratacao = 6,
        CancelamentodeSubContratacao = 7,
        PagamentoContratoSubContratacao = 8,
        AdiantamentoTerceiros = 9,
        CancelamentodaBaixadeAdiantamentoTerceiro = 10,
        Ocorrencias = 11,
        CancelamentodeOcorrencias = 12,
        Ocorrencias999 = 13,
        CancelamentoOcorrencias999 = 14,
        GeracaodeFatura = 15,
        CancelamentoFatura = 16,
        DescontosFatura = 17,
        CancelamentoDescontosFatura = 18,
        AcrescimosFatura = 19,
        CancelamentoAcrescimoFatura = 20,
        BaixadeTitulosaReceber = 21,
        DescontoBaixadeTitulusaReceber = 22,
        AcrescimoBaixadeTitulosaReceber = 23,
        CancelamentoBaixadeTitulosaReceber = 24,
        CancelamentoAcrescimoBaixadeTitulosaReceber = 25,
        CancelamentoDescontoBaixadeTitulusaReceber = 26,
        GeracaodeParcelasdeNegociacao = 27,
        ValePedagioRecebidodeClienteAcerto = 28,
        CancelamentoPedagioRecebidodeClienteAcerto = 29,
        AbastecimentoPagoMotoristaAcerto = 30,
        CancelamentoAbastecimentoPagoMotoristaAcerto = 31,
        PagamentoPedagiopeloMotoristaAcerto = 32,
        CancelamentoPagamentoPedagioPeloMotoristaAcerto = 33,
        OutrasDespesasAcerto = 34,
        CancelamentoOutrasDespesasAcerto = 35,
        DescontodoAcerto = 36,
        CancelaDescontodoAcerto = 37,
        BonificacaoMotoristaAcerto = 38,
        CancelamentodaBonificacaodoMotoristaAcerto = 39,
        ComissaoAcerto = 40,
        CancelaComissaoAcerto = 41,
        CancelamentoGeracaodeParcelasdeNegociacao = 42,
        EmissaoDocumentoEntrada = 43,
        ExtornoDocumentoEntrada = 44
    }
}
