//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Resources.Enumeradores {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormaEnvioDocumentacao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormaEnvioDocumentacao() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Resources.Enumeradores.FormaEnvioDocumentacao", typeof(FormaEnvioDocumentacao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF das notas apenas.
        /// </summary>
        public static string PDFDasNotasApenas {
            get {
                return ResourceManager.GetString("PDFDasNotasApenas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF do CTes + Notas.
        /// </summary>
        public static string PDFDoCTesNotas {
            get {
                return ResourceManager.GetString("PDFDoCTesNotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF do CTes + Notas e XML dos CTes + Notas.
        /// </summary>
        public static string PDFDoCTesNotasXMLDosCTesNotas {
            get {
                return ResourceManager.GetString("PDFDoCTesNotasXMLDosCTesNotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF dos CTes apenas.
        /// </summary>
        public static string PDFDosCTesApenas {
            get {
                return ResourceManager.GetString("PDFDosCTesApenas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente XML das notas.
        /// </summary>
        public static string SomenteXMLDasNotas {
            get {
                return ResourceManager.GetString("SomenteXMLDasNotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente XML dos CTes.
        /// </summary>
        public static string SomenteXMLDosCTes {
            get {
                return ResourceManager.GetString("SomenteXMLDosCTes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usar do Grupo de Pessoa.
        /// </summary>
        public static string UsarDoGrupoDePessoa {
            get {
                return ResourceManager.GetString("UsarDoGrupoDePessoa", resourceCulture);
            }
        }
    }
}
