//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Resources.Enumeradores {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndicadorIE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndicadorIE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Resources.Enumeradores.IndicadorIE", typeof(IndicadorIE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Contribuinte isento de Inscrição no cadastro de Contribuintes do ICMS..
        /// </summary>
        public static string DoisContribuinteIsentoDeInscricaoNoCadastroDeContribuintesDoICMS {
            get {
                return ResourceManager.GetString("DoisContribuinteIsentoDeInscricaoNoCadastroDeContribuintesDoICMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Informado.
        /// </summary>
        public static string NaoInformado {
            get {
                return ResourceManager.GetString("NaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9- Não Contribuinte, que pode ou não possuir Inscrição Estadual no Cadastro de Contribuintes do ICMS..
        /// </summary>
        public static string NoveNaoContribuinteQuePodeOuNaoPossuirInscricaoEstadualNoCadastroDeContribuintesDoICMS {
            get {
                return ResourceManager.GetString("NoveNaoContribuinteQuePodeOuNaoPossuirInscricaoEstadualNoCadastroDeContribuintesD" +
                        "oICMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Contribuinte ICMS (informar a IE do destinatário)..
        /// </summary>
        public static string UmContribuinteICMSInformarIEDoDestinatario {
            get {
                return ResourceManager.GetString("UmContribuinteICMSInformarIEDoDestinatario", resourceCulture);
            }
        }
    }
}
