//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Resources.Enumeradores {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StatusCTe {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatusCTe() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Resources.Enumeradores.StatusCTe", typeof(StatusCTe).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizado.
        /// </summary>
        public static string Autorizado {
            get {
                return ResourceManager.GetString("Autorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelado.
        /// </summary>
        public static string Cancelado {
            get {
                return ResourceManager.GetString("Cancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denegado.
        /// </summary>
        public static string Denegado {
            get {
                return ResourceManager.GetString("Denegado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Cancelamento.
        /// </summary>
        public static string EmCancelamento {
            get {
                return ResourceManager.GetString("EmCancelamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Digitação.
        /// </summary>
        public static string EmDigitacao {
            get {
                return ResourceManager.GetString("EmDigitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Inutilização.
        /// </summary>
        public static string EmInutilizacao {
            get {
                return ResourceManager.GetString("EmInutilizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviado.
        /// </summary>
        public static string Enviado {
            get {
                return ResourceManager.GetString("Enviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inutilizado.
        /// </summary>
        public static string Inutilizado {
            get {
                return ResourceManager.GetString("Inutilizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendente.
        /// </summary>
        public static string Pendente {
            get {
                return ResourceManager.GetString("Pendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejeitado.
        /// </summary>
        public static string Rejeitado {
            get {
                return ResourceManager.GetString("Rejeitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
    }
}
