//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Resources.Enumeradores {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TipoParentesco {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TipoParentesco() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Resources.Enumeradores.TipoParentesco", typeof(TipoParentesco).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avô(ó).
        /// </summary>
        public static string Avo {
            get {
                return ResourceManager.GetString("Avo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bisavô(ó).
        /// </summary>
        public static string Bisavo {
            get {
                return ResourceManager.GetString("Bisavo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bisneto(a).
        /// </summary>
        public static string Bisneto {
            get {
                return ResourceManager.GetString("Bisneto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esposo(a).
        /// </summary>
        public static string Esposo {
            get {
                return ResourceManager.GetString("Esposo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filho(a).
        /// </summary>
        public static string Filhos {
            get {
                return ResourceManager.GetString("Filhos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irmão(ã).
        /// </summary>
        public static string Irmao {
            get {
                return ResourceManager.GetString("Irmao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mãe.
        /// </summary>
        public static string Mae {
            get {
                return ResourceManager.GetString("Mae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum.
        /// </summary>
        public static string Nenhum {
            get {
                return ResourceManager.GetString("Nenhum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neto(a).
        /// </summary>
        public static string Neto {
            get {
                return ResourceManager.GetString("Neto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outro.
        /// </summary>
        public static string Outro {
            get {
                return ResourceManager.GetString("Outro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pai.
        /// </summary>
        public static string Pai {
            get {
                return ResourceManager.GetString("Pai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primo(a).
        /// </summary>
        public static string Primo {
            get {
                return ResourceManager.GetString("Primo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrinho(a).
        /// </summary>
        public static string Sobrinho {
            get {
                return ResourceManager.GetString("Sobrinho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrino-Neto.
        /// </summary>
        public static string SobrinhoNeto {
            get {
                return ResourceManager.GetString("SobrinhoNeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tio(a).
        /// </summary>
        public static string Tio {
            get {
                return ResourceManager.GetString("Tio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tio-avó.
        /// </summary>
        public static string TioAvo {
            get {
                return ResourceManager.GetString("TioAvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trineto(a).
        /// </summary>
        public static string Trineto {
            get {
                return ResourceManager.GetString("Trineto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trisavô(ó).
        /// </summary>
        public static string Trisavo {
            get {
                return ResourceManager.GetString("Trisavo", resourceCulture);
            }
        }
    }
}
