//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Resources.Enumeradores {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TipoParametroBaseTabelaFrete {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TipoParametroBaseTabelaFrete() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Resources.Enumeradores.TipoParametroBaseTabelaFrete", typeof(TipoParametroBaseTabelaFrete).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajudante.
        /// </summary>
        public static string Ajudante {
            get {
                return ResourceManager.GetString("Ajudante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componente Frete.
        /// </summary>
        public static string ComponenteFrete {
            get {
                return ResourceManager.GetString("ComponenteFrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distância.
        /// </summary>
        public static string Distancia {
            get {
                return ResourceManager.GetString("Distancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excedente entrega.
        /// </summary>
        public static string ExcedenteEntrega {
            get {
                return ResourceManager.GetString("ExcedenteEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        public static string Hora {
            get {
                return ResourceManager.GetString("Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelos de Reboque.
        /// </summary>
        public static string ModeloReboque {
            get {
                return ResourceManager.GetString("ModeloReboque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelos de Tração.
        /// </summary>
        public static string ModeloTracao {
            get {
                return ResourceManager.GetString("ModeloTracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum.
        /// </summary>
        public static string Nenhum {
            get {
                return ResourceManager.GetString("Nenhum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Entregas.
        /// </summary>
        public static string NumeroEntrega {
            get {
                return ResourceManager.GetString("NumeroEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacote.
        /// </summary>
        public static string Pacote {
            get {
                return ResourceManager.GetString("Pacote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallets.
        /// </summary>
        public static string Pallets {
            get {
                return ResourceManager.GetString("Pallets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetros da Ocorrência.
        /// </summary>
        public static string ParametrosOcorrencia {
            get {
                return ResourceManager.GetString("ParametrosOcorrencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso.
        /// </summary>
        public static string Peso {
            get {
                return ResourceManager.GetString("Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rota Embarcador.
        /// </summary>
        public static string Rota {
            get {
                return ResourceManager.GetString("Rota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo.
        /// </summary>
        public static string Tempo {
            get {
                return ResourceManager.GetString("Tempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Carga.
        /// </summary>
        public static string TipoCarga {
            get {
                return ResourceManager.GetString("TipoCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Embalagem.
        /// </summary>
        public static string TipoEmbalagem {
            get {
                return ResourceManager.GetString("TipoEmbalagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Base.
        /// </summary>
        public static string ValorBase {
            get {
                return ResourceManager.GetString("ValorBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Líquido do Frete.
        /// </summary>
        public static string ValorFreteLiquido {
            get {
                return ResourceManager.GetString("ValorFreteLiquido", resourceCulture);
            }
        }
    }
}
