//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Resources.Enumeradores {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TipoTabelaFrete {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TipoTabelaFrete() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Resources.Enumeradores.TipoTabelaFrete", typeof(TipoTabelaFrete).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frete Sem Tabela.
        /// </summary>
        public static string FreteSemTabela {
            get {
                return ResourceManager.GetString("FreteSemTabela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela por Cliente.
        /// </summary>
        public static string TabelaCliente {
            get {
                return ResourceManager.GetString("TabelaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela por Comissão de produto.
        /// </summary>
        public static string TabelaComissaoProduto {
            get {
                return ResourceManager.GetString("TabelaComissaoProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela por Rota.
        /// </summary>
        public static string TabelaRota {
            get {
                return ResourceManager.GetString("TabelaRota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela por Subcontratação.
        /// </summary>
        public static string TabelaSubContratacao {
            get {
                return ResourceManager.GetString("TabelaSubContratacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas.
        /// </summary>
        public static string Todas {
            get {
                return ResourceManager.GetString("Todas", resourceCulture);
            }
        }
    }
}
