//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Resources.Filiais {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Turno {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Turno() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Resources.Filiais.Turno", typeof(Turno).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string Adicionar {
            get {
                return ResourceManager.GetString("Adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Turno.
        /// </summary>
        public static string AdicionarTurno {
            get {
                return ResourceManager.GetString("AdicionarTurno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção.
        /// </summary>
        public static string Atencao {
            get {
                return ResourceManager.GetString("Atencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizado com sucesso..
        /// </summary>
        public static string AtualizadoSucesso {
            get {
                return ResourceManager.GetString("AtualizadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar.
        /// </summary>
        public static string Atualizar {
            get {
                return ResourceManager.GetString("Atualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        public static string Aviso {
            get {
                return ResourceManager.GetString("Aviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrado com sucesso..
        /// </summary>
        public static string CadastradoSucesso {
            get {
                return ResourceManager.GetString("CadastradoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação.
        /// </summary>
        public static string Confirmacao {
            get {
                return ResourceManager.GetString("Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Descricao {
            get {
                return ResourceManager.GetString("Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação não pode passar de 2000 caracteres..
        /// </summary>
        public static string DescricaoNaoPodePassarDoisMilCaracteres {
            get {
                return ResourceManager.GetString("DescricaoNaoPodePassarDoisMilCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição não pode passar de 200 caracteres..
        /// </summary>
        public static string DescricaoNaoPodePassarDuzentosCaracteres {
            get {
                return ResourceManager.GetString("DescricaoNaoPodePassarDuzentosCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição é obrigatória..
        /// </summary>
        public static string DescricaoObrigatoria {
            get {
                return ResourceManager.GetString("DescricaoObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turno.
        /// </summary>
        public static string DescricaoTurno {
            get {
                return ResourceManager.GetString("DescricaoTurno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dias da semana.
        /// </summary>
        public static string DiasSemana {
            get {
                return ResourceManager.GetString("DiasSemana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluído com sucesso..
        /// </summary>
        public static string ExcluidoSucesso {
            get {
                return ResourceManager.GetString("ExcluidoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string Excluir {
            get {
                return ResourceManager.GetString("Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha.
        /// </summary>
        public static string Falha {
            get {
                return ResourceManager.GetString("Falha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filiais.
        /// </summary>
        public static string Filiais {
            get {
                return ResourceManager.GetString("Filiais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros de Pesquisa.
        /// </summary>
        public static string FiltrosPesquisa {
            get {
                return ResourceManager.GetString("FiltrosPesquisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Final.
        /// </summary>
        public static string HoraFinal {
            get {
                return ResourceManager.GetString("HoraFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora Inicial.
        /// </summary>
        public static string HoraInicial {
            get {
                return ResourceManager.GetString("HoraInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O horário final deve ser maior que o horário inicial..
        /// </summary>
        public static string HorarioFinalDeveSerMaiorInicial {
            get {
                return ResourceManager.GetString("HorarioFinalDeveSerMaiorInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horários.
        /// </summary>
        public static string Horarios {
            get {
                return ResourceManager.GetString("Horarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horários de Acesso.
        /// </summary>
        public static string HorariosAcesso {
            get {
                return ResourceManager.GetString("HorariosAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar o registro..
        /// </summary>
        public static string NaoFoiPossivelEncontrarRegistro {
            get {
                return ResourceManager.GetString("NaoFoiPossivelEncontrarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação.
        /// </summary>
        public static string Observacao {
            get {
                return ResourceManager.GetString("Observacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao adicionar dados..
        /// </summary>
        public static string OcorreuFalhaAdicionar {
            get {
                return ResourceManager.GetString("OcorreuFalhaAdicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao atualizar dados..
        /// </summary>
        public static string OcorreuFalhaAtualizar {
            get {
                return ResourceManager.GetString("OcorreuFalhaAtualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao consultar..
        /// </summary>
        public static string OcorreuFalhaConsultar {
            get {
                return ResourceManager.GetString("OcorreuFalhaConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao exportar..
        /// </summary>
        public static string OcorreuFalhaExportar {
            get {
                return ResourceManager.GetString("OcorreuFalhaExportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao gerar arquivo..
        /// </summary>
        public static string OcorreuFalhaGerar {
            get {
                return ResourceManager.GetString("OcorreuFalhaGerar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao remover dados..
        /// </summary>
        public static string OcorreuFalhaRemover {
            get {
                return ResourceManager.GetString("OcorreuFalhaRemover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string Pesquisar {
            get {
                return ResourceManager.GetString("Pesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar Turnos.
        /// </summary>
        public static string PesquisarTurnos {
            get {
                return ResourceManager.GetString("PesquisarTurnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realmente deseja excluir esse cadastro?.
        /// </summary>
        public static string RealmenteDesejaExcluirCadastro {
            get {
                return ResourceManager.GetString("RealmenteDesejaExcluirCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso.
        /// </summary>
        public static string Sucesso {
            get {
                return ResourceManager.GetString("Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugestão.
        /// </summary>
        public static string Sugestao {
            get {
                return ResourceManager.GetString("Sugestao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Até {1}.
        /// </summary>
        public static string XAteX {
            get {
                return ResourceManager.GetString("XAteX", resourceCulture);
            }
        }
    }
}
