// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.alianca.intercab.emp.doc.booking
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific; using Newtonsoft.Json;
	
	public partial class GenericEvent : ISpecificRecord
	{
		[JsonIgnore] public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""GenericEvent"",""namespace"":""com.alianca.intercab.emp.doc.booking"",""fields"":[{""name"":""name"",""type"":[""string"",""null""]},{""name"":""alternateCodes"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""AlternateCodeEvent"",""namespace"":""com.alianca.intercab.emp.doc.booking"",""fields"":[{""name"":""codeType"",""type"":[""string"",""null""]},{""name"":""code"",""type"":[""string"",""null""]}]}}}]}");
		private string _name;
		private IList<com.alianca.intercab.emp.doc.booking.AlternateCodeEvent> _alternateCodes;
		[JsonIgnore] public virtual Schema Schema
		{
			get
			{
				return GenericEvent._SCHEMA;
			}
		}
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public IList<com.alianca.intercab.emp.doc.booking.AlternateCodeEvent> alternateCodes
		{
			get
			{
				return this._alternateCodes;
			}
			set
			{
				this._alternateCodes = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.name;
			case 1: return this.alternateCodes;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.name = (System.String)fieldValue; break;
			case 1: this.alternateCodes = (IList<com.alianca.intercab.emp.doc.booking.AlternateCodeEvent>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
