//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Resources.Relatorios.Frotas
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Motorista
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Motorista()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Resources.Relatorios.Frotas.Motorista", typeof(Motorista).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Agência.
        /// </summary>
        public static string Agencia
        {
            get
            {
                return ResourceManager.GetString("Agencia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aposentado.
        /// </summary>
        public static string Aposentado
        {
            get
            {
                return ResourceManager.GetString("Aposentado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aposentado.
        /// </summary>
        public static string CPF
        {
            get
            {
                return ResourceManager.GetString("CPF", resourceCulture);
            }
        }
        public static string RG
        {
            get
            {
                return ResourceManager.GetString("RG", resourceCulture);
            }
        }
        public static string CNH
        {
            get
            {
                return ResourceManager.GetString("CNH", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Banco.
        /// </summary>
        public static string Banco
        {
            get
            {
                return ResourceManager.GetString("Banco", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bloqueado.
        /// </summary>
        public static string Bloqueado
        {
            get
            {
                return ResourceManager.GetString("Bloqueado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string Cargo
        {
            get
            {
                return ResourceManager.GetString("Cargo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cargo Motorista.
        /// </summary>
        public static string CargoMotorista
        {
            get
            {
                return ResourceManager.GetString("CargoMotorista", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Cargo Motorista.
        /// </summary>
        public static string CNPJTransportador
        {
            get
            {
                return ResourceManager.GetString("CNPJTransportador", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Cargo Motorista.
        /// </summary>
        public static string NumeroRegistroCNH
        {
            get
            {
                return ResourceManager.GetString("NumeroRegistroCNH", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Cargo Motorista.
        /// </summary>
        public static string DataPrimeiraCNH
        {
            get
            {
                return ResourceManager.GetString("DataPrimeiraCNH", resourceCulture);
            }
        }
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        public static string Bairro
        {
            get
            {
                return ResourceManager.GetString("Bairro", resourceCulture);
            }
        }
        public static string Numero
        {
            get
            {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        public static string TipoLogradouro
        {
            get
            {
                return ResourceManager.GetString("TipoLogradouro", resourceCulture);
            }
        }
        public static string EstadoCivil
        {
            get
            {
                return ResourceManager.GetString("EstadoCivil", resourceCulture);
            }
        }
        public static string CorRaca
        {
            get
            {
                return ResourceManager.GetString("CorRaca", resourceCulture);
            }
        }
        public static string Escolaridade
        {
            get
            {
                return ResourceManager.GetString("Escolaridade", resourceCulture);
            }
        }
        public static string TituloEleitoral
        {
            get
            {
                return ResourceManager.GetString("TituloEleitoral", resourceCulture);
            }
        }
        public static string ZonaEleitoral
        {
            get
            {
                return ResourceManager.GetString("ZonaEleitoral", resourceCulture);
            }
        }
        public static string SecaoEleitoral
        {
            get
            {
                return ResourceManager.GetString("DataExpedicaoCTPS", resourceCulture);
            }
        }
        public static string DataExpedicaoCTPS
        {
            get
            {
                return ResourceManager.GetString("SecaoEleitoral", resourceCulture);
            }
        }
        public static string EstadoCTPS
        {
            get
            {
                return ResourceManager.GetString("EstadoCTPS", resourceCulture);
            }
        }
        public static string LocalidadeNascimento
        {
            get
            {
                return ResourceManager.GetString("LocalidadeNascimento", resourceCulture);
            }
        }
        public static string GrauParentesco
        {
            get
            {
                return ResourceManager.GetString("GrauParentesco", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Cargo Motorista.
        /// </summary>
        public static string EstadoRG
        {
            get
            {
                return ResourceManager.GetString("EstadoRG", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Categoria CNH.
        /// </summary>
        public static string CategoriaCNH
        {
            get
            {
                return ResourceManager.GetString("CategoriaCNH", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string Celular
        {
            get
            {
                return ResourceManager.GetString("Celular", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Centro Resultado.
        /// </summary>
        public static string CentroResultado
        {
            get
            {
                return ResourceManager.GetString("CentroResultado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        public static string CEP
        {
            get
            {
                return ResourceManager.GetString("CEP", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Código Integração.
        /// </summary>
        public static string CodigoIntegracao
        {
            get
            {
                return ResourceManager.GetString("CodigoIntegracao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data Admissão.
        /// </summary>
        public static string DataAdmissao
        {
            get
            {
                return ResourceManager.GetString("DataAdmissao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data Emissão CNH.
        /// </summary>
        public static string DataEmissaoCNH
        {
            get
            {
                return ResourceManager.GetString("DataEmissaoCNH", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data Emissão RG.
        /// </summary>
        public static string DataEmissaoRG
        {
            get
            {
                return ResourceManager.GetString("DataEmissaoRG", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento.
        /// </summary>
        public static string DataNascimento
        {
            get
            {
                return ResourceManager.GetString("DataNascimento", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dias de Folga Retirada.
        /// </summary>
        public static string DiasFolgaRetirada
        {
            get
            {
                return ResourceManager.GetString("DiasFolgaRetirada", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dias Trabalhado.
        /// </summary>
        public static string DiasTrabalhado
        {
            get
            {
                return ResourceManager.GetString("DiasTrabalhado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dígito.
        /// </summary>
        public static string Digito
        {
            get
            {
                return ResourceManager.GetString("Digito", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Emissor RG.
        /// </summary>
        public static string EmissorRG
        {
            get
            {
                return ResourceManager.GetString("EmissorRG", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string Endereco
        {
            get
            {
                return ResourceManager.GetString("Endereco", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ficha Ativa.
        /// </summary>
        public static string FichaAtiva
        {
            get
            {
                return ResourceManager.GetString("FichaAtiva", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filial.
        /// </summary>
        public static string Filial
        {
            get
            {
                return ResourceManager.GetString("Filial", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Frota.
        /// </summary>
        public static string Frota
        {
            get
            {
                return ResourceManager.GetString("Frota", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Frotas.
        /// </summary>
        public static string Frotas
        {
            get
            {
                return ResourceManager.GetString("Frotas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gerar Comis..
        /// </summary>
        public static string GerarComissao
        {
            get
            {
                return ResourceManager.GetString("GerarComissao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Licença.
        /// </summary>
        public static string Licenca
        {
            get
            {
                return ResourceManager.GetString("Licenca", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Motivo bloqueio.
        /// </summary>
        public static string MotivoBloqueio
        {
            get
            {
                return ResourceManager.GetString("MotivoBloqueio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mudar aparelho sem bloquear.
        /// </summary>
        public static string MudarAparelhoSemBloquear
        {
            get
            {
                return ResourceManager.GetString("MudarAparelhoSemBloquear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nº Cartão.
        /// </summary>
        public static string NumeroCartao
        {
            get
            {
                return ResourceManager.GetString("NumeroCartao", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nº Conta.
        /// </summary>
        public static string NumeroConta
        {
            get
            {
                return ResourceManager.GetString("NumeroConta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nº Prontuário.
        /// </summary>
        public static string NumeroProntuario
        {
            get
            {
                return ResourceManager.GetString("NumeroProntuario", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao buscar os dados do relatório..
        /// </summary>
        public static string OcorreuUmaFalhaAoBuscarDadosRelatorio
        {
            get
            {
                return ResourceManager.GetString("OcorreuUmaFalhaAoBuscarDadosRelatorio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao gerar o relatório..
        /// </summary>
        public static string OcorreuUmaFalhaAoGerarRelatorio
        {
            get
            {
                return ResourceManager.GetString("OcorreuUmaFalhaAoGerarRelatorio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Relatório de Motoristas.
        /// </summary>
        public static string RelatorioMotorista
        {
            get
            {
                return ResourceManager.GetString("RelatorioMotorista", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Relatório de Motoristas.
        /// </summary>
        public static string RelatorioMotoristas
        {
            get
            {
                return ResourceManager.GetString("RelatorioMotoristas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Relatórios.
        /// </summary>
        public static string Relatorios
        {
            get
            {
                return ResourceManager.GetString("Relatorios", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saldo Adiantamento.
        /// </summary>
        public static string SaldoAdiantamento
        {
            get
            {
                return ResourceManager.GetString("SaldoAdiantamento", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saldo Diária.
        /// </summary>
        public static string SaldoDiaria
        {
            get
            {
                return ResourceManager.GetString("SaldoDiaria", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Situação Colaborador.
        /// </summary>
        public static string SituacaoColaborador
        {
            get
            {
                return ResourceManager.GetString("SituacaoColaborador", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string Telefone
        {
            get
            {
                return ResourceManager.GetString("Telefone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tipo Conta.
        /// </summary>
        public static string TipoConta
        {
            get
            {
                return ResourceManager.GetString("TipoConta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tipo do Motorista.
        /// </summary>
        public static string TipoMotorista
        {
            get
            {
                return ResourceManager.GetString("TipoMotorista", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tipo do Relatório.
        /// </summary>
        public static string TipoRelatorio
        {
            get
            {
                return ResourceManager.GetString("TipoRelatorio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transportadora.
        /// </summary>
        public static string Transportadora
        {
            get
            {
                return ResourceManager.GetString("Transportadora", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Utiliza Aplicativo.
        /// </summary>
        public static string UtilizaAplicativo
        {
            get
            {
                return ResourceManager.GetString("UtilizaAplicativo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Validade CNH.
        /// </summary>
        public static string ValidadeCNH
        {
            get
            {
                return ResourceManager.GetString("ValidadeCNH", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Validade Seguradora..
        /// </summary>
        public static string ValidadeSeguradora
        {
            get
            {
                return ResourceManager.GetString("ValidadeSeguradora", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Veículo.
        /// </summary>
        public static string Veiculo
        {
            get
            {
                return ResourceManager.GetString("Veiculo", resourceCulture);
            }
        }
    }
}
