//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ServiceSoap")]
    public interface ServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastrarMotorista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarMotoristaResponse CadastrarMotorista(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarMotoristaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastrarMotorista", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarMotoristaResponse> CadastrarMotoristaAsync(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarMotoristaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastrarMotoristaV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarMotoristaV2Response CadastrarMotoristaV2(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarMotoristaV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastrarMotoristaV2", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarMotoristaV2Response> CadastrarMotoristaV2Async(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarMotoristaV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RenovarPesquisaMotorista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RenovarPesquisaMotoristaResponse RenovarPesquisaMotorista(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RenovarPesquisaMotoristaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RenovarPesquisaMotorista", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RenovarPesquisaMotoristaResponse> RenovarPesquisaMotoristaAsync(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RenovarPesquisaMotoristaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastrarVeiculo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarVeiculoResponse CadastrarVeiculo(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarVeiculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastrarVeiculo", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarVeiculoResponse> CadastrarVeiculoAsync(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarVeiculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastrarVeiculoV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarVeiculoV2Response CadastrarVeiculoV2(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarVeiculoV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastrarVeiculoV2", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarVeiculoV2Response> CadastrarVeiculoV2Async(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarVeiculoV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarVeiculo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculoResponse ConsultarVeiculo(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarVeiculo", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculoResponse> ConsultarVeiculoAsync(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarVeiculoV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculoV2Response ConsultarVeiculoV2(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculoV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarVeiculoV2", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculoV2Response> ConsultarVeiculoV2Async(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculoV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarVeiculov4", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculov4Response ConsultarVeiculov4(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculov4Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarVeiculov4", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculov4Response> ConsultarVeiculov4Async(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculov4Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarMotorista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaResponse ConsultarMotorista(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarMotorista", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaResponse> ConsultarMotoristaAsync(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarMotoristaV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV2Response ConsultarMotoristaV2(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarMotoristaV2", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV2Response> ConsultarMotoristaV2Async(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarMotoristaV3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV3Response ConsultarMotoristaV3(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarMotoristaV3", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV3Response> ConsultarMotoristaV3Async(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarMotoristaV4", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV4Response ConsultarMotoristaV4(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV4Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarMotoristaV4", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV4Response> ConsultarMotoristaV4Async(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV4Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Credenciais : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string usuarioField;
        
        private string senhaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Senha
        {
            get
            {
                return this.senhaField;
            }
            set
            {
                this.senhaField = value;
                this.RaisePropertyChanged("Senha");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RetornoConsulta : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool statusField;
        
        private string mensagemField;
        
        private System.Nullable<System.DateTime> dataPesquisaField;
        
        private System.Nullable<System.DateTime> dataValidadeField;
        
        private System.Nullable<int> codigoPesquisaField;
        
        private System.Nullable<int> codigoRetornoField;
        
        private string documentoPendentesField;
        
        private string pesquisaComplementarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem
        {
            get
            {
                return this.mensagemField;
            }
            set
            {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> DataPesquisa
        {
            get
            {
                return this.dataPesquisaField;
            }
            set
            {
                this.dataPesquisaField = value;
                this.RaisePropertyChanged("DataPesquisa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> DataValidade
        {
            get
            {
                return this.dataValidadeField;
            }
            set
            {
                this.dataValidadeField = value;
                this.RaisePropertyChanged("DataValidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> CodigoPesquisa
        {
            get
            {
                return this.codigoPesquisaField;
            }
            set
            {
                this.codigoPesquisaField = value;
                this.RaisePropertyChanged("CodigoPesquisa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> CodigoRetorno
        {
            get
            {
                return this.codigoRetornoField;
            }
            set
            {
                this.codigoRetornoField = value;
                this.RaisePropertyChanged("CodigoRetorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DocumentoPendentes
        {
            get
            {
                return this.documentoPendentesField;
            }
            set
            {
                this.documentoPendentesField = value;
                this.RaisePropertyChanged("DocumentoPendentes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PesquisaComplementar
        {
            get
            {
                return this.pesquisaComplementarField;
            }
            set
            {
                this.pesquisaComplementarField = value;
                this.RaisePropertyChanged("PesquisaComplementar");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Veiculo : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Nullable<System.DateTime> dataCriacaoField;
        
        private string placaField;
        
        private string renavamField;
        
        private string chassiField;
        
        private int anoFabricacaoField;
        
        private string marcaField;
        
        private string modeloField;
        
        private string corField;
        
        private string statusEquipamentoRastreamentoField;
        
        private string numeroTerminalField;
        
        private string placaCarretaField;
        
        private string renavamCarretaField;
        
        private TipoProprietario tipoProprietarioField;
        
        private string proprietarioNomeField;
        
        private System.Nullable<double> proprietarioCNPJ_CPFField;
        
        private string proprietarioIE_RGField;
        
        private string proprietarioRG_UFField;
        
        private System.Nullable<System.DateTime> proprietarioDataNascimentoField;
        
        private string proprietarioNomeMaeField;
        
        private string tecnologiaRastreamentoField;
        
        private string tipoVeiculoField;
        
        private string tipoCarretaField;
        
        private string cnpjEmpresaDeVinculoField;
        
        private string cidadeOrigemField;
        
        private string estadoOrigemField;
        
        private string cRLVImagem64Field;
        
        private string rNTRCField;
        
        private System.Nullable<System.DateTime> validade_RNTRCField;
        
        private System.Nullable<PerfilV> perfilVField;
        
        private string proprietarioCelularField;
        
        private string controleClienteField;
        
        private System.Nullable<RNTCTipo> rNTCTipoField;
        
        private string nrLiberacaoField;
        
        private string grField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> DataCriacao
        {
            get
            {
                return this.dataCriacaoField;
            }
            set
            {
                this.dataCriacaoField = value;
                this.RaisePropertyChanged("DataCriacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Placa
        {
            get
            {
                return this.placaField;
            }
            set
            {
                this.placaField = value;
                this.RaisePropertyChanged("Placa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Renavam
        {
            get
            {
                return this.renavamField;
            }
            set
            {
                this.renavamField = value;
                this.RaisePropertyChanged("Renavam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Chassi
        {
            get
            {
                return this.chassiField;
            }
            set
            {
                this.chassiField = value;
                this.RaisePropertyChanged("Chassi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int AnoFabricacao
        {
            get
            {
                return this.anoFabricacaoField;
            }
            set
            {
                this.anoFabricacaoField = value;
                this.RaisePropertyChanged("AnoFabricacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Marca
        {
            get
            {
                return this.marcaField;
            }
            set
            {
                this.marcaField = value;
                this.RaisePropertyChanged("Marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Modelo
        {
            get
            {
                return this.modeloField;
            }
            set
            {
                this.modeloField = value;
                this.RaisePropertyChanged("Modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Cor
        {
            get
            {
                return this.corField;
            }
            set
            {
                this.corField = value;
                this.RaisePropertyChanged("Cor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string StatusEquipamentoRastreamento
        {
            get
            {
                return this.statusEquipamentoRastreamentoField;
            }
            set
            {
                this.statusEquipamentoRastreamentoField = value;
                this.RaisePropertyChanged("StatusEquipamentoRastreamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string NumeroTerminal
        {
            get
            {
                return this.numeroTerminalField;
            }
            set
            {
                this.numeroTerminalField = value;
                this.RaisePropertyChanged("NumeroTerminal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PlacaCarreta
        {
            get
            {
                return this.placaCarretaField;
            }
            set
            {
                this.placaCarretaField = value;
                this.RaisePropertyChanged("PlacaCarreta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string RenavamCarreta
        {
            get
            {
                return this.renavamCarretaField;
            }
            set
            {
                this.renavamCarretaField = value;
                this.RaisePropertyChanged("RenavamCarreta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public TipoProprietario TipoProprietario
        {
            get
            {
                return this.tipoProprietarioField;
            }
            set
            {
                this.tipoProprietarioField = value;
                this.RaisePropertyChanged("TipoProprietario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ProprietarioNome
        {
            get
            {
                return this.proprietarioNomeField;
            }
            set
            {
                this.proprietarioNomeField = value;
                this.RaisePropertyChanged("ProprietarioNome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<double> ProprietarioCNPJ_CPF
        {
            get
            {
                return this.proprietarioCNPJ_CPFField;
            }
            set
            {
                this.proprietarioCNPJ_CPFField = value;
                this.RaisePropertyChanged("ProprietarioCNPJ_CPF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ProprietarioIE_RG
        {
            get
            {
                return this.proprietarioIE_RGField;
            }
            set
            {
                this.proprietarioIE_RGField = value;
                this.RaisePropertyChanged("ProprietarioIE_RG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ProprietarioRG_UF
        {
            get
            {
                return this.proprietarioRG_UFField;
            }
            set
            {
                this.proprietarioRG_UFField = value;
                this.RaisePropertyChanged("ProprietarioRG_UF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<System.DateTime> ProprietarioDataNascimento
        {
            get
            {
                return this.proprietarioDataNascimentoField;
            }
            set
            {
                this.proprietarioDataNascimentoField = value;
                this.RaisePropertyChanged("ProprietarioDataNascimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ProprietarioNomeMae
        {
            get
            {
                return this.proprietarioNomeMaeField;
            }
            set
            {
                this.proprietarioNomeMaeField = value;
                this.RaisePropertyChanged("ProprietarioNomeMae");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string TecnologiaRastreamento
        {
            get
            {
                return this.tecnologiaRastreamentoField;
            }
            set
            {
                this.tecnologiaRastreamentoField = value;
                this.RaisePropertyChanged("TecnologiaRastreamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string TipoVeiculo
        {
            get
            {
                return this.tipoVeiculoField;
            }
            set
            {
                this.tipoVeiculoField = value;
                this.RaisePropertyChanged("TipoVeiculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string TipoCarreta
        {
            get
            {
                return this.tipoCarretaField;
            }
            set
            {
                this.tipoCarretaField = value;
                this.RaisePropertyChanged("TipoCarreta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string CnpjEmpresaDeVinculo
        {
            get
            {
                return this.cnpjEmpresaDeVinculoField;
            }
            set
            {
                this.cnpjEmpresaDeVinculoField = value;
                this.RaisePropertyChanged("CnpjEmpresaDeVinculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string CidadeOrigem
        {
            get
            {
                return this.cidadeOrigemField;
            }
            set
            {
                this.cidadeOrigemField = value;
                this.RaisePropertyChanged("CidadeOrigem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string EstadoOrigem
        {
            get
            {
                return this.estadoOrigemField;
            }
            set
            {
                this.estadoOrigemField = value;
                this.RaisePropertyChanged("EstadoOrigem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string CRLVImagem64
        {
            get
            {
                return this.cRLVImagem64Field;
            }
            set
            {
                this.cRLVImagem64Field = value;
                this.RaisePropertyChanged("CRLVImagem64");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string RNTRC
        {
            get
            {
                return this.rNTRCField;
            }
            set
            {
                this.rNTRCField = value;
                this.RaisePropertyChanged("RNTRC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<System.DateTime> Validade_RNTRC
        {
            get
            {
                return this.validade_RNTRCField;
            }
            set
            {
                this.validade_RNTRCField = value;
                this.RaisePropertyChanged("Validade_RNTRC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<PerfilV> PerfilV
        {
            get
            {
                return this.perfilVField;
            }
            set
            {
                this.perfilVField = value;
                this.RaisePropertyChanged("PerfilV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string ProprietarioCelular
        {
            get
            {
                return this.proprietarioCelularField;
            }
            set
            {
                this.proprietarioCelularField = value;
                this.RaisePropertyChanged("ProprietarioCelular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string ControleCliente
        {
            get
            {
                return this.controleClienteField;
            }
            set
            {
                this.controleClienteField = value;
                this.RaisePropertyChanged("ControleCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<RNTCTipo> RNTCTipo
        {
            get
            {
                return this.rNTCTipoField;
            }
            set
            {
                this.rNTCTipoField = value;
                this.RaisePropertyChanged("RNTCTipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string NrLiberacao
        {
            get
            {
                return this.nrLiberacaoField;
            }
            set
            {
                this.nrLiberacaoField = value;
                this.RaisePropertyChanged("NrLiberacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string GR
        {
            get
            {
                return this.grField;
            }
            set
            {
                this.grField = value;
                this.RaisePropertyChanged("GR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TipoProprietario
    {
        
        /// <remarks/>
        Juridica,
        
        /// <remarks/>
        Fisica,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum PerfilV
    {
        
        /// <remarks/>
        AG,
        
        /// <remarks/>
        AU,
        
        /// <remarks/>
        FR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum RNTCTipo
    {
        
        /// <remarks/>
        Aluguel,
        
        /// <remarks/>
        Particular,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RetornoCadastro : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private StatusPesquisa statusField;
        
        private System.Nullable<System.DateTime> dataPesquisaField;
        
        private System.Nullable<System.DateTime> dataValidadeField;
        
        private System.Nullable<int> codigoPesquisaField;
        
        private System.Nullable<int> codigoRetornoField;
        
        private string mensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatusPesquisa Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> DataPesquisa
        {
            get
            {
                return this.dataPesquisaField;
            }
            set
            {
                this.dataPesquisaField = value;
                this.RaisePropertyChanged("DataPesquisa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> DataValidade
        {
            get
            {
                return this.dataValidadeField;
            }
            set
            {
                this.dataValidadeField = value;
                this.RaisePropertyChanged("DataValidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> CodigoPesquisa
        {
            get
            {
                return this.codigoPesquisaField;
            }
            set
            {
                this.codigoPesquisaField = value;
                this.RaisePropertyChanged("CodigoPesquisa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> CodigoRetorno
        {
            get
            {
                return this.codigoRetornoField;
            }
            set
            {
                this.codigoRetornoField = value;
                this.RaisePropertyChanged("CodigoRetorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Mensagem
        {
            get
            {
                return this.mensagemField;
            }
            set
            {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum StatusPesquisa
    {
        
        /// <remarks/>
        EnviadoParaPesquisa,
        
        /// <remarks/>
        ErroValidacao,
        
        /// <remarks/>
        Inapto,
        
        /// <remarks/>
        Apto,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Motorista : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string funcaoField;
        
        private string perfilField;
        
        private string fotoField;
        
        private System.Nullable<System.DateTime> dataCriacaoField;
        
        private string nomeField;
        
        private double cPFField;
        
        private string rgField;
        
        private string orgaoExpField;
        
        private System.Nullable<System.DateTime> dataEmissaoField;
        
        private System.Nullable<System.DateTime> dataNascimentoField;
        
        private string nomePaiField;
        
        private string nomeMaeField;
        
        private string generoField;
        
        private string enderecoField;
        
        private System.Nullable<int> numeroField;
        
        private string complementoField;
        
        private string bairroField;
        
        private string cEPField;
        
        private string telefoneField;
        
        private string celularField;
        
        private string nextelField;
        
        private string cNHRegistroField;
        
        private string cNHEmissaoField;
        
        private string cNHCategoriaField;
        
        private System.Nullable<System.DateTime> cNHValidadeField;
        
        private string cNHUfField;
        
        private string cnpjEmpresaDeVinculoField;
        
        private string cidadeOrigemField;
        
        private string estadoOrigemField;
        
        private System.Nullable<System.DateTime> vencimentoField;
        
        private string imagemCNH64Field;
        
        private System.Nullable<System.DateTime> dataValidadeField;
        
        private string nrLiberacaoField;
        
        private string grField;
        
        private bool pesquisaComplementarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Funcao
        {
            get
            {
                return this.funcaoField;
            }
            set
            {
                this.funcaoField = value;
                this.RaisePropertyChanged("Funcao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Perfil
        {
            get
            {
                return this.perfilField;
            }
            set
            {
                this.perfilField = value;
                this.RaisePropertyChanged("Perfil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Foto
        {
            get
            {
                return this.fotoField;
            }
            set
            {
                this.fotoField = value;
                this.RaisePropertyChanged("Foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> DataCriacao
        {
            get
            {
                return this.dataCriacaoField;
            }
            set
            {
                this.dataCriacaoField = value;
                this.RaisePropertyChanged("DataCriacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double CPF
        {
            get
            {
                return this.cPFField;
            }
            set
            {
                this.cPFField = value;
                this.RaisePropertyChanged("CPF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string RG
        {
            get
            {
                return this.rgField;
            }
            set
            {
                this.rgField = value;
                this.RaisePropertyChanged("RG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string OrgaoExp
        {
            get
            {
                return this.orgaoExpField;
            }
            set
            {
                this.orgaoExpField = value;
                this.RaisePropertyChanged("OrgaoExp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> DataEmissao
        {
            get
            {
                return this.dataEmissaoField;
            }
            set
            {
                this.dataEmissaoField = value;
                this.RaisePropertyChanged("DataEmissao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> DataNascimento
        {
            get
            {
                return this.dataNascimentoField;
            }
            set
            {
                this.dataNascimentoField = value;
                this.RaisePropertyChanged("DataNascimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string NomePai
        {
            get
            {
                return this.nomePaiField;
            }
            set
            {
                this.nomePaiField = value;
                this.RaisePropertyChanged("NomePai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string NomeMae
        {
            get
            {
                return this.nomeMaeField;
            }
            set
            {
                this.nomeMaeField = value;
                this.RaisePropertyChanged("NomeMae");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Genero
        {
            get
            {
                return this.generoField;
            }
            set
            {
                this.generoField = value;
                this.RaisePropertyChanged("Genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Endereco
        {
            get
            {
                return this.enderecoField;
            }
            set
            {
                this.enderecoField = value;
                this.RaisePropertyChanged("Endereco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> Numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
                this.RaisePropertyChanged("Numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Complemento
        {
            get
            {
                return this.complementoField;
            }
            set
            {
                this.complementoField = value;
                this.RaisePropertyChanged("Complemento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Bairro
        {
            get
            {
                return this.bairroField;
            }
            set
            {
                this.bairroField = value;
                this.RaisePropertyChanged("Bairro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string CEP
        {
            get
            {
                return this.cEPField;
            }
            set
            {
                this.cEPField = value;
                this.RaisePropertyChanged("CEP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Telefone
        {
            get
            {
                return this.telefoneField;
            }
            set
            {
                this.telefoneField = value;
                this.RaisePropertyChanged("Telefone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Celular
        {
            get
            {
                return this.celularField;
            }
            set
            {
                this.celularField = value;
                this.RaisePropertyChanged("Celular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Nextel
        {
            get
            {
                return this.nextelField;
            }
            set
            {
                this.nextelField = value;
                this.RaisePropertyChanged("Nextel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string CNHRegistro
        {
            get
            {
                return this.cNHRegistroField;
            }
            set
            {
                this.cNHRegistroField = value;
                this.RaisePropertyChanged("CNHRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string CNHEmissao
        {
            get
            {
                return this.cNHEmissaoField;
            }
            set
            {
                this.cNHEmissaoField = value;
                this.RaisePropertyChanged("CNHEmissao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string CNHCategoria
        {
            get
            {
                return this.cNHCategoriaField;
            }
            set
            {
                this.cNHCategoriaField = value;
                this.RaisePropertyChanged("CNHCategoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<System.DateTime> CNHValidade
        {
            get
            {
                return this.cNHValidadeField;
            }
            set
            {
                this.cNHValidadeField = value;
                this.RaisePropertyChanged("CNHValidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string CNHUf
        {
            get
            {
                return this.cNHUfField;
            }
            set
            {
                this.cNHUfField = value;
                this.RaisePropertyChanged("CNHUf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string CnpjEmpresaDeVinculo
        {
            get
            {
                return this.cnpjEmpresaDeVinculoField;
            }
            set
            {
                this.cnpjEmpresaDeVinculoField = value;
                this.RaisePropertyChanged("CnpjEmpresaDeVinculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string CidadeOrigem
        {
            get
            {
                return this.cidadeOrigemField;
            }
            set
            {
                this.cidadeOrigemField = value;
                this.RaisePropertyChanged("CidadeOrigem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string EstadoOrigem
        {
            get
            {
                return this.estadoOrigemField;
            }
            set
            {
                this.estadoOrigemField = value;
                this.RaisePropertyChanged("EstadoOrigem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<System.DateTime> Vencimento
        {
            get
            {
                return this.vencimentoField;
            }
            set
            {
                this.vencimentoField = value;
                this.RaisePropertyChanged("Vencimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string ImagemCNH64
        {
            get
            {
                return this.imagemCNH64Field;
            }
            set
            {
                this.imagemCNH64Field = value;
                this.RaisePropertyChanged("ImagemCNH64");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<System.DateTime> DataValidade
        {
            get
            {
                return this.dataValidadeField;
            }
            set
            {
                this.dataValidadeField = value;
                this.RaisePropertyChanged("DataValidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string NrLiberacao
        {
            get
            {
                return this.nrLiberacaoField;
            }
            set
            {
                this.nrLiberacaoField = value;
                this.RaisePropertyChanged("NrLiberacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string GR
        {
            get
            {
                return this.grField;
            }
            set
            {
                this.grField = value;
                this.RaisePropertyChanged("GR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public bool PesquisaComplementar
        {
            get
            {
                return this.pesquisaComplementarField;
            }
            set
            {
                this.pesquisaComplementarField = value;
                this.RaisePropertyChanged("PesquisaComplementar");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CadastrarMotorista", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CadastrarMotoristaRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Motorista motorista;
        
        public CadastrarMotoristaRequest()
        {
        }
        
        public CadastrarMotoristaRequest(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais, Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Motorista motorista)
        {
            this.Credenciais = Credenciais;
            this.motorista = motorista;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CadastrarMotoristaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CadastrarMotoristaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoCadastro CadastrarMotoristaResult;
        
        public CadastrarMotoristaResponse()
        {
        }
        
        public CadastrarMotoristaResponse(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoCadastro CadastrarMotoristaResult)
        {
            this.CadastrarMotoristaResult = CadastrarMotoristaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CadastrarMotoristaV2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CadastrarMotoristaV2Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Motorista motorista;
        
        public CadastrarMotoristaV2Request()
        {
        }
        
        public CadastrarMotoristaV2Request(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais, Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Motorista motorista)
        {
            this.Credenciais = Credenciais;
            this.motorista = motorista;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CadastrarMotoristaV2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CadastrarMotoristaV2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoCadastro CadastrarMotoristaV2Result;
        
        public CadastrarMotoristaV2Response()
        {
        }
        
        public CadastrarMotoristaV2Response(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoCadastro CadastrarMotoristaV2Result)
        {
            this.CadastrarMotoristaV2Result = CadastrarMotoristaV2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RenovarPesquisaMotorista", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RenovarPesquisaMotoristaRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Motorista motorista;
        
        public RenovarPesquisaMotoristaRequest()
        {
        }
        
        public RenovarPesquisaMotoristaRequest(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais, Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Motorista motorista)
        {
            this.Credenciais = Credenciais;
            this.motorista = motorista;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RenovarPesquisaMotoristaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RenovarPesquisaMotoristaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoCadastro RenovarPesquisaMotoristaResult;
        
        public RenovarPesquisaMotoristaResponse()
        {
        }
        
        public RenovarPesquisaMotoristaResponse(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoCadastro RenovarPesquisaMotoristaResult)
        {
            this.RenovarPesquisaMotoristaResult = RenovarPesquisaMotoristaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CadastrarVeiculo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CadastrarVeiculoRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Veiculo veiculo;
        
        public CadastrarVeiculoRequest()
        {
        }
        
        public CadastrarVeiculoRequest(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais, Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Veiculo veiculo)
        {
            this.Credenciais = Credenciais;
            this.veiculo = veiculo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CadastrarVeiculoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CadastrarVeiculoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoCadastro CadastrarVeiculoResult;
        
        public CadastrarVeiculoResponse()
        {
        }
        
        public CadastrarVeiculoResponse(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoCadastro CadastrarVeiculoResult)
        {
            this.CadastrarVeiculoResult = CadastrarVeiculoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CadastrarVeiculoV2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CadastrarVeiculoV2Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Veiculo veiculo;
        
        public CadastrarVeiculoV2Request()
        {
        }
        
        public CadastrarVeiculoV2Request(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais, Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Veiculo veiculo)
        {
            this.Credenciais = Credenciais;
            this.veiculo = veiculo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CadastrarVeiculoV2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CadastrarVeiculoV2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoCadastro CadastrarVeiculoV2Result;
        
        public CadastrarVeiculoV2Response()
        {
        }
        
        public CadastrarVeiculoV2Response(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoCadastro CadastrarVeiculoV2Result)
        {
            this.CadastrarVeiculoV2Result = CadastrarVeiculoV2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarVeiculo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarVeiculoRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string placa;
        
        public ConsultarVeiculoRequest()
        {
        }
        
        public ConsultarVeiculoRequest(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais, string placa)
        {
            this.Credenciais = Credenciais;
            this.placa = placa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarVeiculoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarVeiculoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoConsulta ConsultarVeiculoResult;
        
        public ConsultarVeiculoResponse()
        {
        }
        
        public ConsultarVeiculoResponse(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoConsulta ConsultarVeiculoResult)
        {
            this.ConsultarVeiculoResult = ConsultarVeiculoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarVeiculoV2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarVeiculoV2Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string placa;
        
        public ConsultarVeiculoV2Request()
        {
        }
        
        public ConsultarVeiculoV2Request(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais, string placa)
        {
            this.Credenciais = Credenciais;
            this.placa = placa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarVeiculoV2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarVeiculoV2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoConsulta ConsultarVeiculoV2Result;
        
        public ConsultarVeiculoV2Response()
        {
        }
        
        public ConsultarVeiculoV2Response(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoConsulta ConsultarVeiculoV2Result)
        {
            this.ConsultarVeiculoV2Result = ConsultarVeiculoV2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarVeiculov4", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarVeiculov4Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string placa;
        
        public ConsultarVeiculov4Request()
        {
        }
        
        public ConsultarVeiculov4Request(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais, string placa)
        {
            this.Credenciais = Credenciais;
            this.placa = placa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarVeiculov4Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarVeiculov4Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoConsulta ConsultarVeiculov4Result;
        
        public ConsultarVeiculov4Response()
        {
        }
        
        public ConsultarVeiculov4Response(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoConsulta ConsultarVeiculov4Result)
        {
            this.ConsultarVeiculov4Result = ConsultarVeiculov4Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarMotorista", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarMotoristaRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string cpf;
        
        public ConsultarMotoristaRequest()
        {
        }
        
        public ConsultarMotoristaRequest(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais, string cpf)
        {
            this.Credenciais = Credenciais;
            this.cpf = cpf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarMotoristaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarMotoristaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoConsulta ConsultarMotoristaResult;
        
        public ConsultarMotoristaResponse()
        {
        }
        
        public ConsultarMotoristaResponse(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoConsulta ConsultarMotoristaResult)
        {
            this.ConsultarMotoristaResult = ConsultarMotoristaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarMotoristaV2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarMotoristaV2Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string cpf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string centroCusto;
        
        public ConsultarMotoristaV2Request()
        {
        }
        
        public ConsultarMotoristaV2Request(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais, string cpf, string centroCusto)
        {
            this.Credenciais = Credenciais;
            this.cpf = cpf;
            this.centroCusto = centroCusto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarMotoristaV2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarMotoristaV2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoConsulta ConsultarMotoristaV2Result;
        
        public ConsultarMotoristaV2Response()
        {
        }
        
        public ConsultarMotoristaV2Response(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoConsulta ConsultarMotoristaV2Result)
        {
            this.ConsultarMotoristaV2Result = ConsultarMotoristaV2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarMotoristaV3", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarMotoristaV3Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string cpf;
        
        public ConsultarMotoristaV3Request()
        {
        }
        
        public ConsultarMotoristaV3Request(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais, string cpf)
        {
            this.Credenciais = Credenciais;
            this.cpf = cpf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarMotoristaV3Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarMotoristaV3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoConsulta ConsultarMotoristaV3Result;
        
        public ConsultarMotoristaV3Response()
        {
        }
        
        public ConsultarMotoristaV3Response(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoConsulta ConsultarMotoristaV3Result)
        {
            this.ConsultarMotoristaV3Result = ConsultarMotoristaV3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarMotoristaV4", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarMotoristaV4Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string cpf;
        
        public ConsultarMotoristaV4Request()
        {
        }
        
        public ConsultarMotoristaV4Request(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.Credenciais Credenciais, string cpf)
        {
            this.Credenciais = Credenciais;
            this.cpf = cpf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarMotoristaV4Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarMotoristaV4Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoConsulta ConsultarMotoristaV4Result;
        
        public ConsultarMotoristaV4Response()
        {
        }
        
        public ConsultarMotoristaV4Response(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RetornoConsulta ConsultarMotoristaV4Result)
        {
            this.ConsultarMotoristaV4Result = ConsultarMotoristaV4Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ServiceSoapChannel : Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ServiceSoap>, Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public ServiceSoapClient()
        {

        }

        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarMotoristaResponse CadastrarMotorista(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarMotoristaRequest request)
        {
            return base.Channel.CadastrarMotorista(request);
        }
        
        public System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarMotoristaResponse> CadastrarMotoristaAsync(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarMotoristaRequest request)
        {
            return base.Channel.CadastrarMotoristaAsync(request);
        }
        
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarMotoristaV2Response CadastrarMotoristaV2(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarMotoristaV2Request request)
        {
            return base.Channel.CadastrarMotoristaV2(request);
        }
        
        public System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarMotoristaV2Response> CadastrarMotoristaV2Async(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarMotoristaV2Request request)
        {
            return base.Channel.CadastrarMotoristaV2Async(request);
        }
        
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RenovarPesquisaMotoristaResponse RenovarPesquisaMotorista(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RenovarPesquisaMotoristaRequest request)
        {
            return base.Channel.RenovarPesquisaMotorista(request);
        }
        
        public System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RenovarPesquisaMotoristaResponse> RenovarPesquisaMotoristaAsync(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.RenovarPesquisaMotoristaRequest request)
        {
            return base.Channel.RenovarPesquisaMotoristaAsync(request);
        }
        
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarVeiculoResponse CadastrarVeiculo(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarVeiculoRequest request)
        {
            return base.Channel.CadastrarVeiculo(request);
        }
        
        public System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarVeiculoResponse> CadastrarVeiculoAsync(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarVeiculoRequest request)
        {
            return base.Channel.CadastrarVeiculoAsync(request);
        }
        
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarVeiculoV2Response CadastrarVeiculoV2(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarVeiculoV2Request request)
        {
            return base.Channel.CadastrarVeiculoV2(request);
        }
        
        public System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarVeiculoV2Response> CadastrarVeiculoV2Async(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.CadastrarVeiculoV2Request request)
        {
            return base.Channel.CadastrarVeiculoV2Async(request);
        }
        
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculoResponse ConsultarVeiculo(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculoRequest request)
        {
            return base.Channel.ConsultarVeiculo(request);
        }
        
        public System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculoResponse> ConsultarVeiculoAsync(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculoRequest request)
        {
            return base.Channel.ConsultarVeiculoAsync(request);
        }
        
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculoV2Response ConsultarVeiculoV2(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculoV2Request request)
        {
            return base.Channel.ConsultarVeiculoV2(request);
        }
        
        public System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculoV2Response> ConsultarVeiculoV2Async(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculoV2Request request)
        {
            return base.Channel.ConsultarVeiculoV2Async(request);
        }
        
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculov4Response ConsultarVeiculov4(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculov4Request request)
        {
            return base.Channel.ConsultarVeiculov4(request);
        }
        
        public System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculov4Response> ConsultarVeiculov4Async(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarVeiculov4Request request)
        {
            return base.Channel.ConsultarVeiculov4Async(request);
        }
        
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaResponse ConsultarMotorista(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaRequest request)
        {
            return base.Channel.ConsultarMotorista(request);
        }
        
        public System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaResponse> ConsultarMotoristaAsync(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaRequest request)
        {
            return base.Channel.ConsultarMotoristaAsync(request);
        }
        
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV2Response ConsultarMotoristaV2(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV2Request request)
        {
            return base.Channel.ConsultarMotoristaV2(request);
        }
        
        public System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV2Response> ConsultarMotoristaV2Async(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV2Request request)
        {
            return base.Channel.ConsultarMotoristaV2Async(request);
        }
        
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV3Response ConsultarMotoristaV3(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV3Request request)
        {
            return base.Channel.ConsultarMotoristaV3(request);
        }
        
        public System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV3Response> ConsultarMotoristaV3Async(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV3Request request)
        {
            return base.Channel.ConsultarMotoristaV3Async(request);
        }
        
        public Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV4Response ConsultarMotoristaV4(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV4Request request)
        {
            return base.Channel.ConsultarMotoristaV4(request);
        }
        
        public System.Threading.Tasks.Task<Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV4Response> ConsultarMotoristaV4Async(Servicos.ServicoBrasilRisk.GestaoAnaliseDePerfil.ConsultarMotoristaV4Request request)
        {
            return base.Channel.ConsultarMotoristaV4Async(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://homologacao.brasilrisk.com.br/gestaoanalisedeperfil/service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://homologacao.brasilrisk.com.br/gestaoanalisedeperfil/service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
}
