namespace Dominio.Entidades.Embarcador.Documentos
{
    [NHibernate.Mapping.Attributes.Class(0, Table = "T_ARQUIVO_MERCANTE_ERRO", EntityName = "ArquivoMercanteErro", Name = "Dominio.Entidades.Embarcador.Documentos.ArquivoMercanteErro", NameType = typeof(ArquivoMercanteErro))]

    public class ArquivoMercanteErro : EntidadeBase
    {
        [NHibernate.Mapping.Attributes.Id(0, Name = "Codigo", Type = "System.Int64", Column = "AMR_CODIGO")]
        [NHibernate.Mapping.Attributes.Generator(1, Class = "native")]
        public virtual long Codigo { get; set; }

        [NHibernate.Mapping.Attributes.Property(0, Name = "CodigoGeralErro", Column = "AMR_CODIGO_GERAL_ERRO", TypeType = typeof(string), Length = 50, NotNull = false)]
        public virtual string CodigoGeralErro { get; set; }

        [NHibernate.Mapping.Attributes.Property(0, Name = "CodigoErro", Column = "AMR_CODIGO_ERRO", TypeType = typeof(string), Length = 50, NotNull = false)]
        public virtual string CodigoErro { get; set; }

        [NHibernate.Mapping.Attributes.Property(0, Name = "NumeroControle", Column = "AMR_NUMERO_CONTROLE", TypeType = typeof(string), Length = 50, NotNull = false)]
        public virtual string NumeroControle { get; set; }

        [NHibernate.Mapping.Attributes.ManyToOne(0, Class = "ArquivoMercante", Column = "AME_CODIGO", NotNull = false, Lazy = NHibernate.Mapping.Attributes.Laziness.Proxy)]
        public virtual ArquivoMercante ArquivoMercante { get; set; }

        public virtual string Descricao
        {
            get
            {
                return CodigoGeralErro;
            }
        }

        public virtual string DescricaoErro
        {
            get
            {
                switch (CodigoErro)
                {
                    case "EE0": return "Arquivo recusado, tipo de registro não pode ser identificado.";
                    case "EE1": return "Quantidade de Conhecimentos informada não é numérica.";
                    case "EE2": return "Quantidade de Conhecimentos informada é igual a zero.";
                    case "EE3": return "Empresa de Navegação / NVOCC com formato inválido ou não informada.";
                    case "EE4": return "Empresa de Navegação / NVOCC não consta do cadastro.";
                    case "EE5": return "Agência de Navegação / Desconsolidadora com formato inválido.";
                    case "EE6": return "Agência de Navegação / Desconsolidadora não consta do cadastro.";
                    case "EE7": return "Data de Emissão do Manifesto inválida.";
                    case "EE8": return "Data de Encerramento do Manifesto é maior que a data limite (Data Corrente para LCI e 10 dias após a Data Corrente para demais tipos de Manifesto).";
                    case "EE9": return "Data de Previsão de Atracação (Operação) do Manifesto inválida.";
                    case "EEA": return "Código do Porto de Carregamento não consta na tabela.";
                    case "EEB": return "Código do Porto de Descarregamento não consta na tabela.";
                    case "EEC": return "Código do Terminal Portuário de Carregamento não consta na tabela.";
                    case "EED": return "Código do Terminal Portuário de Descarregamento não consta na tabela.";
                    case "EEE": return "Número da Viagem não informado.";
                    case "EEF": return "Quantidade de Contêiner de 20 não numérico.";
                    case "EEG": return "Quantidade de Contêiner de 40 não numérico.";
                    case "EEH": return "Código da Embarcação (IMO) não existe na tabela.";
                    case "EEI": return "Código da Embarcação (IMO) do Comboio não existe na tabela.";
                    case "EEJ": return "Quantidade de Conhecimentos informados no Manifesto diferente da quantidade de Conhecimentos enviados.";
                    case "EEK": return "Código da Embarcação (IMO) não informado.";
                    case "EEL": return "Código do Porto de Carregamento não informado.";
                    case "EEM": return "Código do Porto de Descarregamento não informado.";
                    case "EEN": return "Código do Terminal Portuário de Descarregamento não informado.";
                    case "EEO": return "Manifesto já existe no Cadastro.";
                    case "EEP": return "Porto Nacional não está associado a um Serviço de Arrecadação. Entre em contato com o SERARR.";
                    case "EEQ": return "Código da Agência de Navegação / Desconsolidadora não informado.";
                    case "EER": return "Número do CE a ser desconsolidado não encontrado no Cadastro.";
                    case "EES": return "Número do CE informado já foi desconsolidado.";
                    case "EET": return "Soma do Peso dos CE desconsolidados fora do limite informado no desconsolidado.";
                    case "EEU": return "Soma do Frete dos CE desconsolidados menor que o informado no desconsolidado.";
                    case "EEV": return "Código do Porto de Carregamento inválido para o tipo de Tráfego.";
                    case "EEW": return "Código do Porto de Descarregamento inválido para o tipo de Tráfego.";
                    case "EEX": return "Código do Terminal Portuário de Carregamento não é do Porto de Carregamento informado.";
                    case "EEY": return "Código do Terminal Portuário de Descarregamento não é do Porto de Descarregamento informado.";
                    case "EEZ": return "Tipo de Tráfego informado diferente do esperado.";
                    case "EF0": return "Número do Conhecimento de Embarque sem informação.";
                    case "EF1": return "Data de Emissão do Conhecimento inválida.";
                    case "EF2": return "Data de Emissão do Conhecimento maior que a data corrente.";
                    case "EF3": return "Código do Tipo de Embalagem para Carga Solta (tipo item 2) inválido na tabela.";
                    case "EF4": return "Consignatário não existe no cadastro.";
                    case "EF5": return "Quantidade de Veículos não numérico.";
                    case "EF6": return "Peso Bruto não numérico.";
                    case "EF7": return "Peso Bruto não informado (igual a zero).";
                    case "EF8": return "Valor Frete Básico não numérico.";
                    case "EF9": return "Valor Frete Básico não informado (igual a zero).";
                    case "EFA": return "Código da Taxa não existe na tabela.";
                    case "EFB": return "Valor da Taxa não numérico.";
                    case "EFC": return "Valor da Taxa não informado (igual a zero).";
                    case "EFD": return "Valor da Taxa informado sem o respectivo código.";
                    case "EFE": return "Indicador Parcial de Contêiner inválido.";
                    case "EFF": return "Indicador Capacidade de Contêiner inválido.";
                    case "EFG": return "Nenhuma ocorrência de Mercadoria preenchida para o tipo de Item de Carga informado.";
                    case "EFH": return "Estado de Destino Final da Carga inválido.";
                    case "EFI": return "Cubagem informada não numérica.";
                    case "EFJ": return "Cubagem não informada (igual a zero).";
                    case "EFK": return "Valor da Taxa do Componente Frete não informado (igual a zero).";
                    case "EFL": return "Valor da Taxa do Componente Frete não numérico.";
                    case "EFM": return "Código de Recolhimento do Componente Frete inválido.";
                    case "EFN": return "Número de Série da Nota Fiscal não informado.";
                    case "EFO": return "Data Emissão da Nota Fiscal não informada.";
                    case "EFP": return "Data Emissão da Nota Fiscal inválida.";
                    case "EFQ": return "Data Emissão da Nota Fiscal maior que data corrente.";
                    case "EFR": return "Volume da Nota Fiscal não numérico.";
                    case "EFS": return "Volume da Nota Fiscal não informado (igual a zero).";
                    case "EFT": return "Nenhuma Mercadoria foi informada.";
                    case "EFU": return "Existe(m) ocorrência(s) em branco, entre códigos de mercadorias. Preencha em Sequência";
                    case "EFV": return "Peso (em kg) da Tara do Contêiner não numérico.";
                    case "EFW": return "Conhecimento já existe no cadastro.";
                    case "EFX": return "Código da Moeda do Frete não informado.";
                    case "EFY": return "Código da Moeda do Frete não existe na tabela.";
                    case "EFZ": return "Código da Moeda da Taxa do Frete não informado.";
                    case "EG0": return "Código da Moeda da Taxa do Frete não existe na tabela.";
                    case "EG1": return "Código do País de Procedência da Carga não existe na tabela.";
                    case "EG2": return "Código do Porto de Origem do Transporte não existe na Tabela.";
                    case "EG3": return "Número da Declaração de Despacho de Exportação (DDE) não informado.";
                    case "EG4": return "Número da Declaração de Despacho de Exportação (DDE) não numérico.";
                    case "EG5": return "Código do País de Destino Final da Carga não existe na tabela.";
                    case "EG6": return "Código do Porto de Transbordo não existe na tabela.";
                    case "EG7": return "Cód. do País de Procedência da Carga inválido na tabela de países.";
                    case "EG8": return "Cód. do País de Destino Final da Carga inválido para o Tipo de Tráfego informado.";
                    case "EG9": return "Código do Porto de Transbordo inválido para o Tipo de Tráfego informado.";
                    case "EGA": return "Registro de Manifesto de Carga não encontrado.";
                    case "EGB": return "Número do Contêiner não informado.";
                    case "EGC": return "Data de Emissão do Conhecimento maior que a Data de Emissão do Manifesto.";
                    case "EGD": return "Porto ainda não implantado pelo DMM.";
                    case "EGE": return "Número do Conhecimento de Embarque duplicado no Manifesto.";
                    case "EGF": return "Tipo de Item de Carga não informado ou inválido.";
                    case "EGG": return "Número Sequencial do Item de Carga não informado ou inválido.";
                    case "EGH": return "Número do BL contém, brancos ou caracteres especiais em seu conteúdo.";
                    case "EGI": return "Identificação do Embarcador não informado.";
                    case "EGJ": return "Manifesto informado em duplicata no arquivo Van.";
                    case "EGK": return "Código de Recolhimento do Frete não informado ou inválido.";
                    case "EGL": return "Categoria da Carga não informada ou inválida.";
                    case "EGM": return "Modalidade do Frete não informada ou inválida.";
                    case "EGN": return "UF de Destino da Carga não consta na tabela.";
                    case "EGO": return "Indicador BL a Ordem não informado ou inválido.";
                    case "EGP": return "Indicador de Consignatário Estrangeiro não informado ou inválido para o Tipo de Tráfego informado.";
                    case "EGQ": return "Código do Componente do Frete não informado ou inválido na tabela.";
                    case "EGR": return "CNPJ / CPF do Embarcador inválido no cadastro.";
                    case "EGS": return "CNPJ / CPF do Consignatário inválido.";
                    case "EGT": return "Embarcação de Transbordo Nacional não informado ou inválido na tabela.";
                    case "EGU": return "Porto de Destino Final não informado ou inválido na tabela.";
                    case "EGV": return "Identificação do Consignatário não informado.";
                    case "EGW": return "Porto de Transbordo no Exterior inválido na tabela.";
                    case "EGX": return "País de Procedência não informado.";
                    case "EGY": return "Número do Passaporte Estrangeiro não informado, para Indicador Consignatário Estrangeiro igual a ‘S’.";
                    case "EGZ": return "Nome do Consignatário Estrangeiro não informado, para Indicador Consignatário Estrangeiro igual a ‘S’.";
                    case "EH0": return "Tipo de Contêiner não informado.";
                    case "EH1": return "Tipo de Contêiner inválido na Tabela.";
                    case "EH2": return "Número do Contêiner inválido.";
                    case "EH3": return "Peso Bruto (em kg) do Item de Carga não numérico.";
                    case "EH4": return "Peso (em kg) da Tara do Contêiner não informado (igual a zero).";
                    case "EH5": return "Código do Tipo de Embalagem para Carga Solta (Tipo Item 2) não informado.";
                    case "EH6": return "Quantidade de Item para Carga Solta não Numérico.";
                    case "EH7": return "Código do Tipo de Granel (tipo item 3) não informado.";
                    case "EH8": return "Texto Descrição Granel (tipo item 3) não informado.";
                    case "EH9": return "Número do Chassi do Veículo não informado.";
                    case "EHA": return "Nome da Marca (tipo item 2 ou 4) não informado.";
                    case "EHB": return "Nome da Contramarca (tipo item 2 ou 4) não informado.";
                    case "EHC": return "Código de Mercadoria Perigosa inválido na tabela.";
                    case "EHD": return "Código da Classe de Mercadoria Perigosa não informado.";
                    case "EHE": return "Número Lacre do Contêiner não informado.";
                    case "EHF": return "CNPJ / CPF Emitente da Nota Fiscal não informado ou inválido no cadastro (CNPJ / CPF).";
                    case "EHG": return "Inscrição do Emitente da Nota Fiscal não informado ou inválido.";
                    case "EHI": return "Código da Mercadoria do Item não existe na tabela de mercadorias.";
                    case "EHJ": return "Valor da Mercadoria da Nota Fiscal não numérico.";
                    case "EHK": return "Peso Bruto (em kg) do Item de Carga não informado (igual a zero).";
                    case "EHL": return "CNPJ / CPF da parte a ser notificada inválido no cadastro.";
                    case "EHM": return "Identificação da parte a ser notificada não informado.";
                    case "EHN": return "Quantidade de Contêiner Vazio informado não numérico.";
                    case "EHO": return "Quantidade de Contêiner(s) Vazio(s) informada no Manifesto diferente da quantidade de Contêiner(s) Vazio(s) enviada.";
                    case "EHP": return "Soma da Cubagem dos CE Desconsolidados menor que a informada no Desconsolidado.";
                    case "EHQ": return "Número Sequencial do Item Contêiner Vazio inválido.";
                    case "EHR": return "Nome do Navio de Transbordo no Exterior deve ser informado na condição de: Porto de Origem informado no Conhecimento ser diferente do Porto de Carregamento informado no Manifesto.";
                    case "EHS": return "Número da Nota Fiscal não informado ou inválido.";
                    case "EHT": return "Número BL do Primeiro Transporte deve ser informado na condição de: Porto de Origem informado no Conhecimento ser diferente do Porto de Carregamento informado no Manifesto.";
                    case "EHU": return "Nome do Navio do Primeiro Transporte deve ser informado na condição de: Porto de Origem informado no Conhecimento ser diferente do Porto de Carregamento informado no Manifesto.";
                    case "EHV": return "Data Emissão do BL do Primeiro Transporte deve ser informada/válida na condição de: Porto de Origem informado no Conhecimento ser diferente do Porto de Carregamento informado no Manifesto.";
                    case "EHW": return "Número do CE-MERCANTE informado para Associação inexistente na Base MERCANTE.";
                    case "EHX": return "Valor do Frete Total Baldeação não informado ou inválido.";
                    case "EHY": return "Código da Moeda Frete de Baldeação não informada ou inválida na tabela.";
                    case "EHZ": return "Código da Mercadoria do Item diferente de 8 posições numéricas ou diferente de (4 posições numéricas + 4 brancos) ou diferente de (4 posições numéricas + ‘0000’).";
                    case "EI0": return "Quantidade de Item para Carga Solta (tipo item 2) não Informada (igual a zero).";
                    case "EI1": return "Código do Tipo de Granel (tipo item 3) inválido na Tabela.";
                    case "EI2": return "Quantidade de Itens de Carga Informada no Conhecimento diferente da quantidade enviada.";
                    case "EI3": return "Nenhum Item de Carga informado para o Conhecimento enviado.";
                    case "EI4": return "Terminal Portuário de Descarregamento informado no Conhecimento não é um dos Terminais Portuários de Descarregamento informado no Manifesto.";
                    case "EI5": return "Código do Porto de Transbordo no Exterior deve ser informado na condição de: Porto de Origem informado no Conhecimento ser diferente do Porto de Carregamento informado no Manifesto.";
                    case "EI6": return "Código do Porto de Transbordo no Exterior não deve ser informado na condição de : Porto de Origem informado no Conhecimento ser igual ao Porto de Carregamento informado no Manifesto.";
                    case "EI7": return "Nome do Navio de Transbordo no Exterior não deve ser Informado na condição de : Porto de Origem informado no Conhecimento ser igual ao Porto de Carregamento informado no Manifesto.";
                    case "EI8": return "Número do BL Primeiro Transporte não deve ser Informado na condição de Porto de Origem informado no Conhecimento ser igual ao Porto de Carregamento Informado no Manifesto.";
                    case "EI9": return "Nome do Navio Primeiro Transporte não deve ser informado na condição de Porto de Origem informado no Conhecimento ser igual ao Porto de Carregamento Informado no Manifesto.";
                    case "EIA": return "Data de Emissão do Primeiro Transporte não deve ser informado na condição de : Porto de Origem informado no Conhecimento ser igual ao Porto de Carregamento Informado no Manifesto.";
                    case "EIB": return "CNPJ / CPF do Consignatário não deve ser Informado quando indicador de BL A Ordem estiver informado (igual a ‘S’).";
                    case "EIC": return "Indicador de Consignatário Estrangeiro Não deve ser informado (‘N’) quando indicador de BL A Ordem estiver informado (igual a ‘S’).";
                    case "EID": return "Número do Contêiner Convenience informado para a Modalidade de Frete = HH.";
                    case "EIE": return "Contêiner Vazio não existe na Função de Associação de um número de Manifesto existente e previamente informado.";
                    case "EIF": return "Indicador de Inclusão/Associação no Manifesto de Baldeação não informado ou inválido.";
                    case "EIG": return "Número do Manifesto de Baldeação para Associação não informado.";
                    case "EIH": return "Número do Manifesto de Baldeação para Associação não ativo no cadastro.";
                    case "EII": return "Quantidade de Contêiner Vazio informada no Manifesto de Baldeação para associação com Número do Manifesto informado, diferente de zero.";
                    case "EIJ": return "Código da Moeda Frete Baldeação inválida para o tipo de Tráfego do CE-MERCANTE informado.";
                    case "EIK": return "Manifesto e Conhecimento informados já associados.";
                    case "EIL": return "Não Permitido Associação. Porto de Carregamento informado no Manifesto a Associar igual ao Porto de Carregamento de outro Manifesto já Associado a este Conhecimento.";
                    case "EIM": return "Não Permitido Associação. Porto de Descarregamento informado no Manifesto a Associar igual ao Porto de Descarregamento de outro Manifesto já Associado a este Conhecimento.";
                    case "EIN": return "Tipo de Tráfego do Número de Manifesto inválido para associação solicitada.";
                    case "EIO": return "Conhecimento informado com Categoria da Carga inválida para Associação solicitada.";
                    case "EIP": return "Conhecimento informado com Tipo de Tráfego inválido para Associação solicitada.";
                    case "EIQ": return "Tipo de Tráfego do Número de Manifesto Principal inválido.";
                    case "EIR": return "Código de Recolhimento do Componente Frete não informado ou inválido.";
                    case "EIS": return "O Código de Terminal Portuário incompatível para inclusão de Manifesto de Passagem.";
                    case "EIT": return "Terminal Portuário de Carregamento informado no Conhecimento não é um dos Terminais Portuários de Carregamento informado no Manifesto.";
                    case "EIU": return "Nro do CE-MERCANTE informado não existe no Conhecimento Passagem.";
                    case "EIV": return "Nro Manifesto Informado para Associação não existe na Base MERCANTE.";
                    case "EIW": return "Código do Terminal Portuário de Descarregamento do Conhecimento a Associar não pode ser igual aos Terminais Portuários de Carregamento do Manifesto.";
                    case "EIX": return "Código do Terminal Portuário de Carregamento do Conhecimento a Associar não pode ser igual aos Terminais Portuários de Descarregamento do Manifesto.";
                    case "EIY": return "Categoria da Carga informada no Conhecimento incompatível com o Tipo de Tráfego.";
                    case "EIZ": return "Conhecimento Longo Curso Exportação já possui um Manifesto Principal Longo Curso Exportação associado.";
                    case "EJ0": return "Terminal Portuário de Descarregamento X Recinto Alfandegado inconsistentes na tabela MERCANTE.";
                    case "EJ1": return "Descrição de Mercadoria não informada.";
                    case "EJ2": return "NR CE-MASTER Informado já possui isenção ou suspensão.";
                    case "EJ3": return "NR CE-MERCANTE informado já pagou AFRMM.";
                    case "EJ4": return "Agência desconsolidadora não está cadastrada como Agência Sub-estabelecida.";
                    case "EJ5": return "Problema ao transformar o Conhecimento em Conhecimento MASTER. Favor entrar em contato com a Central de Atendimento e Suporte (CAS) informando o Número do CEMERCANTE o qual deseja Desconsolidar.";
                    case "EJ6": return "Ao menos 1(um) registro de Item de Carga tipo = Solta ou Veículo deve ser informado, quando o Nro Contêiner Ships Convenience no registro do Conhecimento correspondente estiver preenchido.";
                    case "EJ7": return "Indicador de BL Serviço não informado.";
                    case "EJ8": return "Indicador de BL Serviço diferente de ‘S’ ou ‘N’.";
                    case "EJ9": return "Quantidade de Notas Fiscais informada no Conhecimento diferente da quantidade enviada.";
                    case "EJA": return "Conhecimento sem registro de Nota Fiscal.";
                    case "EJB": return "Código de Mercadoria informado no Item de Carga do CE-FILHOTE não existente nos Itens de Carga do Respectivo CE-MASTER.";
                    case "EJC": return "Nro de Contêiner informado no Item de Carga tipo Contêiner do CE-FILHOTE Não existente nos Itens de Carga tipo contêiner do respectivo CE-MASTER.";
                    case "EJD": return "Quantidade de Itens de Carga informado no registro de conhecimento não numérico.";
                    case "EJE": return "Quantidade de Itens de Carga informado no registro de conhecimento igual a zero.";
                    case "EJF": return "Quantidade de Notas Fiscais informada no registro de conhecimento não numérico.";
                    case "EJG": return "Quantidade de Notas Fiscais informada no registro de conhecimento igual a zero.";
                    case "EJH": return "Número CE-MERCANTE Original deve ser preenchido com zeros quando indicador BL Serviço igual a ‘N’.";
                    case "EJI": return "Número CE-MERCANTE Original deve ser maior que zero e válido quando indicador BL Serviço Igual a ‘S’.";
                    case "EJJ": return "Valor do Frete Básico deve ser igual a zero quando Indicador BL Serviço Igual a ‘S’.";
                    case "EJK": return "Código Recolhimento Frete não deve ser informado quando BL Serviço igual a ‘S’.";
                    case "EJL": return "Indicador de BL Serviço não pode ser ‘S’ para Filhote Provisório e Desconsolidado.";
                    case "EJM": return "Número do contêiner informado no item do conhecimento filhote não existe nos itens do seu Respectivo Conhecimento MASTER.";
                    case "EJN": return "Código NCM informado no item do conhecimento filhote não existe nos itens do seu respectivo Conhecimento MASTER.";
                    case "EJO": return "Não é permitido associar. Conhecimento bloqueado pelo Sistema Carga.";
                    case "EJP": return "Número do CE-MASTER já informado no registro de Manifesto (MD) do arquivo de entrada.";
                    case "EJQ": return "CNPJ / CPF do Consignatário deve ser informado quando Indicador de BL Ordem igual a ‘N’ e Indicador de Consignatário Estrangeiro igual a ‘N’.";
                    case "EJR": return "CNPJ / CPF do Consignatário não deve ser preenchido quando Indicador de BL Ordem igual a N’ e Indicador de Consignatário Estrangeiro igual a ‘S’.";
                    case "EJS": return "Não permitido associar Conhecimento pois Manifesto encontra-se no Porto de Destino Final da Carga.";
                    case "EJT": return "Número do CE-MERCANTE Original Informado Não Existente Na Base MERCANTE.";
                    case "EJU": return "Código do Terminal Portuário de Carregamento Não Informado.";
                    case "EJV": return "Código do Porto de Origem não consta na tabela.";
                    case "EJW": return "Código do Porto de Destino não consta na tabela.";
                    case "EJX": return "Código do Porto de Origem não informado.";
                    case "EJY": return "Código do Porto de Destino não informado.";
                    case "EJZ": return "Código do Porto de Origem inválido para o tipo de tráfego.";
                    case "EK0": return "Código do Porto de Destino inválido para o tipo de tráfego.";
                    case "EK1": return "Código do Terminal Portuário de Destino não informado.";
                    case "EK2": return "Código de Terminal Portuário de Origem não pertence ao Porto de Carregamento.";
                    case "EK3": return "Código de Terminal Portuário de Destino não pertence ao Porto de Descarregamento.";
                    case "EK4": return "CNPJ da Agência de Navegação não Ativo no Cadastro (CNPJ).";
                    case "EK5": return "CNPJ da Agência de Navegação inválido no Cadastro (CNPJ).";
                    case "EK6": return "CNPJ da Empresa de Navegação não Ativo no Cadastro (CNPJ).";
                    case "EK7": return "CNPJ da Empresa de Navegação inválido no Cadastro (CNPJ).";
                    case "EK8": return "Tipo de Declaração de Exportação inválida.";
                    case "EK9": return "DV do número da Declaração de Exportação inválido, verifique Parâmetros de Entrada.";
                    case "EKA": return "Tipo de Declaração não Numérico ou igual a zero.";
                    case "EKB": return "Número da Declaração de Exportação não Numérico ou igual a zero.";
                    case "EKC": return "CNPJ do Consignatário não Ativo no Cadastro (CNPJ).";
                    case "EKD": return "CNPJ do Consignatário inválido no Cadastro (CNPJ).";
                    case "EKE": return "CPF do Consignatário não Ativo no Cadastro (CPF).";
                    case "EKF": return "CPF do Consignatário inválido no Cadastro (CPF).";
                    case "EKG": return "Indicador de Entrega no Exterior diferente de ‘S’ ou ‘N’.";
                    case "EKH": return "Indicador de Entrega no Exterior Não deve ser informado quando Indicador de BL A Ordem estiver Informado (Igual a ‘S’).";
                    case "EKI": return "Código do País Destino no Exterior não deve ser Informado quando Indicador de BL A Ordem estiver Informado (Igual a ‘S’).";
                    case "EKJ": return "Número do Passaporte Estrangeiro não pode ser Informado para Indicador de BL A Ordem Informado (Igual a ‘S’).";
                    case "EKK": return "Nome do Consignatário Estrangeiro não pode ser Informado para Indicador de BL A Ordem Informado (Igual a ‘S’).";
                    case "EKL": return "País de Destino no Exterior não pode ter conteúdo quando indicador de entrega No Exterior for igual a ‘N’.";
                    case "EKM": return "Número do Passaporte Estrangeiro não deve ser Informado quando CNPJ ou CPF do Consignatário Nacional for Informado.";
                    case "EKN": return "Nome do Consignatário Estrangeiro Não deve ser Informado quando CNPJ ou CPF do Consignatário Nacional for Informado.";
                    case "EKO": return "Código do País Destino no Exterior deve ser Informado quando Indicador de Entrega no Exterior Informado (Igual a ‘S’).";
                    case "EKP": return "Número de CNPJ ou CPF do Consignatário Nacional não deve ser Informado Quando o Indicador de Entrega no Exterior for Informado (Igual a ‘S’).";
                    case "EKQ": return "Indicador do Consignatário Estrangeiro não deve ser Informado Quando o Indicador de Entrega no Exterior for Informado (Igual a ‘S’).";
                    case "EKR": return "Número do Passaporte Estrangeiro não deve ser informado quando o Indicador de Entrega no Exterior for Informado (Igual a ‘S’).";
                    case "EKS": return "Nome do Consignatário Estrangeiro não tem informação quando o Indicador de Entrega no Exterior for Informado (Igual a ‘S’).";
                    case "EKT": return "Código do País Destino no Exterior Informado está inválido na Tabela SISCOMEX De País Iso2 (CG).";
                    case "EKU": return "Tipo de registro fora da sequência esperada.";
                    case "EKV": return "Indicador de Contêiner Ships Convenience informado, porém diferente de “S”.";
                    case "EKW": return "Número de Contêiner Ships Convenience não deve ser preenchido quando indicador de Contêiner Ships Convenience diferente de “S”.";
                    case "EKX": return "Tipo de Contêiner Ships Convenience não deve ser preenchido quando indicador de Contêiner Ships Convenience diferente de “S”.";
                    case "EKY": return "Número do Lacre de Contêiner Ships Convenience não deve ser preenchido quando indicador de Contêiner Ships Convenience diferente de “S”. OBS: A mensagem refere-se ao número da ocorrência do contêiner ships convenience (Grupo).";
                    case "EKZ": return "Número de Contêiner Ships Convenience não preenchido, ou preenchido, com formato inválido, para indicador de Contêiner Ships Convenience informado(Igual a “S”).";
                    case "EL0": return "Número de Contêiner Ships Convenience inválido para indicador de Contêiner Ships Convenience informado(Igual a “S”).";
                    case "EL1": return "Tipo de Contêiner Ships Convenience deve ser informado quando indicador de Contêiner Ships Convenience informado(Igual a “S”).";
                    case "EL2": return "Tipo de Contêiner Ships Convenience não consta na Tabela Tipo de Contêiner(Tabela SISCOMEX) para indicador de Contêiner Ships Convenience informado(Igual a “S”).";
                    case "EL3": return "Número do Lacre de Contêiner Ships Convenience deve ser informado quando indicador de Contêiner Ships Convenience informado(Igual a “S”).";
                    case "EL4": return "Número e Tipo de Contêiner Ships Convenience devem ser informados quando indicador de Contêiner Ships Convenience informado(Igual a “S”).";
                    case "EL5": return "Item de Carga (Tipo Contêiner), sem informação de Número do Lacre.";
                    case "EL6": return "Tipo de Declaração de Exportação quando preenchido deve ser 1 ou 2 ou 3, correspondente ao campo Número da Declaração de Exportação.";
                    case "EL7": return "Número do Contêiner duplicata nos Registros de Contêiner Vazio.";
                    case "EL8": return "Número do Contêiner duplicata nos Registros de Item de Carga do mesmo Conhecimento.";
                    case "EL9": return "Nro do Contêiner duplicata entre os Registros; Contêiner Vazio e Item de Carga.";
                    case "ELA": return "Nro do Contêiner duplicata entre os Registros de Item de Carga de Conhecimentos diferentes.";
                    case "ELB": return "Identificação do Consignatário deve ser preenchido, quando Indicador de Entrega no Exterior for Informado (Igual a ‘S’).";
                    case "ELC": return "Indicador da Função de Inclusão/Associação e Tipo Carga do Registro M4, Deve ter sua 2a. posição preenchida obrigatoriamente com ‘1’ ou ‘3’.";
                    case "ELD": return "A segunda posição do campo Indicadores da Função/Associação e Tipo de Carga incompatível com o tráfego do Conhecimento informado, a ser associado.";
                    case "ELE": return "Indicador da Função de Inclusão/Associação e Tipo Carga do Registro M6, Deve ter sua 2a posição preenchida obrigatoriamente com ‘I’ ou ‘E’ ou ‘P’.";
                    case "ELF": return "Indicador da Função de Inclusão/Associação e Tipo Carga do Registro ME, Deve ter sua segunda posição preenchida obrigatoriamente com ‘E’.";
                    case "ELG": return "O MASTER deste conhecimento filhote não está no seu porto de destino final.";
                    case "ELH": return "Não permitido associar. Existe pelo menos um conhecimento filhote deste MASTER com NIC vinculado.";
                    case "ELI": return "Item de Carga tipo = contêiner ou granel não deve existir para conhecimento com Existência de Ships Convenience.";
                    case "ELJ": return "O conteúdo da Modalidade de Frete = NA (Não se Aplica), não permite a existência de Item de Carga Tipo = Contêiner, para o respectivo Conhecimento.";
                    case "ELK": return "Porto de Transbordo no Exterior deve ser Porto Estrangeiro.";
                    case "ELL": return "CE-MERCANTE Original não deve ser BL Serviço (IN-BL-SERVICO igual a ‘S’).";
                    case "ELM": return "Data de Validade da Agência Desconsolidadora cadastrada como Substabelecida está vencida no cadastro de Subestabelecimento.";
                    case "ELN": return "Agência de Navegação não é cadastrada como Desconsolidadora.";
                    case "ELO": return "Agência Desconsolidadora não representa o NVOCC.";
                    case "ELP": return "Data de validade da representação da Agência Desconsolidadora em relação ao NVOCC, encontra-se vencida.";
                    case "ELQ": return "Empresa não cadastrada como NVOCC.";
                    case "ELR": return "CNPJ / CPF Emitente da Nota Fiscal não Ativo no Cadastro (CNPJ / CPF).";
                    case "ELS": return "Arquivo Incompleto.";
                    case "ELT": return "Indicador de BL Serviço não pode ser ‘N’ para o Tipo de Tráfego informado.";
                    case "ELU": return "CPF não pertence a Agência de Navegação.";
                    case "ELV": return "CPF não pertence a Empresa de Navegação.";
                    case "ELX": return "Empresa de Navegação deve ser nacional quando a Agência de Navegação não for informado.";
                    case "ELY": return "Empresa NVOCC não representa Consignatário do Conhecimento MASTER.";
                    case "ELZ": return "Não pode haver Códigos de Mercadorias repetidos no mesmo Item.";
                    case "ELW": return "Desconsolidação não permitida. CE - MERCANTE já vinculado a DI, DSI ou DTA.";
                    case "EM0": return "Não Permitida a Inclusão de Manifesto de Empresa NVOCC.";
                    case "EM1": return "Para Código de Empresa de Navegação Estrangeira deve-se informar Agência de Navegação com CNPJ válido.";
                    case "EM2": return "Terminal Portuário de Carregamento X Recinto Alfandegado inconsistentes na tabela MERCANTE EM3 Código do SERARR inexistente na Tabela.";
                    case "EM4": return "Data de Emissão do Conhecimento não informada.";
                    case "EM5": return "Terminal Portuário de Carregamento não deve ser informado para este tipo de tráfego.";
                    case "EM6": return "Terminal Portuário de Descarregamento não deve ser informado para este tipo de tráfego.";
                    case "EM7": return "Soma dos pesos dos Itens maior que 999.999.999,999 kg.";
                    case "EM8": return "Indisponibilidade de realizar conversão/cotação de moeda estrangeira.";
                    case "EM9": return "CPF não pertence a Agência Desconsolidadora.";
                    case "EMA": return "Não é permitido desconsolidar. Conhecimento bloqueado pelo Sistema Carga.";
                    case "EMB": return "Código NCM do Item é obrigatório se no Conhecimento de Passagem for informado Porto de Destino Nacional.";
                    case "EMC": return "Associação deste Conhecimento não permitida. O conhecimento MASTER do House informado ainda não foi Desunitizado. Faça Associação pelo CE MASTER.";
                    case "EMD": return "Limite de 191 Códigos de Erros por registro / linha atingido. Favor corrija e resubmeta o arquivo.";
                    case "EME": return "Campo Indicador de carga movimentada na estadia inválido, isto é, diferente de 'S', de 'N' e de branco.";
                    case "EMF": return "Item de Carga ou CE-MERCANTE não encontrado no sistema.";
                    case "EMG": return "Campo Quantidade da carga perigosa diferente de branco e não numérico.";
                    case "EMH": return "Campo Volume da Carga Perigosa diferente de branco e não numérico.";
                    case "EMI": return "Campos de Item Complementar informados já se encontram na Base MERCANTE.";
                    case "EMJ": return "Campo Código ONU da Mercadoria – Número ONU diferente de branco e não numérico.";
                    case "EMM": return "Campo Ficha de Emergência para derramamento inválido, isto é, diferente de 'S', de 'N, e de branco.";
                    case "EMO": return "Campo Número do Pacote (IMO) diferente de branco e não numérico.";
                    case "EMP": return "Campo Reserva / Número de referência diferente de branco e não numérico.";
                    case "EMQ": return "Campo Peso Líquido - Massa (Kg) diferente de branco e não numérico.";
                    case "EMS": return "Campo Ponto de fulgor (em graus Celsius) diferente de branco e não numérico.";
                    case "EMT": return "Campo Código da prioridade da carga perigosa diferente de branco e não numérico.";
                    case "EMV": return "Campo Temperatura do produto em graus Celsius diferente de branco e não numérico.";
                    case "EMY": return "Campo Indicador de utilização embalagem de madeira inválido, isto é, diferente de 'S', de 'N' e de branco.";
                    case "EMZ": return "Campo Embalagem de madeira bruta dever ser informado quando Indicador de utilização embalagem de madeira for informado com 'S'.";
                    case "EMW": return "Campo Embalagem de madeira bruta diferente de 720, 721 ou 722.";
                    case "EN0": return "Campo Número de identificação da mercadoria diferente de branco e não numérico.";
                    case "EN2": return "Campo Indicador de Carga de madeira bruta inválido, isto é, diferente de 'S', de 'N' e de branco.";
                    case "EN3": return "Campo Indicador de Carga de madeira bruta deve ser informado apenas para Itens Tipo Granel e Carga Solta.";
                    case "EN4": return "Campo Temperatura do contêiner em graus Celsius diferente de branco e não numérico.";
                    case "EN5": return "Campo Temperatura do contêiner em graus Celsius só dever ser informado quando o Item for Tipo Contêiner.";
                    case "EN7": return "Campo Marca da mercadoria só deve ser informado quando o Item for Tipo Contêiner.";
                    case "EN9": return "Campo Contramarca da mercadoria só deve ser informado quando o Item for Tipo Contêiner.";
                    case "EOA": return "Campo Quantidade de volumes diferente de branco e não numérico.";
                    case "EOB": return "Campo Quantidade de volumes só dever ser informado quando o Item for Tipo Contêiner.";
                    case "EOC": return "Campo Indicador de utilização embalagem de madeira se diferente de branco, deve ser informado apenas para Itens Tipo Contêiner, Granel e Carga Solta.";
                    case "EOD": return "Campo Embalagem de madeira bruta deve ser informado apenas para Itens Tipo Contêiner, Granel e Carga Solta.";
                    case "EOE": return "Campo Número de identificação da mercadoria deve ser informado apenas para Itens Tipo Contêiner, Granel e Carga Solta.";
                    case "EOF": return "Campo Descrição completa da marca ou BL deve ser informado apenas para Itens Tipo Contêiner, Granel e Carga Solta.";
                    case "ENH": return "Item do Tipo Veículo não possui informações complementares. Todos os campos complementares não devem ser informados.";
                    case "ENI": return "Tentativa de inclusão de item temporário já cadastrado.";
                    case "ENJ": return "Tentativa de inclusão de item definitivo já cadastrado.";
                    case "ENK": return "Tentativa de inclusão de item provisório já cadastrado.";
                    case "ENL": return "Tentativa de efetivar item provisório não cadastrado.";
                    case "ENM": return "Tentativa de efetivar item provisório já efetivado com mesmo CE-MERCANTE.";
                    case "ENN": return "Tentativa de efetivar item provisório já efetivado com outro CE-MERCANTE.";
                    case "ENO": return "Tentativa de efetivar item temporário não cadastrado.";
                    case "ENP": return "Tentativa de efetivar item temporário já efetivado com mesmo CE-MERCANTE.";
                    case "ENQ": return "Tentativa de efetivar item temporário já efetivado com outro CE-MERCANTE.";
                    case "ENR": return "Dados complementares não encontrados para este item.";
                    case "ENS": return "Tentativa de exclusão de item provisório que já foi efetivado com CE-MERCANTE.";
                    case "ENT": return "Campo Temperatura do contêiner fora do intervalo de –272 a 9726 graus Celsius.";
                    case "ENU": return "Campo Temperatura do produto fora do intervalo de –272 a 9726 graus Celsius.";
                    case "ENV": return "Campo Ponto de fulgor fora do intervalo de –272 a 9726 graus Celsius.";
                    case "ENX": return "Não é possível informar, via EDI / UPLOAD, dados de Item Complementar para CE do Tipo Provisório.";
                    case "ENY": return "CE-MERCANTE não encontrado no sistema.";
                    case "EOG": return "Campo Código NCM de Mercadoria (no Dado Complementar) não informado.";
                    case "EOH": return "Campo Código NCM de Mercadoria (no Dado Complementar) diferente de 8 posições numéricas ou diferente de 4 posições numéricas + 4 brancos.";
                    case "EOI": return "Campo Código IMO da Mercadoria Perigosa não informado ou inválido.";
                    case "EOJ": return "Campo Nome Técnico do Produto deve ser informado quando 'Código IMO da Mercadoria Perigosa' for preenchido.";
                    case "EOK": return "Campo Indicador de carga movimentada deve ser informado com 'S' ou 'N' quando 'Código IMO da Mercadoria Perigosa' for preenchido.";
                    case "EOL": return "Campo Marca da Mercadoria só deve ser informado quando o Item for Tipo Contêiner.";
                    case "EOM": return "Campo Marca da Mercadoria não informado para Item do Tipo Contêiner.";
                    case "EON": return "Campo Contramarca da Mercadoria só deve ser informado quando o Item for Tipo Contêiner.";
                    case "EOO": return "Campo Quantidade de Volumes só deve ser informado quando o Item for Tipo Contêiner.";
                    case "EOP": return "Campo Quantidade de Volumes não informado ou inválido para Item do Tipo Contêiner.";
                    case "EOQ": return "Campo Tipo de Embalagem só deve ser informado quando o Item for Tipo Contêiner.";
                    case "EOR": return "Campo Tipo de Embalagem não informado ou inválido para Item do Tipo Contêiner.";
                    case "EOS": return "Campo Indicador de carga movimentada deve ser preenchido com branco quando 'Código IMO da Mercadoria Perigosa' não for informado.";
                    case "EOT": return "Campo Packing Group deve ser preenchido com brancos quando 'Código IMO da Mercadoria Perigosa' não for informado.";
                    case "EOU": return "Campo Quantidade de Carga Perigosa deve ser preenchido com brancos quando 'Código IMO da Mercadoria Perigosa' não for informado.";
                    case "EOV": return "Campo Volume de Carga Perigosa deve ser preenchido com brancos quando 'Código IMO da Mercadoria Perigosa' não for informado.";
                    case "EOX": return "Campo Código IMO da Mercadoria Perigosa dever ser informado quando dados de Mercadoria Perigosa forem preenchidos.";
                    case "EOY": return "Campo Código ONU da Mercadoria - NÚMERO ONU deve ser preenchido com brancos quando 'Código IMO da Mercadoria Perigosa' não for informado.";
                    case "EOZ": return "Campo Divisão de Risco deve ser preenchido com brancos quando 'Código IMO da Mercadoria Perigosa' não for informado.";
                    case "EOW": return "Campo Classe da Mercadoria Perigosa deve ser preenchido com brancos quando 'Código IMO da Mercadoria Perigosa' não for informado.";
                    case "EO0": return "Campo Espécie de Pacotes deve ser preenchido com brancos quando 'Código IMO daMercadoria Perigosa' não for informado.";
                    case "EO1": return "Campo Indicador Ficha de Emergência para Derramamento deve ser preenchido com branco quando 'Código IMO da Mercadoria Perigosa' não for informado.";
                    case "EO2": return "Campo Nome Técnico do Produto deve ser preenchido com brancos quando 'Código IMO da Mercadoria Perigosa' não for informado.";
                    case "EO3": return "Campo Reserva / Número de Referência deve ser preenchido com brancos quando 'Código IMO da Mercadoria Perigosa' não for informado.";
                    case "EO4": return "Campo Peso Líquido - Massa deve ser preenchido com brancos quando 'Código IMO da Mercadoria Perigosa' não for informado.";
                    case "EO5": return "Campo Identificação do Poluente Marinho deve ser preenchido com brancos quando 'Código IMO da Mercadoria Perigosa' não for informado.";
                    case "EO6": return "Campo Ponto de Fulgor deve ser preenchido com brancos quando 'Código IMO da Mercadoria Perigosa' não for informado.";
                    case "EO7": return "Campo Código da Prioridade da Carga Perigosa deve ser preenchido com brancos quando 'Código IMO da Mercadoria Perigosa' não for informado.";
                    case "EO8": return "Campo Motivo da Prioridade da Carga Perigosa deve ser preenchido com brancos quando 'Código IMO da Mercadoria Perigosa' não for informado.";
                    case "EO9": return "Campo Temperatura do Produto deve ser preenchido com brancos quando 'Código IMO da Mercadoria Perigosa' não for informado.";
                    case "EPA": return "Campo Posição de Estivagem deve ser preenchido com brancos quando 'Código IMO da Mercadoria Perigosa' não for informado.";
                    case "EPB": return "Não é permitido informar Dado Complementar para Conhecimento Filhote EPC Campo Embalagem de madeira bruta deve ser preenchido com brancos quando 'Indicador de utilização embalagem de madeira' não for informado.";
                    case "EPD": return "Código NCM informado não encontrado no Item do Conhecimento.";
                    case "EPE": return "Usuário não autorizado a Incluir ou Alterar Dados Complementares para o Item do Conhecimento informado.";
                    case "EPF": return "Problema ao validar situação de CPF e/ou CNPJ na base.";
                    case "EPG": return "Erro na sub-rotina de acesso ao Cadastro de CPF e/ou CNPJ.";
                    case "EPH": return "Campo Número Sequencial do Item de Carga (no Dado Complementar) não numérico.";
                    case "EPI": return "Campo Número do CE-MERCANTE (no Dado Complementar) não numérico.";
                    case "EPJ": return "Sequencial de identificação de Mercadoria do Dado Complementar a ser alterado não encontrado na base.";
                    case "EPK": return "Campo Tipo de Embalagem informado não existe na tabela.";
                    case "EQ0": return "Campo Nome de Consignatário Estrangeiro LCE é obrigatório.";
                    case "EQ1": return "Campo Endereço do Consignatário Estrangeiro LCE é obrigatório.";
                    case "EQ2": return "Campo Identificação DU-E deve estar em branco quando o campo Tipo de declaração de exportação não for informado.";
                    case "EQ3": return "Campo Identificação RUC deve estar em branco quando o campo Tipo de declaração de exportação não for informado.";
                    case "EQ4": return "Campo Tipo de declaração de exportação deve ser numérico entre valores 1 a 3 e 5 a 7 apenas.";
                    case "EQ5": return "Campo Identificação DU-E só pode ser informado quando o campo Tipo de declaração de exportação for '6'.";
                    case "EQ6": return "Campo Identificação RUC só pode ser informado quando o campo Tipo de declaração de exportação for '7'.";
                    case "EQ7": return "Campo Identificação DU-E é obrigatório para o campo Tipo de declaração de exportação igual a '6'.";
                    case "EQ8": return "Campo Identificação RUC deve estar em branco para o campo Tipo de declaração de exportação igual a '6'.";
                    case "EQ9": return "Campo Identificação DU-E deve estar em branco para o campo Tipo de declaração de exportação igual a '7'.";
                    case "EQA": return "Campo Identificação RUC é obrigatório para o campo Tipo de declaração de exportação igual a '7'.";
                    case "EQB": return "Campo Tipo de declaração de exportação deve ser preenchido entre os valores 1 a 3 e 5 a 7 apenas.";
                    case "EQC": return "Campo Identificação DU-E não possui 14 posições ou no formato inválido.";
                    case "EQD": return "Digito Verificador do Campo Identificação DU-E inválido.";
                    case "EQE": return "Campo Identificação RUC não possui ao menos 12 posições ou no formato inválido.";
                    case "EQF": return "Campos Número da Declaração de Exportação e Identificação DU-E preenchidos. Informe apenas um documento de Exportação, conforme domínio descrito no layout.";
                    case "EQG": return "Campos Número da Declaração de Exportação e Identificação RUC preenchidos. Informe apenas um documento de Exportação, conforme domínio descrito no layout.";
                    case "EA0": return "Conteúdo ou Assinatura Digital corrompida.";
                    case "EA1": return "Conteúdo sem Assinatura Digital.";
                    case "EA2": return "Certificado encontra-se expirado.";
                    case "EA3": return "A Certificação está revogada.";
                    case "EA4": return "Erro no processamento na Assinatura Digital.";
                    case "EA5": return "O Certificado pertence a um CNPJ.";
                    case "EA6": return "Cadeia de Certificados inválida ou o Certificado é Auto-Assinado.";
                    case "EA7": return "Codificação DER ( Distinguished Encoding Rules ) incorreta. Possível arquivo corrompido.";
                    default:
                        return string.Empty;
                }
            }
        }
    }
}
