var ConfiguracaoObservacaoCTe = function () { };

ConfiguracaoObservacaoCTe.prototype = {
    _obterHTML: function () {
        var self = this;

        var p = new promise.Promise();

        $.get("Content/Static/Configuracao/ObservacaoCTe.html?dyn=" + guid(), function (data) {
            self._htmlObservacao = data;
            if (self.Parametros.KnoutObservacaoTerceiro != null) {
                $.get("Content/Static/Configuracao/ObservacaoCTeTerceiro.html?dyn=" + guid(), function (data) {
                    self._htmlObservacaoTerceiro = data;
                    p.done();
                });
            } else {
                p.done();
            }
        });

        return p;
    },
    Load: function (obj) {
        var self = this;

        self.Parametros = obj;

        var p = new promise.Promise();

        LoadLocalizationResources("Configuracoes.ObservacaoCTe").then(function () {

            self._obterHTML().then(function () {
                self._configurarHTML();
                self._carregarCampos();
                p.done();
            });
            LocalizeCurrentPage();
        });
        return p;

    },
    _configurarHTML: function () {
        var self = this;

        $("#" + self.Parametros.IdContainerObservacao).html(self._htmlObservacao);

        if (self.Parametros.KnoutObservacaoTerceiro != null)
            $("#" + self.Parametros.IdContainerObservacaoTerceiro).html(self._htmlObservacaoTerceiro);
    },
    _carregarCampos: function () {

        var self = this;

        self.Parametros.Knouckout.TagCNPJEmitente = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#CNPJEmitente"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.CNPJDoEmitente, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagNomeEmitente = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#NomeEmitente"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.NomeDoEmitente, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagCNPJTomador = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#CNPJTomador"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.CNPJDoTomador, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagNomeTomador = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#NomeTomador"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.NomeDoTomador, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagCNPJRemetente = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#CNPJRemetente"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.CNPJDoRemetente, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagNomeRemetente = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#NomeRemetente"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.NomeDoRemetente, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagCNPJDestinatario = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#CNPJDestinatario"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.CNPJDoDestinatario, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagNomeDestinatario = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#NomeDestinatario"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.NomeDoDestinatario, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagNumeroCTe = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#NumeroCTe"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.NumeroDoCTe, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagSerieCTe = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#SerieCTe"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.SerieDoCTe, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagValorTotalPrestacao = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#ValorTotalPrestacao"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.ValorTotalDaPrestacao, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagValorFrete = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#ValorFrete"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.ValorFrete, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagNumeroCarga = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#NumeroCarga"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.NumeroDaCarga, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagNumeroPedido = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#NumeroPedido"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.NumeroDoPedido, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagRota = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#Rota"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.Rota, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagRotaPedido = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#RotaPedido"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.RotaDoPedido, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagRotaPedidoComValor = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#RotaPedidoComValor"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.RotaDoPedidoComValor, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagPlacas = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#Placas"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.PlacaDoVeiculo, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagRENAVAM = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#RENAVAM"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.RENAVAMDoVeiculo, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagMarcaVeiculo = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#MarcaVeiculo"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.MarcaDoVeiculo, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagCPFMotorista = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#CPFMotorista"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.CPFDoMotorista, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagNomeMotorista = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#NomeMotorista"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.NomeDoMotorista, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagCNHMotorista = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#CNHMotorista"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.CNHDoMotorista, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagRGMotorista = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#RGMotorista"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.RGDoMotorista, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagCodigoTabelaFrete = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#CodigoTabelaFrete"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.CodigoDaTabelaDeFrete, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagCPFOperador = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#CPFOperador"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.CPFDoOperador, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagNomeOperador = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#NomeOperador"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.NomeDoOperador, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagModeloVeicularCarga = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#ModeloVeicularCarga"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.ModeloVeicularDeCarga, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagSeguradora = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#Seguradora"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.Seguradora, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagApoliceSeguro = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#ApoliceSeguro"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.ApoliceDeSeguro, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagChaveDocumentoTransporteAnterior = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#ChaveDocumentoTransporteAnterior"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.ChaveDoDocumentoDeTransporteAnterior, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagNumeroOCADocumentoTransporteAnterior = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#NumeroOCADocumentoTransporteAnterior"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.NumeroOCADocumentoDeTransporteAnterior, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagNumeroNotaFiscal = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#NumeroNotaFiscal"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.NumeroNotaFiscal, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagObservacaoNotaFiscal = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#ObservacaoNotaFiscal"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.ObservacaoNotaFiscal, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagNumeroContainer = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#NumeroContainer"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.NumeroContainer, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagOrdem = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#OrdemPedido"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.OrdemPedido, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagTipoOperacao = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#TipoOperacao"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.TipoOperacao, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagDataAgendamento = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#DataAgendamento"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.DataDeAgendamento, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagFaixaTemperatura = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#FaixaTemperatura"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.FaixaDeTemperatura, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagNumeroOS = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#NumeroOS"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.NumeroOS, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagValorNota = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#ValorNota"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.ValorNota, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagValorADValorem = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#ValorADValorem"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.ValorADValorem, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagMoeda = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#Moeda"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.Moeda, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagValorCotacaoMoeda = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#ValorCotacaoMoeda"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.CotacaoDaMoeda, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagValorTotalMoeda = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#ValorTotalMoeda"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.ValorEmMoeda, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagAdicional1Pedido = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#Adicional1Pedido"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.AdicionalUmPedido, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagAdicional2Pedido = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#Adicional2Pedido"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.AdicionalDoisPedido, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagAdicional3Pedido = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#Adicional3Pedido"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.AdicionalTresPedido, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagAdicional4Pedido = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#Adicional4Pedido"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.AdicionalQuatroPedido, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagAdicional5Pedido = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#Adicional5Pedido"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.AdicionalCincoPedido, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagAdicional6Pedido = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#Adicional6Pedido"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.AdicionalSeisPedido, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagAdicional7Pedido = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#Adicional7Pedido"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.AdicionalSetePedido, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagNumeroDI = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#NumeroDI"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.NumeroDI, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagReserva = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#Reserva"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.Reserva, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagQuantidadeVolumes = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#QuantidadeVolumes"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.QuantidadeDeVolumes, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagLacresCarga = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#LacresCarga"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.LacresDaCarga, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagTipoCarga = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#TipoCarga"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.TipoDeCarga, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagPesoCTe = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#PesoCTe"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.PesoDoCTe, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagPesoCarga = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#PesoCarga"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.PesoDaCarga, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagDataPrevisaoEntrega = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#DataPrevisaoEntrega"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.PrevisaoDeEntrega, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagCodigoConfiguracaoTabelaFrete = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#CodigoConfiguracaoTabelaFrete"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.CodigoConfiguracaoTabelaDeFrete, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagLocRemetente = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#LocRemetente"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.LocalizacaoRemetente, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagLocDestinatario = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#LocDestinatario"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.LocalizacaoDestinatario, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagLocExpedidor = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#LocExpedidor"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.LocalizacaoExpedidor, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagLocRecebedor = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#LocRecebedor"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.LocalizacaoRecebedor, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagUFVeiculo = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#UFVeiculo"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.UFDoVeiculo, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagPercentualBonificacaoTransportador = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#PercentualBonificacaoTransportador"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.PercentualBonificacaoTransportador, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(_CONFIGURACAO_TMS.TipoServicoMultisoftware != EnumTipoServicoMultisoftware.MultiTMS) });
        self.Parametros.Knouckout.TagBancoContaTomador = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#BancoContaTomador"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.BancoDoTomador, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagAgenciaContaTomador = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#AgenciaContaTomador"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.AgenciaContaTomador, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagDigitoContaTomador = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#DigitoContaTomador"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.DigitoContaTomador, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagNumeroContaTomador = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#NumeroContaTomador"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.NumeroContaTomador, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagTipoContaTomador = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#TipoContaTomador"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.TipoContaTomador, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagNumeroCarregamento = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#NumeroCarregamento"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.NumeroCarregamento, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagKMTotalCarga = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#KMTotalCarga"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.KMTotalCarga, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagTipoCargaPedido = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#TipoCargaPedido"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.TipoCargaPedido, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagOutrosNumerosCarga = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#OutrosNumerosCarga"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.OutrosNumerosCarga, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagNumeroDI = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#NumeroDI"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.NumeroDI, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagEmbarque = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#Embarque"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.Embarque, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagMasterBl = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#MasterBL"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.MasterBL, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagNumeroControleCliente = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#NumeroControleCliente "); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.NumeroControleCliente, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        self.Parametros.Knouckout.TagValorValePedagio = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacao.id, "#ValorValePedagio"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.ValorValePedagio, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });


        if (self.Parametros.KnoutObservacaoTerceiro != null) {
            self.Parametros.Knouckout.TagCPFCNPJProprietarioVeiculo = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacaoTerceiro.id, "#CPFCNPJProprietarioVeiculo"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.CPFCNPJDoProprietarioDoVeiculo, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
            self.Parametros.Knouckout.TagIEProprietarioVeiculo = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacaoTerceiro.id, "#IEProprietarioVeiculo"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.IEDoProprietarioDoVeiculo, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
            self.Parametros.Knouckout.TagNomeProprietarioVeiculo = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacaoTerceiro.id, "#NomeProprietarioVeiculo"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.NomeDoProprietarioDoVeiculo, enable: (self.Parametros.KnoutEnable || ko.observable(true)) });
            self.Parametros.Knouckout.TagEnderecoProprietarioVeiculo = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacaoTerceiro.id, "#EnderecoProprietarioVeiculo"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.EnderecoDoProprietarioDoVeiculo, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
            self.Parametros.Knouckout.TagRNTRCProprietarioVeiculo = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacaoTerceiro.id, "#RNTRCProprietarioVeiculo"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.RNTRCDoProprietarioDoVeiculo, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
            self.Parametros.Knouckout.TagPlacaVeiculoTerceiro = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacaoTerceiro.id, "#Placa"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.PlacaDoVeiculo, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
            self.Parametros.Knouckout.TagRENAVAMVeiculoTerceiro = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacaoTerceiro.id, "#RENAVAM"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.RENAVAMDoVeiculo, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
            self.Parametros.Knouckout.TagMarcaVeiculoTerceiro = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacaoTerceiro.id, "#MarcaVeiculo"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.MarcaDoVeiculo, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
            self.Parametros.Knouckout.TagUFVeiculoTerceiro = PropertyEntity({ eventClick: function (e) { InserirTag(self.Parametros.KnoutObservacaoTerceiro.id, "#UFVeiculo"); }, type: types.event, text: Localization.Resources.Configuracoes.ObservacaoCTe.UFDoVeiculo, enable: (self.Parametros.KnoutEnable || ko.observable(true)), visible: ko.observable(true) });
        }
    }
};

