// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.maersk.vessel.smds.operations.MSK
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific; using Newtonsoft.Json;
	
	public partial class carrierDetail : ISpecificRecord
	{
		[JsonIgnore] public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""carrierDetail"",""namespace"":""com.maersk.vessel.smds.operations.MSK"",""fields"":[{""name"":""code"",""doc"":""Carrier code refers to the unique identification code for a particular name of the carrier for a voyage. Example : XPRESS"",""type"":[""null"",""string""]},{""name"":""name"",""doc"":""Carrier name refers to the name of the carrier who is operating the asset(vessel). Example: aREGIONAL CONTAINER/FREIGHTERS LTD"",""type"":[""null"",""string""]},{""name"":""fromDate"",""doc"":""Vessel Carrier from date. Format in long format Example : 1212278400000"",""type"":[""null"",""long""],""logicalType"":""timestamp-millis""},{""name"":""toDate"",""doc"":""Vessel Carrier to date. Format in long format Example : 1212278400000"",""type"":[""null"",""long""],""logicalType"":""timestamp-millis""}]}");
		/// <summary>
		/// Carrier code refers to the unique identification code for a particular name of the carrier for a voyage. Example : XPRESS
		/// </summary>
		private string _code;
		/// <summary>
		/// Carrier name refers to the name of the carrier who is operating the asset(vessel). Example: aREGIONAL CONTAINER/FREIGHTERS LTD
		/// </summary>
		private string _name;
		/// <summary>
		/// Vessel Carrier from date. Format in long format Example : 1212278400000
		/// </summary>
		private System.Nullable<long> _fromDate;
		/// <summary>
		/// Vessel Carrier to date. Format in long format Example : 1212278400000
		/// </summary>
		private System.Nullable<long> _toDate;
		[JsonIgnore] public virtual Schema Schema
		{
			get
			{
				return carrierDetail._SCHEMA;
			}
		}
		/// <summary>
		/// Carrier code refers to the unique identification code for a particular name of the carrier for a voyage. Example : XPRESS
		/// </summary>
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				this._code = value;
			}
		}
		/// <summary>
		/// Carrier name refers to the name of the carrier who is operating the asset(vessel). Example: aREGIONAL CONTAINER/FREIGHTERS LTD
		/// </summary>
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		/// <summary>
		/// Vessel Carrier from date. Format in long format Example : 1212278400000
		/// </summary>
		public System.Nullable<long> fromDate
		{
			get
			{
				return this._fromDate;
			}
			set
			{
				this._fromDate = value;
			}
		}
		/// <summary>
		/// Vessel Carrier to date. Format in long format Example : 1212278400000
		/// </summary>
		public System.Nullable<long> toDate
		{
			get
			{
				return this._toDate;
			}
			set
			{
				this._toDate = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.code;
			case 1: return this.name;
			case 2: return this.fromDate;
			case 3: return this.toDate;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.code = (System.String)fieldValue; break;
			case 1: this.name = (System.String)fieldValue; break;
			case 2: this.fromDate = (System.Nullable<long>)fieldValue; break;
			case 3: this.toDate = (System.Nullable<long>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
