namespace Dominio.ObjetosDeValor.Embarcador.Documentos
{
    public class DadosDocsysCSV
    {
        public string vescode { get; set; }
        public string vessel { get; set; }
        public string voy { get; set; }
        public string dir { get; set; }
        public string ori { get; set; }
        public string oriname { get; set; }
        public string pol { get; set; }
        public string polname { get; set; }
        public string pod { get; set; }
        public string podname { get; set; }
        public string dest { get; set; }
        public string destname { get; set; }
        public string blading { get; set; }
        public string carrier { get; set; }
        public string eta_ets { get; set; }
        public string sh_code { get; set; }
        public string shipper { get; set; }
        public string cn_code { get; set; }
        public string consig { get; set; }
        public string n1_code { get; set; }
        public string notify1 { get; set; }
        public string cst_code { get; set; }
        public string customer1 { get; set; }
        public string fw_code { get; set; }
        public string forwarder { get; set; }
        public string cargospec_ { get; set; }
        public string nor { get; set; }
        public string equip01 { get; set; }
        public string equip02 { get; set; }
        public string equip03 { get; set; }
        public string equip04 { get; set; }
        public string equip05 { get; set; }
        public string equip06 { get; set; }
        public string equip07 { get; set; }
        public string equip08 { get; set; }
        public string equip09 { get; set; }
        public string equip10 { get; set; }
        public string paymode { get; set; }
        public string trspmode { get; set; }
        public string p_frt1 { get; set; }
        public string p_amt2 { get; set; }
        public string p_amt3 { get; set; }
        public string p_amt4 { get; set; }
        public string p_amt5 { get; set; }
        public string p_amt6 { get; set; }
        public string p_amt7 { get; set; }
        public string p_amt8 { get; set; }
        public string p_amt9 { get; set; }
        public string p_amt10 { get; set; }
        public string p_ttl { get; set; }
        public string c_frt1 { get; set; }
        public string c_amt2 { get; set; }
        public string c_amt3 { get; set; }
        public string c_ac_amt4 { get; set; }
        public string c_amt5 { get; set; }
        public string c_amt6 { get; set; }
        public string c_amt7 { get; set; }
        public string c_amt8 { get; set; }
        public string c_amt9 { get; set; }
        public string c_amt10 { get; set; }
        public string c_ttl { get; set; }
        public string curr_ { get; set; }
        public string thc_cust { get; set; }
        public string thc_custeame { get; set; }
        public string lcl_cust { get; set; }
        public string lcl_custname { get; set; }
        public string BLIssue { get; set; }
        public string tariff { get; set; }
        public string commodity_code { get; set; }
        public string commodity_text { get; set; }
        public string TrsPt1 { get; set; }
        public string TrsPt1_txt { get; set; }
        public string TrsPt2 { get; set; }
        public string TrsPt2_txt { get; set; }
        public string AnzTeus { get; set; }
        public string ContPartKz { get; set; }
        public string Cnt01 { get; set; }
        public string Cnt02 { get; set; }
        public string Cnt03 { get; set; }
        public string Cnt04 { get; set; }
        public string Cnt05 { get; set; }
        public string Cnt06 { get; set; }
        public string Cnt07 { get; set; }
        public string Cnt08 { get; set; }
        public string Cnt09 { get; set; }
        public string Cnt10 { get; set; }
        public string Cnt11 { get; set; }
        public string Cnt12 { get; set; }
        public string Cnt13 { get; set; }
        public string Cnt14 { get; set; }
        public string Cnt15 { get; set; }
        public string Cnt16 { get; set; }
        public string Cnt17 { get; set; }
        public string Cnt18 { get; set; }
        public string Cnt19 { get; set; }
        public string Cnt20 { get; set; }
        public string L_Rec_Date { get; set; }
        public string Prepaid_Coll_Remarks { get; set; }
        public string Service { get; set; }
        public string PreVesCd { get; set; }
        public string PreVesText { get; set; }
        public string PreVoy { get; set; }
        public string PreDir { get; set; }
        public string PreOriCd { get; set; }
        public string PreOriTxt { get; set; }
        public string PreDstCd { get; set; }
        public string PreDstTxt { get; set; }
        public string PreBL { get; set; }
        public string PreOwner { get; set; }
        public string OnVesCd { get; set; }
        public string OnVesText { get; set; }
        public string OnVesVoy { get; set; }
        public string OnVesDir { get; set; }
        public string OnOriCd { get; set; }
        public string OnOriTxt { get; set; }
        public string OnDstCd { get; set; }
        public string OnDstTxt { get; set; }
        public string OnBL { get; set; }
        public string OnOwner { get; set; }
        public string BL_Version { get; set; }
        public string Corr_code { get; set; }
        public string Waybil { get; set; }
        public string PlPay { get; set; }
        public string PLPayTxt { get; set; }
        public string BLPrDest { get; set; }
        public string RelOf { get; set; }
        public string RelOfTxt { get; set; }
        public string IssOf { get; set; }
        public string IssOfTxt { get; set; }
        public string UBLI { get; set; }
        public string CopyKZ { get; set; }
        public string BOOKNO { get; set; }
        public string EDI_Src { get; set; }
        public string SpecicNo { get; set; }
        public string Total_GRSWGT { get; set; }
        public string Unit { get; set; }
        public string DMM_MepPrtNo { get; set; }
        public string DMM_BLPrtno { get; set; }
        public string NoITM { get; set; }
        public string NoBLZ { get; set; }
        public string NoTXT { get; set; }
        public string NoEDF { get; set; }
        public string IPWNO { get; set; }
        public string CORTXT { get; set; }
        public string CORTYP { get; set; }
        public string CORENT { get; set; }
        public string CORENTTXT { get; set; }
        public string CORDATE { get; set; }
        public string AgecyO { get; set; }
        public string AgencyI { get; set; }
        public string VoucherDate { get; set; }
        public string DACS_transf { get; set; }
        public string PrecarVes { get; set; }
        public string PrecarVesText { get; set; }
        public string PrecarVoy { get; set; }
        public string PrecarIsVes { get; set; }
        public string FeeLPCode { get; set; }
        public string FeLPText { get; set; }
        public string Agreem__No { get; set; }
        public string Agreem__Name { get; set; }
        public string CNTSTAT { get; set; }
        public string LPlace_Nat_ { get; set; }
        public string LPlace_Un { get; set; }
        public string LPort_Nat_ { get; set; }
        public string LPort_Un { get; set; }
        public string DPort_Nat_ { get; set; }
        public string DPort_Un { get; set; }
        public string DPlace_Nat_ { get; set; }
        public string DPlace_Un { get; set; }
        public string TSH1_Nat { get; set; }
        public string TSH1_Un { get; set; }
        public string TSH2_Nat { get; set; }
        public string TSH2_Un { get; set; }
        public string PayPl_Nat_ { get; set; }
        public string PayPl_Un { get; set; }
        public string Rel__Nat_ { get; set; }
        public string Rel__Un { get; set; }
        public string ISS_Nat_ { get; set; }
        public string ISS_Un { get; set; }
        public string EC_Shipper { get; set; }
        public string EC_Consignee { get; set; }
        public string EC_Notify1 { get; set; }
        public string VoucherNO { get; set; }
        public string StornoNO { get; set; }
        public string ShipperRef { get; set; }
        public string ForwarderRef { get; set; }
        public string EDI_Channel { get; set; }
        public string CTESign { get; set; }
        public string SCAC { get; set; }
        public string Station { get; set; }
    }
}
