const CONTROLLER_GRUPO_MOTORISTAS = "GrupoMotoristas";
const ENDPOINT_PESQUISAR_GRUPO_MOTORISTAS = "Pesquisar";
const ENDPOINT_RECUPERAR_GRUPO_MOTORISTAS = "BuscarPorCodigo";
const ENDPOINT_ADICIONAR_GRUPO_MOTORISTAS = "Adicionar";
const ENDPOINT_ATUALIZAR_GRUPO_MOTORISTAS = "Atualizar";
const ENDPOINT_EXCLUIR_GRUPO_MOTORISTAS = "Excluir";

const MSG_AVISO_TITULO_CAMPOS_OBRIGATORIOS = "Campos Obrigatórios";
const MSG_AVISO_TITULO_INCONSISTENCIA = "Inconsistência";
