//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicos.ServicoELT {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoELT.IELTAverbaService")]
    public interface IELTAverbaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IELTAverbaService/FileUpload", ReplyAction="http://tempuri.org/IELTAverbaService/FileUploadResponse")]
        Servicos.ServicoELT.RespostaProcessamento FileUpload(Servicos.ServicoELT.RemoteFileInfo request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IELTAverbaService/FileUpload", ReplyAction="http://tempuri.org/IELTAverbaService/FileUploadResponse")]
        System.Threading.Tasks.Task<Servicos.ServicoELT.RespostaProcessamento> FileUploadAsync(Servicos.ServicoELT.RemoteFileInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteFileInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteFileInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string CNPJ;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemoteFileInfo() {
        }
        
        public RemoteFileInfo(string CNPJ, string FileName, long Length, System.IO.Stream FileByteStream) {
            this.CNPJ = CNPJ;
            this.FileName = FileName;
            this.Length = Length;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RespostaProcessamento", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RespostaProcessamento {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CNPJ;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string CTE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Codigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.DateTime DataHora;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Protocolo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string Resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string fname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string status;
        
        public RespostaProcessamento() {
        }
        
        public RespostaProcessamento(string CNPJ, string CTE, string Codigo, System.DateTime DataHora, string Protocolo, string Resultado, string fname, string status) {
            this.CNPJ = CNPJ;
            this.CTE = CTE;
            this.Codigo = Codigo;
            this.DataHora = DataHora;
            this.Protocolo = Protocolo;
            this.Resultado = Resultado;
            this.fname = fname;
            this.status = status;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IELTAverbaServiceChannel : Servicos.ServicoELT.IELTAverbaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ELTAverbaServiceClient : System.ServiceModel.ClientBase<Servicos.ServicoELT.IELTAverbaService>, Servicos.ServicoELT.IELTAverbaService {
        
        public ELTAverbaServiceClient() {
        }
        
        public ELTAverbaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ELTAverbaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ELTAverbaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ELTAverbaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servicos.ServicoELT.RespostaProcessamento Servicos.ServicoELT.IELTAverbaService.FileUpload(Servicos.ServicoELT.RemoteFileInfo request) {
            return base.Channel.FileUpload(request);
        }
        
        public string FileUpload(ref string CNPJ, string FileName, long Length, System.IO.Stream FileByteStream, out string Codigo, out System.DateTime DataHora, out string Protocolo, out string Resultado, out string fname, out string status) {
            Servicos.ServicoELT.RemoteFileInfo inValue = new Servicos.ServicoELT.RemoteFileInfo();
            inValue.CNPJ = CNPJ;
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            Servicos.ServicoELT.RespostaProcessamento retVal = ((Servicos.ServicoELT.IELTAverbaService)(this)).FileUpload(inValue);
            CNPJ = retVal.CNPJ;
            Codigo = retVal.Codigo;
            DataHora = retVal.DataHora;
            Protocolo = retVal.Protocolo;
            Resultado = retVal.Resultado;
            fname = retVal.fname;
            status = retVal.status;
            return retVal.CTE;
        }
        
        public System.Threading.Tasks.Task<Servicos.ServicoELT.RespostaProcessamento> FileUploadAsync(Servicos.ServicoELT.RemoteFileInfo request) {
            return base.Channel.FileUploadAsync(request);
        }
    }
}
