//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicos.ServicoSAP_ST {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://jsl.com.br/Criar_Adiantamento_FI", ConfigurationName="ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUT")]
    public interface SI_Criar_Adiantamento_Sync_OUT {
        
        // CODEGEN: Generating message contract since the operation SI_Criar_Adiantamento_Sync_OUT is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUTResponse SI_Criar_Adiantamento_Sync_OUT(Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUTResponse> SI_Criar_Adiantamento_Sync_OUTAsync(Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUTRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jsl.com.br/Criar_Adiantamento_FI")]
    public partial class DT_Criar_Adiantamento_req : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_Criar_Adiantamento_reqItem[] t_HEADERField;
        
        private DT_Criar_Adiantamento_reqItem1[] t_ITEM_CARUANAField;
        
        private DT_Criar_Adiantamento_reqItem2[] t_ITEM_PROPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_Criar_Adiantamento_reqItem[] T_HEADER {
            get {
                return this.t_HEADERField;
            }
            set {
                this.t_HEADERField = value;
                this.RaisePropertyChanged("T_HEADER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_Criar_Adiantamento_reqItem1[] T_ITEM_CARUANA {
            get {
                return this.t_ITEM_CARUANAField;
            }
            set {
                this.t_ITEM_CARUANAField = value;
                this.RaisePropertyChanged("T_ITEM_CARUANA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_Criar_Adiantamento_reqItem2[] T_ITEM_PROP {
            get {
                return this.t_ITEM_PROPField;
            }
            set {
                this.t_ITEM_PROPField = value;
                this.RaisePropertyChanged("T_ITEM_PROP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jsl.com.br/Criar_Adiantamento_FI")]
    public partial class DT_Criar_Adiantamento_reqItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dOC_CONTField;
        
        private System.DateTime dAT_DOCField;
        
        private string tIPO_DOCField;
        
        private string eMPRESAField;
        
        private System.DateTime dATA_LANCField;
        
        private string mOEDAField;
        
        private string rEFERENCIAField;
        
        private string tEXTO_CABField;
        
        private string tEXTO_COMPField;
        
        private string nUM_FILIALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DOC_CONT {
            get {
                return this.dOC_CONTField;
            }
            set {
                this.dOC_CONTField = value;
                this.RaisePropertyChanged("DOC_CONT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime DAT_DOC {
            get {
                return this.dAT_DOCField;
            }
            set {
                this.dAT_DOCField = value;
                this.RaisePropertyChanged("DAT_DOC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TIPO_DOC {
            get {
                return this.tIPO_DOCField;
            }
            set {
                this.tIPO_DOCField = value;
                this.RaisePropertyChanged("TIPO_DOC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string EMPRESA {
            get {
                return this.eMPRESAField;
            }
            set {
                this.eMPRESAField = value;
                this.RaisePropertyChanged("EMPRESA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=4)]
        public System.DateTime DATA_LANC {
            get {
                return this.dATA_LANCField;
            }
            set {
                this.dATA_LANCField = value;
                this.RaisePropertyChanged("DATA_LANC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MOEDA {
            get {
                return this.mOEDAField;
            }
            set {
                this.mOEDAField = value;
                this.RaisePropertyChanged("MOEDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string REFERENCIA {
            get {
                return this.rEFERENCIAField;
            }
            set {
                this.rEFERENCIAField = value;
                this.RaisePropertyChanged("REFERENCIA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string TEXTO_CAB {
            get {
                return this.tEXTO_CABField;
            }
            set {
                this.tEXTO_CABField = value;
                this.RaisePropertyChanged("TEXTO_CAB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string TEXTO_COMP {
            get {
                return this.tEXTO_COMPField;
            }
            set {
                this.tEXTO_COMPField = value;
                this.RaisePropertyChanged("TEXTO_COMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string NUM_FILIAL {
            get {
                return this.nUM_FILIALField;
            }
            set {
                this.nUM_FILIALField = value;
                this.RaisePropertyChanged("NUM_FILIAL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jsl.com.br/Criar_Adiantamento_FI")]
    public partial class DT_Criar_Adiantamento_resp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_Criar_Adiantamento_respItem[] t_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_Criar_Adiantamento_respItem[] T_RETURN {
            get {
                return this.t_RETURNField;
            }
            set {
                this.t_RETURNField = value;
                this.RaisePropertyChanged("T_RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jsl.com.br/Criar_Adiantamento_FI")]
    public partial class DT_Criar_Adiantamento_respItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tIPOField;
        
        private string eMPRESAField;
        
        private string dOC_CONTField;
        
        private string aREA_FUNCField;
        
        private string nUM_MSGField;
        
        private string tEXTO_MSGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TIPO {
            get {
                return this.tIPOField;
            }
            set {
                this.tIPOField = value;
                this.RaisePropertyChanged("TIPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EMPRESA {
            get {
                return this.eMPRESAField;
            }
            set {
                this.eMPRESAField = value;
                this.RaisePropertyChanged("EMPRESA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DOC_CONT {
            get {
                return this.dOC_CONTField;
            }
            set {
                this.dOC_CONTField = value;
                this.RaisePropertyChanged("DOC_CONT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string AREA_FUNC {
            get {
                return this.aREA_FUNCField;
            }
            set {
                this.aREA_FUNCField = value;
                this.RaisePropertyChanged("AREA_FUNC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string NUM_MSG {
            get {
                return this.nUM_MSGField;
            }
            set {
                this.nUM_MSGField = value;
                this.RaisePropertyChanged("NUM_MSG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string TEXTO_MSG {
            get {
                return this.tEXTO_MSGField;
            }
            set {
                this.tEXTO_MSGField = value;
                this.RaisePropertyChanged("TEXTO_MSG");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jsl.com.br/Criar_Adiantamento_FI")]
    public partial class DT_Criar_Adiantamento_reqItem1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cHAVE_LANCField;
        
        private string cOD_CARTAOField;
        
        private decimal mONTANTEField;
        
        private string lOCAL_NEGField;
        
        private string cOND_PAGField;
        
        private System.DateTime dATA_BASEField;
        
        private string bLOQ_PAGField;
        
        private string fORMA_PAGField;
        
        private string rEF_PAGField;
        
        private string aTRIBUICAOField;
        
        private string bANCO_EMPRESAField;
        
        private string iD_CONTAField;
        
        private string tEXTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CHAVE_LANC {
            get {
                return this.cHAVE_LANCField;
            }
            set {
                this.cHAVE_LANCField = value;
                this.RaisePropertyChanged("CHAVE_LANC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string COD_CARTAO {
            get {
                return this.cOD_CARTAOField;
            }
            set {
                this.cOD_CARTAOField = value;
                this.RaisePropertyChanged("COD_CARTAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal MONTANTE {
            get {
                return this.mONTANTEField;
            }
            set {
                this.mONTANTEField = value;
                this.RaisePropertyChanged("MONTANTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LOCAL_NEG {
            get {
                return this.lOCAL_NEGField;
            }
            set {
                this.lOCAL_NEGField = value;
                this.RaisePropertyChanged("LOCAL_NEG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string COND_PAG {
            get {
                return this.cOND_PAGField;
            }
            set {
                this.cOND_PAGField = value;
                this.RaisePropertyChanged("COND_PAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=5)]
        public System.DateTime DATA_BASE {
            get {
                return this.dATA_BASEField;
            }
            set {
                this.dATA_BASEField = value;
                this.RaisePropertyChanged("DATA_BASE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string BLOQ_PAG {
            get {
                return this.bLOQ_PAGField;
            }
            set {
                this.bLOQ_PAGField = value;
                this.RaisePropertyChanged("BLOQ_PAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string FORMA_PAG {
            get {
                return this.fORMA_PAGField;
            }
            set {
                this.fORMA_PAGField = value;
                this.RaisePropertyChanged("FORMA_PAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string REF_PAG {
            get {
                return this.rEF_PAGField;
            }
            set {
                this.rEF_PAGField = value;
                this.RaisePropertyChanged("REF_PAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ATRIBUICAO {
            get {
                return this.aTRIBUICAOField;
            }
            set {
                this.aTRIBUICAOField = value;
                this.RaisePropertyChanged("ATRIBUICAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string BANCO_EMPRESA {
            get {
                return this.bANCO_EMPRESAField;
            }
            set {
                this.bANCO_EMPRESAField = value;
                this.RaisePropertyChanged("BANCO_EMPRESA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ID_CONTA {
            get {
                return this.iD_CONTAField;
            }
            set {
                this.iD_CONTAField = value;
                this.RaisePropertyChanged("ID_CONTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string TEXTO {
            get {
                return this.tEXTOField;
            }
            set {
                this.tEXTOField = value;
                this.RaisePropertyChanged("TEXTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jsl.com.br/Criar_Adiantamento_FI")]
    public partial class DT_Criar_Adiantamento_reqItem2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cHAVE_LANCField;
        
        private string cOD_PROPField;
        
        private decimal mONTANTEField;
        
        private string lOCAL_NEGOCIOField;
        
        private string cOND_PAGField;
        
        private System.DateTime dATA_BASEField;
        
        private string bLOQ_PAGField;
        
        private string fORMA_PAGField;
        
        private string rEF_PAGField;
        
        private string aTRIBUICAOField;
        
        private string bANCO_EMPRESAField;
        
        private string iD_CONTAField;
        
        private string tEXTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CHAVE_LANC {
            get {
                return this.cHAVE_LANCField;
            }
            set {
                this.cHAVE_LANCField = value;
                this.RaisePropertyChanged("CHAVE_LANC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string COD_PROP {
            get {
                return this.cOD_PROPField;
            }
            set {
                this.cOD_PROPField = value;
                this.RaisePropertyChanged("COD_PROP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal MONTANTE {
            get {
                return this.mONTANTEField;
            }
            set {
                this.mONTANTEField = value;
                this.RaisePropertyChanged("MONTANTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LOCAL_NEGOCIO {
            get {
                return this.lOCAL_NEGOCIOField;
            }
            set {
                this.lOCAL_NEGOCIOField = value;
                this.RaisePropertyChanged("LOCAL_NEGOCIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string COND_PAG {
            get {
                return this.cOND_PAGField;
            }
            set {
                this.cOND_PAGField = value;
                this.RaisePropertyChanged("COND_PAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=5)]
        public System.DateTime DATA_BASE {
            get {
                return this.dATA_BASEField;
            }
            set {
                this.dATA_BASEField = value;
                this.RaisePropertyChanged("DATA_BASE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string BLOQ_PAG {
            get {
                return this.bLOQ_PAGField;
            }
            set {
                this.bLOQ_PAGField = value;
                this.RaisePropertyChanged("BLOQ_PAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string FORMA_PAG {
            get {
                return this.fORMA_PAGField;
            }
            set {
                this.fORMA_PAGField = value;
                this.RaisePropertyChanged("FORMA_PAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string REF_PAG {
            get {
                return this.rEF_PAGField;
            }
            set {
                this.rEF_PAGField = value;
                this.RaisePropertyChanged("REF_PAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ATRIBUICAO {
            get {
                return this.aTRIBUICAOField;
            }
            set {
                this.aTRIBUICAOField = value;
                this.RaisePropertyChanged("ATRIBUICAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string BANCO_EMPRESA {
            get {
                return this.bANCO_EMPRESAField;
            }
            set {
                this.bANCO_EMPRESAField = value;
                this.RaisePropertyChanged("BANCO_EMPRESA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ID_CONTA {
            get {
                return this.iD_CONTAField;
            }
            set {
                this.iD_CONTAField = value;
                this.RaisePropertyChanged("ID_CONTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string TEXTO {
            get {
                return this.tEXTOField;
            }
            set {
                this.tEXTOField = value;
                this.RaisePropertyChanged("TEXTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_Criar_Adiantamento_Sync_OUTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jsl.com.br/Criar_Adiantamento_FI", Order=0)]
        public Servicos.ServicoSAP_ST.DT_Criar_Adiantamento_req MT_Criar_Adiantamento_req;
        
        public SI_Criar_Adiantamento_Sync_OUTRequest() {
        }
        
        public SI_Criar_Adiantamento_Sync_OUTRequest(Servicos.ServicoSAP_ST.DT_Criar_Adiantamento_req MT_Criar_Adiantamento_req) {
            this.MT_Criar_Adiantamento_req = MT_Criar_Adiantamento_req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_Criar_Adiantamento_Sync_OUTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jsl.com.br/Criar_Adiantamento_FI", Order=0)]
        public Servicos.ServicoSAP_ST.DT_Criar_Adiantamento_resp MT_Criar_Adiantamento_resp;
        
        public SI_Criar_Adiantamento_Sync_OUTResponse() {
        }
        
        public SI_Criar_Adiantamento_Sync_OUTResponse(Servicos.ServicoSAP_ST.DT_Criar_Adiantamento_resp MT_Criar_Adiantamento_resp) {
            this.MT_Criar_Adiantamento_resp = MT_Criar_Adiantamento_resp;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_Criar_Adiantamento_Sync_OUTChannel : Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_Criar_Adiantamento_Sync_OUTClient : System.ServiceModel.ClientBase<Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUT>, Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUT {
        
        public SI_Criar_Adiantamento_Sync_OUTClient() {
        }
        
        public SI_Criar_Adiantamento_Sync_OUTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_Criar_Adiantamento_Sync_OUTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_Criar_Adiantamento_Sync_OUTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_Criar_Adiantamento_Sync_OUTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUTResponse Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUT.SI_Criar_Adiantamento_Sync_OUT(Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUTRequest request) {
            return base.Channel.SI_Criar_Adiantamento_Sync_OUT(request);
        }
        
        public Servicos.ServicoSAP_ST.DT_Criar_Adiantamento_resp SI_Criar_Adiantamento_Sync_OUT(Servicos.ServicoSAP_ST.DT_Criar_Adiantamento_req MT_Criar_Adiantamento_req) {
            Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUTRequest inValue = new Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUTRequest();
            inValue.MT_Criar_Adiantamento_req = MT_Criar_Adiantamento_req;
            Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUTResponse retVal = ((Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUT)(this)).SI_Criar_Adiantamento_Sync_OUT(inValue);
            return retVal.MT_Criar_Adiantamento_resp;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUTResponse> Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUT.SI_Criar_Adiantamento_Sync_OUTAsync(Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUTRequest request) {
            return base.Channel.SI_Criar_Adiantamento_Sync_OUTAsync(request);
        }
        
        public System.Threading.Tasks.Task<Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUTResponse> SI_Criar_Adiantamento_Sync_OUTAsync(Servicos.ServicoSAP_ST.DT_Criar_Adiantamento_req MT_Criar_Adiantamento_req) {
            Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUTRequest inValue = new Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUTRequest();
            inValue.MT_Criar_Adiantamento_req = MT_Criar_Adiantamento_req;
            return ((Servicos.ServicoSAP_ST.SI_Criar_Adiantamento_Sync_OUT)(this)).SI_Criar_Adiantamento_Sync_OUTAsync(inValue);
        }
    }
}
