using System;
using System.Collections.Generic;

namespace Dominio.ObjetosDeValor.Embarcador.NotaFiscal
{
    public class NotaFiscalProduto
    {
        public int Codigo { get; set; }
        public Dominio.ObjetosDeValor.Embarcador.Enumeradores.CSTICMS? CSTICMS { get; set; }
        public decimal Quantidade { get; set; }
        public decimal ValorUnitario { get; set; }
        public decimal ValorTotal { get; set; }
        public decimal ValorFrete { get; set; }
        public decimal ValorSeguro { get; set; }
        public decimal ValorOutrasDespesas { get; set; }
        public decimal ValorDesconto { get; set; }
        public string NumeroOrdemCompra { get; set; }
        public string NumeroItemOrdemCompra { get; set; }

        public decimal AliquotaRemICMSRet { get; set; }
        public decimal ValorICMSMonoRet { get; set; }

        public decimal BCICMS { get; set; }
        public decimal ReducaoBCICMS { get; set; }
        public decimal AliquotaICMS { get; set; }
        public decimal ValorICMS { get; set; }
        public decimal BCICMSDestino { get; set; }
        public decimal AliquotaFCP { get; set; }
        public decimal AliquotaICMSDestino { get; set; }
        public decimal AliquotaICMSInterno { get; set; }
        public decimal PercentualPartilha { get; set; }
        public decimal ValorFCP { get; set; }
        public decimal ValorICMSDestino { get; set; }
        public decimal ValorICMSRemetente { get; set; }
        public decimal BCICMSST { get; set; }
        public decimal MVAICMSST { get; set; }
        public decimal ReducaoBCICMSST { get; set; }
        public decimal AliquotaICMSST { get; set; }
        public decimal AliquotaICMSSTInterestadual { get; set; }
        public decimal ValorICMSST { get; set; }
        public Dominio.ObjetosDeValor.Embarcador.Enumeradores.CSTPISCOFINS? CSTPIS { get; set; }
        public decimal BCPIS { get; set; }
        public decimal ReducaoBCPIS { get; set; }
        public decimal AliquotaPIS { get; set; }
        public decimal ValorPIS { get; set; }
        public Dominio.ObjetosDeValor.Embarcador.Enumeradores.CSTPISCOFINS? CSTCOFINS { get; set; }
        public decimal BCCOFINS { get; set; }
        public decimal ReducaoBCCOFINS { get; set; }
        public decimal AliquotaCOFINS { get; set; }
        public decimal ValorCOFINS { get; set; }
        public Dominio.ObjetosDeValor.Embarcador.Enumeradores.CSTIPI? CSTIPI { get; set; }
        public decimal BCIPI { get; set; }
        public decimal ReducaoBCIPI { get; set; }
        public decimal AliquotaIPI { get; set; }
        public decimal ValorIPI { get; set; }
        public decimal BaseISS { get; set; }
        public decimal AliquotaISS { get; set; }
        public decimal ValorISS { get; set; }
        public decimal BCDeducao { get; set; }
        public decimal OutrasRetencoes { get; set; }
        public decimal DescontoIncondicional { get; set; }
        public decimal DescontoCondicional { get; set; }
        public decimal RetencaoISS { get; set; }
        public Dominio.Enumeradores.ExigibilidadeISS ExigibilidadeISS { get; set; }
        public bool IncentivoFiscal { get; set; }
        public string ProcessoJudicial { get; set; }
        public decimal BaseII { get; set; }
        public decimal ValorDespesaII { get; set; }
        public decimal ValorII { get; set; }
        public decimal ValorIOFII { get; set; }
        public string NumeroDocImportacao { get; set; }
        public DateTime? DataRegistroImportacao { get; set; }
        public string LocalDesembaraco { get; set; }
        public string UFDesembaraco { get; set; }
        public DateTime? DataDesembaraco { get; set; }
        public string CNPJAdquirente { get; set; }
        public Dominio.Enumeradores.ViaTransporteInternacional ViaTransporteII { get; set; }
        public decimal ValorFreteMarinho { get; set; }
        public Dominio.Enumeradores.IntermediacaoImportacao IntermediacaoII { get; set; }
        public decimal ValorICMSDesonerado { get; set; }
        public Dominio.Enumeradores.MotivoDesoneracaoICMS MotivoDesoneracao { get; set; }
        public decimal ValorICMSOperacao { get; set; }
        public decimal AliquotaICMSOperacao { get; set; }
        public decimal ValorICMSDiferido { get; set; }
        public Produto Produto { get; set; }
        public int CFOP { get; set; }
        public Servico Servico { get; set; }
        public string CodigoItem { get; set; }
        public string DescricaoItem { get; set; }
        public decimal BaseFCPICMS { get; set; }
        public decimal PercentualFCPICMS { get; set; }
        public decimal ValorFCPICMS { get; set; }
        public decimal BaseFCPICMSST { get; set; }
        public decimal PercentualFCPICMSST { get; set; }
        public decimal ValorFCPICMSST { get; set; }
        public decimal AliquotaFCPICMSST { get; set; }
        public decimal BaseFCPDestino { get; set; }
        public decimal PercentualIPIDevolvido { get; set; }
        public decimal ValorIPIDevolvido { get; set; }
        public string InformacoesAdicionais { get; set; }
        public string CodigoANP { get; set; }
        public Dominio.ObjetosDeValor.Embarcador.Enumeradores.IndicadorEscalaRelevante IndicadorEscalaRelevante { get; set; }
        public string CNPJFabricante { get; set; }
        public string CodigoBeneficioFiscal { get; set; }
        public decimal PercentualGLP { get; set; }
        public decimal PercentualGNN { get; set; }
        public decimal PercentualGNI { get; set; }
        public decimal PercentualOrigemComb { get; set; }
        public decimal PercentualMisturaBiodiesel { get; set; }
        public decimal ValorPartidaANP { get; set; }
        public decimal QuantidadeTributavel { get; set; }
        public decimal ValorUnitarioTributavel { get; set; }
        public ObjetosDeValor.Embarcador.Enumeradores.UnidadeDeMedida? UnidadeDeMedidaTributavel { get; set; }
        public string CodigoEANTributavel { get; set; }
        public decimal BCICMSSTRetido { get; set; }
        public decimal AliquotaICMSSTRetido { get; set; }
        public decimal ValorICMSSTSubstituto { get; set; }
        public decimal ValorICMSSTRetido { get; set; }
        public decimal BCICMSEfetivo { get; set; }
        public decimal AliquotaICMSEfetivo { get; set; }
        public decimal ReducaoBCICMSEfetivo { get; set; }
        public decimal ValorICMSEfetivo { get; set; }
        public string NumeroDrawback { get; set; }
        public string NumeroRegistroExportacao { get; set; }
        public string ChaveAcessoExportacao { get; set; }
        public List<NotaFiscalProdutoLote> LotesItem { get; set; }
        public ObjetosDeValor.Embarcador.Enumeradores.OrigemMercadoria? OrigemMercadoria { get; set; }
        public string CodigoNFCI { get; set; }
        public int LocalArmazenamento { get; set; }
        public decimal BCICMSSTDestino { get; set; }
        public decimal ValorICMSSTDestino { get; set; }
        public int Sequencial { get; set; }
    }
}