//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml;

namespace Servicos.ServicoNaturaNovo.ProcessaCTeNFSe {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.natura.net/CteNfse", ConfigurationName="ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_Sync")]
    public interface SI_ProcessaCteNfse_Sync {
        
        // CODEGEN: Generating message contract since the operation SI_ProcessaCteNfse_Sync is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_SyncResponse SI_ProcessaCteNfse_Sync(Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_SyncRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_SyncResponse> SI_ProcessaCteNfse_SyncAsync(Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_SyncRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.natura.net/CteNfse")]
    public partial class DT_EletronicDocumentRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_EletronicDocumentRequestDados dadosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_EletronicDocumentRequestDados dados {
            get {
                return this.dadosField;
            }
            set {
                this.dadosField = value;
                this.RaisePropertyChanged("dados");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.natura.net/CteNfse")]
    public partial class DT_EletronicDocumentRequestDados : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroTransporteField;
        
        private string codTranspMatrizField;
        
        private string codTranspEmitField;
        
        private string cnpjEmitenteField;
        
        private string cnpjTomadorField;
        
        private DT_EletronicDocumentRequestDadosDocumentoFiscal[] documentoFiscalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numeroTransporte {
            get {
                return this.numeroTransporteField;
            }
            set {
                this.numeroTransporteField = value;
                this.RaisePropertyChanged("numeroTransporte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codTranspMatriz {
            get {
                return this.codTranspMatrizField;
            }
            set {
                this.codTranspMatrizField = value;
                this.RaisePropertyChanged("codTranspMatriz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codTranspEmit {
            get {
                return this.codTranspEmitField;
            }
            set {
                this.codTranspEmitField = value;
                this.RaisePropertyChanged("codTranspEmit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string cnpjEmitente {
            get {
                return this.cnpjEmitenteField;
            }
            set {
                this.cnpjEmitenteField = value;
                this.RaisePropertyChanged("cnpjEmitente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cnpjTomador {
            get {
                return this.cnpjTomadorField;
            }
            set {
                this.cnpjTomadorField = value;
                this.RaisePropertyChanged("cnpjTomador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("documentoFiscal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public DT_EletronicDocumentRequestDadosDocumentoFiscal[] documentoFiscal {
            get {
                return this.documentoFiscalField;
            }
            set {
                this.documentoFiscalField = value;
                this.RaisePropertyChanged("documentoFiscal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.natura.net/CteNfse")]
    public partial class DT_EletronicDocumentRequestDadosDocumentoFiscal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroField;
        
        private string serieField;
        
        private string modeloField;
        
        private System.DateTime dataEmissaoField;
        
        private string origemField;
        
        private string destinoField;
        
        private string tipoDocField;
        
        private string valorFreteField;
        
        private string valorImpostosField;
        
        private DT_EletronicDocumentRequestDadosDocumentoFiscalNfse nfseField;
        
        private DT_EletronicDocumentRequestDadosDocumentoFiscalCte cteField;
        
        private DT_EletronicDocumentRequestDadosDocumentoFiscalNotasTransportadas[] notasTransportadasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
                this.RaisePropertyChanged("serie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=3)]
        public System.DateTime dataEmissao {
            get {
                return this.dataEmissaoField;
            }
            set {
                this.dataEmissaoField = value;
                this.RaisePropertyChanged("dataEmissao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string origem {
            get {
                return this.origemField;
            }
            set {
                this.origemField = value;
                this.RaisePropertyChanged("origem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("destino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string tipoDoc {
            get {
                return this.tipoDocField;
            }
            set {
                this.tipoDocField = value;
                this.RaisePropertyChanged("tipoDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string valorFrete {
            get {
                return this.valorFreteField;
            }
            set {
                this.valorFreteField = value;
                this.RaisePropertyChanged("valorFrete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string valorImpostos {
            get {
                return this.valorImpostosField;
            }
            set {
                this.valorImpostosField = value;
                this.RaisePropertyChanged("valorImpostos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public DT_EletronicDocumentRequestDadosDocumentoFiscalNfse nfse {
            get {
                return this.nfseField;
            }
            set {
                this.nfseField = value;
                this.RaisePropertyChanged("nfse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public DT_EletronicDocumentRequestDadosDocumentoFiscalCte cte {
            get {
                return this.cteField;
            }
            set {
                this.cteField = value;
                this.RaisePropertyChanged("cte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("notasTransportadas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public DT_EletronicDocumentRequestDadosDocumentoFiscalNotasTransportadas[] notasTransportadas {
            get {
                return this.notasTransportadasField;
            }
            set {
                this.notasTransportadasField = value;
                this.RaisePropertyChanged("notasTransportadas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.natura.net/CteNfse")]
    public partial class DT_EletronicDocumentRequestDadosDocumentoFiscalNfse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string retencaoField;
        
        private string aliqISSField;
        
        private string baseISSField;
        
        private string valorISSField;
        
        private string aliqPISField;
        
        private string basePISField;
        
        private string valorPISField;
        
        private string aliqCOFINSField;
        
        private string baseCOFINSField;
        
        private string valorCOFINSField;
        
        private string aliqCSLLField;
        
        private string baseCSLLField;
        
        private string valorCSLLField;
        
        private string aliqIRField;
        
        private string baseIRField;
        
        private string valorIRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string retencao {
            get {
                return this.retencaoField;
            }
            set {
                this.retencaoField = value;
                this.RaisePropertyChanged("retencao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string aliqISS {
            get {
                return this.aliqISSField;
            }
            set {
                this.aliqISSField = value;
                this.RaisePropertyChanged("aliqISS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string baseISS {
            get {
                return this.baseISSField;
            }
            set {
                this.baseISSField = value;
                this.RaisePropertyChanged("baseISS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string valorISS {
            get {
                return this.valorISSField;
            }
            set {
                this.valorISSField = value;
                this.RaisePropertyChanged("valorISS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string aliqPIS {
            get {
                return this.aliqPISField;
            }
            set {
                this.aliqPISField = value;
                this.RaisePropertyChanged("aliqPIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string basePIS {
            get {
                return this.basePISField;
            }
            set {
                this.basePISField = value;
                this.RaisePropertyChanged("basePIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string valorPIS {
            get {
                return this.valorPISField;
            }
            set {
                this.valorPISField = value;
                this.RaisePropertyChanged("valorPIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string aliqCOFINS {
            get {
                return this.aliqCOFINSField;
            }
            set {
                this.aliqCOFINSField = value;
                this.RaisePropertyChanged("aliqCOFINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string baseCOFINS {
            get {
                return this.baseCOFINSField;
            }
            set {
                this.baseCOFINSField = value;
                this.RaisePropertyChanged("baseCOFINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string valorCOFINS {
            get {
                return this.valorCOFINSField;
            }
            set {
                this.valorCOFINSField = value;
                this.RaisePropertyChanged("valorCOFINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string aliqCSLL {
            get {
                return this.aliqCSLLField;
            }
            set {
                this.aliqCSLLField = value;
                this.RaisePropertyChanged("aliqCSLL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string baseCSLL {
            get {
                return this.baseCSLLField;
            }
            set {
                this.baseCSLLField = value;
                this.RaisePropertyChanged("baseCSLL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string valorCSLL {
            get {
                return this.valorCSLLField;
            }
            set {
                this.valorCSLLField = value;
                this.RaisePropertyChanged("valorCSLL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string aliqIR {
            get {
                return this.aliqIRField;
            }
            set {
                this.aliqIRField = value;
                this.RaisePropertyChanged("aliqIR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string baseIR {
            get {
                return this.baseIRField;
            }
            set {
                this.baseIRField = value;
                this.RaisePropertyChanged("baseIR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string valorIR {
            get {
                return this.valorIRField;
            }
            set {
                this.valorIRField = value;
                this.RaisePropertyChanged("valorIR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.natura.net/CteNfse")]
    public partial class DT_EletronicDocumentRequestDadosDocumentoFiscalCte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string chaveCTeField;
        
        private XmlCDataSection xmlCTeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string chaveCTe {
            get {
                return this.chaveCTeField;
            }
            set {
                this.chaveCTeField = value;
                this.RaisePropertyChanged("chaveCTe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public XmlCDataSection xmlCTe {
            get {
                return this.xmlCTeField;
            }
            set {
                this.xmlCTeField = value;
                this.RaisePropertyChanged("xmlCTe");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.natura.net/CteNfse")]
    public partial class DT_EletronicDocumentRequestDadosDocumentoFiscalNotasTransportadas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string chaveNFeField;
        
        private System.DateTime dataEmissaoField;
        
        private bool dataEmissaoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string chaveNFe {
            get {
                return this.chaveNFeField;
            }
            set {
                this.chaveNFeField = value;
                this.RaisePropertyChanged("chaveNFe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime dataEmissao {
            get {
                return this.dataEmissaoField;
            }
            set {
                this.dataEmissaoField = value;
                this.RaisePropertyChanged("dataEmissao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataEmissaoSpecified {
            get {
                return this.dataEmissaoFieldSpecified;
            }
            set {
                this.dataEmissaoFieldSpecified = value;
                this.RaisePropertyChanged("dataEmissaoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.natura.net/CteNfse")]
    public partial class DT_EletronicDocumentResponseDados : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string idField;
        
        private string numberField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ProcessaCteNfse_SyncRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.natura.net/CteNfse", Order=0)]
        public Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.DT_EletronicDocumentRequest MT_EletronicDocumentRequest;
        
        public SI_ProcessaCteNfse_SyncRequest() {
        }
        
        public SI_ProcessaCteNfse_SyncRequest(Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.DT_EletronicDocumentRequest MT_EletronicDocumentRequest) {
            this.MT_EletronicDocumentRequest = MT_EletronicDocumentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ProcessaCteNfse_SyncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.natura.net/CteNfse", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dados", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.DT_EletronicDocumentResponseDados[] MT_EletronicDocumentResponse;
        
        public SI_ProcessaCteNfse_SyncResponse() {
        }
        
        public SI_ProcessaCteNfse_SyncResponse(Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.DT_EletronicDocumentResponseDados[] MT_EletronicDocumentResponse) {
            this.MT_EletronicDocumentResponse = MT_EletronicDocumentResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ProcessaCteNfse_SyncChannel : Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_Sync, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ProcessaCteNfse_SyncClient : System.ServiceModel.ClientBase<Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_Sync>, Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_Sync {
        
        public SI_ProcessaCteNfse_SyncClient() {
        }
        
        public SI_ProcessaCteNfse_SyncClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ProcessaCteNfse_SyncClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ProcessaCteNfse_SyncClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ProcessaCteNfse_SyncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_SyncResponse Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_Sync.SI_ProcessaCteNfse_Sync(Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_SyncRequest request) {
            return base.Channel.SI_ProcessaCteNfse_Sync(request);
        }
        
        public Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.DT_EletronicDocumentResponseDados[] SI_ProcessaCteNfse_Sync(Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.DT_EletronicDocumentRequest MT_EletronicDocumentRequest) {
            Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_SyncRequest inValue = new Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_SyncRequest();
            inValue.MT_EletronicDocumentRequest = MT_EletronicDocumentRequest;
            Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_SyncResponse retVal = ((Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_Sync)(this)).SI_ProcessaCteNfse_Sync(inValue);
            return retVal.MT_EletronicDocumentResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_SyncResponse> Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_Sync.SI_ProcessaCteNfse_SyncAsync(Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_SyncRequest request) {
            return base.Channel.SI_ProcessaCteNfse_SyncAsync(request);
        }
        
        public System.Threading.Tasks.Task<Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_SyncResponse> SI_ProcessaCteNfse_SyncAsync(Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.DT_EletronicDocumentRequest MT_EletronicDocumentRequest) {
            Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_SyncRequest inValue = new Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_SyncRequest();
            inValue.MT_EletronicDocumentRequest = MT_EletronicDocumentRequest;
            return ((Servicos.ServicoNaturaNovo.ProcessaCTeNFSe.SI_ProcessaCteNfse_Sync)(this)).SI_ProcessaCteNfse_SyncAsync(inValue);
        }
    }
}
