//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Resources.Integracoes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControleIntegracao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControleIntegracao() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Resources.Integracoes.ControleIntegracao", typeof(ControleIntegracao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação.
        /// </summary>
        public static string Acao {
            get {
                return ResourceManager.GetString("Acao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditado.
        /// </summary>
        public static string Auditado {
            get {
                return ResourceManager.GetString("Auditado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditoria.
        /// </summary>
        public static string Auditoria {
            get {
                return ResourceManager.GetString("Auditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditoria de Retornos {0}.
        /// </summary>
        public static string AuditoriaDeRetornos {
            get {
                return ResourceManager.GetString("AuditoriaDeRetornos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditoria {0}.
        /// </summary>
        public static string AuditoriaZero {
            get {
                return ResourceManager.GetString("AuditoriaZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga.
        /// </summary>
        public static string Carga {
            get {
                return ResourceManager.GetString("Carga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de Integração.
        /// </summary>
        public static string CodigoDeIntegracao {
            get {
                return ResourceManager.GetString("CodigoDeIntegracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Início.
        /// </summary>
        public static string DataInicio {
            get {
                return ResourceManager.GetString("DataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Limite.
        /// </summary>
        public static string DataLimite {
            get {
                return ResourceManager.GetString("DataLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De.
        /// </summary>
        public static string De {
            get {
                return ResourceManager.GetString("De", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Descricao {
            get {
                return ResourceManager.GetString("Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controle de Integração.
        /// </summary>
        public static string DescricaoControleDeIntegracao {
            get {
                return ResourceManager.GetString("DescricaoControleDeIntegracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes.
        /// </summary>
        public static string Detalhes {
            get {
                return ResourceManager.GetString("Detalhes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes Auditoria.
        /// </summary>
        public static string DetalhesAuditoria {
            get {
                return ResourceManager.GetString("DetalhesAuditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponibilidade.
        /// </summary>
        public static string Disponibilidade {
            get {
                return ResourceManager.GetString("Disponibilidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponível.
        /// </summary>
        public static string Disponivel {
            get {
                return ResourceManager.GetString("Disponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download XMLs de Teste.
        /// </summary>
        public static string DownloadXmlsDeTeste {
            get {
                return ResourceManager.GetString("DownloadXmlsDeTeste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executar Teste.
        /// </summary>
        public static string ExecutarTeste {
            get {
                return ResourceManager.GetString("ExecutarTeste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros de Pesquisa.
        /// </summary>
        public static string FiltrosDePesquisa {
            get {
                return ResourceManager.GetString("FiltrosDePesquisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indisponível.
        /// </summary>
        public static string Indisponivel {
            get {
                return ResourceManager.GetString("Indisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integradora.
        /// </summary>
        public static string Integradora {
            get {
                return ResourceManager.GetString("Integradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método.
        /// </summary>
        public static string Metodo {
            get {
                return ResourceManager.GetString("Metodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número da Carga.
        /// </summary>
        public static string NumeroDaCarga {
            get {
                return ResourceManager.GetString("NumeroDaCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número do CT-e.
        /// </summary>
        public static string NumeroDoCtE {
            get {
                return ResourceManager.GetString("NumeroDoCtE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objeto.
        /// </summary>
        public static string Objeto {
            get {
                return ResourceManager.GetString("Objeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao realizar o download dos XMLs de teste de disponibilidade..
        /// </summary>
        public static string OcorreuUmaFalhaAoRealizarODownloadDosXmlsDeTesteDeDisponibilidade {
            get {
                return ResourceManager.GetString("OcorreuUmaFalhaAoRealizarODownloadDosXmlsDeTesteDeDisponibilidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao testar a disponibilidade..
        /// </summary>
        public static string OcorreuUmaFalhaAoTestarADisponibilidade {
            get {
                return ResourceManager.GetString("OcorreuUmaFalhaAoTestarADisponibilidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para.
        /// </summary>
        public static string Para {
            get {
                return ResourceManager.GetString("Para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string Pesquisar {
            get {
                return ResourceManager.GetString("Pesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar Integrações.
        /// </summary>
        public static string PesquisarIntegracoes {
            get {
                return ResourceManager.GetString("PesquisarIntegracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriedade.
        /// </summary>
        public static string Propriedade {
            get {
                return ResourceManager.GetString("Propriedade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retorno.
        /// </summary>
        public static string Retorno {
            get {
                return ResourceManager.GetString("Retorno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        public static string Sistema {
            get {
                return ResourceManager.GetString("Sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS Cargas.
        /// </summary>
        public static string WsCargas {
            get {
                return ResourceManager.GetString("WsCargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS CT-e.
        /// </summary>
        public static string WsCtE {
            get {
                return ResourceManager.GetString("WsCtE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS Empresa.
        /// </summary>
        public static string WsEmpresa {
            get {
                return ResourceManager.GetString("WsEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS Filial.
        /// </summary>
        public static string WsFilial {
            get {
                return ResourceManager.GetString("WsFilial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS Impressão.
        /// </summary>
        public static string WsImpressao {
            get {
                return ResourceManager.GetString("WsImpressao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS Janela de Carregamento.
        /// </summary>
        public static string WsJanelaDeCarregamento {
            get {
                return ResourceManager.GetString("WsJanelaDeCarregamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS MDF-e.
        /// </summary>
        public static string WsMdfE {
            get {
                return ResourceManager.GetString("WsMdfE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS NFS.
        /// </summary>
        public static string WsNfs {
            get {
                return ResourceManager.GetString("WsNfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS Ocorrências.
        /// </summary>
        public static string WsOcorrencias {
            get {
                return ResourceManager.GetString("WsOcorrencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS Pessoas.
        /// </summary>
        public static string WsPessoas {
            get {
                return ResourceManager.GetString("WsPessoas", resourceCulture);
            }
        }
    }
}
