//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Resources.TorreControle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FinalizacaoEmLote {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FinalizacaoEmLote() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Resources.TorreControle.FinalizacaoEmLote", typeof(FinalizacaoEmLote).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga.
        /// </summary>
        public static string Carga {
            get {
                return ResourceManager.GetString("Carga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargas disponíveis para finalização das coletas/entregas.
        /// </summary>
        public static string CargasDisponiveisFinalizacao {
            get {
                return ResourceManager.GetString("CargasDisponiveisFinalizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Carga Embarcador.
        /// </summary>
        public static string CodigoCargaEmbarcador {
            get {
                return ResourceManager.GetString("CodigoCargaEmbarcador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coletas/Entregas finalizadas.
        /// </summary>
        public static string ColetasEntregasFinalizadas {
            get {
                return ResourceManager.GetString("ColetasEntregasFinalizadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você realmente deseja confirmar e finalizar as coletas/entregas de todas as cargas selecionadas? Essa ação é irreversível..
        /// </summary>
        public static string ConfirmarFinalizarColetasEntregasSelecionadas {
            get {
                return ResourceManager.GetString("ConfirmarFinalizarColetasEntregasSelecionadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar múltiplas Coletas/Entregas.
        /// </summary>
        public static string ConfirmarMultiplasColetas {
            get {
                return ResourceManager.GetString("ConfirmarMultiplasColetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar múltiplas Coletas/Entregas.
        /// </summary>
        public static string ConfirmarMultiplasColetasEntregas {
            get {
                return ResourceManager.GetString("ConfirmarMultiplasColetasEntregas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data criação carga.
        /// </summary>
        public static string DataCriacaoCarga {
            get {
                return ResourceManager.GetString("DataCriacaoCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data emissão.
        /// </summary>
        public static string DataEmissao {
            get {
                return ResourceManager.GetString("DataEmissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data criação carga final.
        /// </summary>
        public static string DataFinalCriacaoCarga {
            get {
                return ResourceManager.GetString("DataFinalCriacaoCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Emissão final.
        /// </summary>
        public static string DataFinalEmissao {
            get {
                return ResourceManager.GetString("DataFinalEmissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data final processamento.
        /// </summary>
        public static string DataFinalProcessamento {
            get {
                return ResourceManager.GetString("DataFinalProcessamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data criação carga inicial.
        /// </summary>
        public static string DataInicioCriacaoCarga {
            get {
                return ResourceManager.GetString("DataInicioCriacaoCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Emissão inicial.
        /// </summary>
        public static string DataInicioEmissao {
            get {
                return ResourceManager.GetString("DataInicioEmissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data início processamento.
        /// </summary>
        public static string DataInicioProcessamento {
            get {
                return ResourceManager.GetString("DataInicioProcessamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data início viagem.
        /// </summary>
        public static string DataInicioViagem {
            get {
                return ResourceManager.GetString("DataInicioViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data início viagem até.
        /// </summary>
        public static string DataInicioViagemFinal {
            get {
                return ResourceManager.GetString("DataInicioViagemFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data início viagem de.
        /// </summary>
        public static string DataInicioViagemInicial {
            get {
                return ResourceManager.GetString("DataInicioViagemInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data prevista descarga.
        /// </summary>
        public static string DataPrevisaoDescarga {
            get {
                return ResourceManager.GetString("DataPrevisaoDescarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data previsão de entrega.
        /// </summary>
        public static string DataPrevisaoEntrega {
            get {
                return ResourceManager.GetString("DataPrevisaoEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data previsão de entrega até.
        /// </summary>
        public static string DataPrevisaoEntregaPedidoFinal {
            get {
                return ResourceManager.GetString("DataPrevisaoEntregaPedidoFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data previsão de entrega de.
        /// </summary>
        public static string DataPrevisaoEntregaPedidoInicial {
            get {
                return ResourceManager.GetString("DataPrevisaoEntregaPedidoInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data processamento.
        /// </summary>
        public static string DataProcessamento {
            get {
                return ResourceManager.GetString("DataProcessamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Descricao {
            get {
                return ResourceManager.GetString("Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatário.
        /// </summary>
        public static string Destinatario {
            get {
                return ResourceManager.GetString("Destinatario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destino.
        /// </summary>
        public static string Destino {
            get {
                return ResourceManager.GetString("Destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportador.
        /// </summary>
        public static string Empresa {
            get {
                return ResourceManager.GetString("Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapa.
        /// </summary>
        public static string Etapa {
            get {
                return ResourceManager.GetString("Etapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibir grid processamento.
        /// </summary>
        public static string ExibirGridProcessamento {
            get {
                return ResourceManager.GetString("ExibirGridProcessamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibir Processamentos.
        /// </summary>
        public static string ExibirProcessamentos {
            get {
                return ResourceManager.GetString("ExibirProcessamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha.
        /// </summary>
        public static string Falha {
            get {
                return ResourceManager.GetString("Falha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha ao informar inicio de viagem..
        /// </summary>
        public static string FalhaInformarInicioViagem {
            get {
                return ResourceManager.GetString("FalhaInformarInicioViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filial.
        /// </summary>
        public static string Filial {
            get {
                return ResourceManager.GetString("Filial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar.
        /// </summary>
        public static string Filtrar {
            get {
                return ResourceManager.GetString("Filtrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalização de Coletas e Entregas em Lote.
        /// </summary>
        public static string FinalizacaoColetasEntregasLote {
            get {
                return ResourceManager.GetString("FinalizacaoColetasEntregasLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizações.
        /// </summary>
        public static string Finalizacoes {
            get {
                return ResourceManager.GetString("Finalizacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizado.
        /// </summary>
        public static string Finalizado {
            get {
                return ResourceManager.GetString("Finalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcar/Desmarcar 100 primeiros registros.
        /// </summary>
        public static string MarcarDesmarcarPrimeiros100 {
            get {
                return ResourceManager.GetString("MarcarDesmarcarPrimeiros100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorista.
        /// </summary>
        public static string Motorista {
            get {
                return ResourceManager.GetString("Motorista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma carga entrega encontrada.
        /// </summary>
        public static string NenhumaCargaEncontrada {
            get {
                return ResourceManager.GetString("NenhumaCargaEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Carga.
        /// </summary>
        public static string NumCarga {
            get {
                return ResourceManager.GetString("NumCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Carga.
        /// </summary>
        public static string NumeroCarga {
            get {
                return ResourceManager.GetString("NumeroCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de tentativas.
        /// </summary>
        public static string NumeroTentativas {
            get {
                return ResourceManager.GetString("NumeroTentativas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filial Origem.
        /// </summary>
        public static string Origens {
            get {
                return ResourceManager.GetString("Origens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendente.
        /// </summary>
        public static string Pendente {
            get {
                return ResourceManager.GetString("Pendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string Pesquisar {
            get {
                return ResourceManager.GetString("Pesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placa.
        /// </summary>
        public static string Placa {
            get {
                return ResourceManager.GetString("Placa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processamento.
        /// </summary>
        public static string Processamento {
            get {
                return ResourceManager.GetString("Processamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processamento das Finalizações.
        /// </summary>
        public static string ProcessamentoFinalizacoes {
            get {
                return ResourceManager.GetString("ProcessamentoFinalizacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rastreador.
        /// </summary>
        public static string Rastreador {
            get {
                return ResourceManager.GetString("Rastreador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realize a filtragem para visualizar as Finalizações em processamento..
        /// </summary>
        public static string RealizeAsFiltragens {
            get {
                return ResourceManager.GetString("RealizeAsFiltragens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remetente.
        /// </summary>
        public static string Remetente {
            get {
                return ResourceManager.GetString("Remetente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionados.
        /// </summary>
        public static string Selecionados {
            get {
                return ResourceManager.GetString("Selecionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você pode selecionar no máximo 100 registros por vez..
        /// </summary>
        public static string SelecionarCemRegistrosVez {
            get {
                return ResourceManager.GetString("SelecionarCemRegistrosVez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcar/Desmarcar 100 primeiros registros.
        /// </summary>
        public static string SelecionarTodos {
            get {
                return ResourceManager.GetString("SelecionarTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você precisa selecionar ao menos um registro para realizar essa ação..
        /// </summary>
        public static string SelecionarUmRegistro {
            get {
                return ResourceManager.GetString("SelecionarUmRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma ou mais cargas para visualizar informações de finalização..
        /// </summary>
        public static string SelecioneUmaOuMaisCargas {
            get {
                return ResourceManager.GetString("SelecioneUmaOuMaisCargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string Situacao {
            get {
                return ResourceManager.GetString("Situacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação Carga.
        /// </summary>
        public static string SituacaoCarga {
            get {
                return ResourceManager.GetString("SituacaoCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação Controle de Entrega.
        /// </summary>
        public static string SituacaoControleDeEntrega {
            get {
                return ResourceManager.GetString("SituacaoControleDeEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação do Monitoramento.
        /// </summary>
        public static string SituacaoMonitoramento {
            get {
                return ResourceManager.GetString("SituacaoMonitoramento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação Processamento.
        /// </summary>
        public static string SituacaoProcessamento {
            get {
                return ResourceManager.GetString("SituacaoProcessamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Operação.
        /// </summary>
        public static string TiposOperacao {
            get {
                return ResourceManager.GetString("TiposOperacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomador.
        /// </summary>
        public static string Tomador {
            get {
                return ResourceManager.GetString("Tomador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torre de Controle.
        /// </summary>
        public static string TorreControle {
            get {
                return ResourceManager.GetString("TorreControle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportador.
        /// </summary>
        public static string Transportador {
            get {
                return ResourceManager.GetString("Transportador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veículo.
        /// </summary>
        public static string Veiculo {
            get {
                return ResourceManager.GetString("Veiculo", resourceCulture);
            }
        }
    }
}
