// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.alianca.mtms.emp.responsebuscarcte
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	using Newtonsoft.Json;

	public partial class DominioObjetosDeValorEmbarcadorCargaContainer : ISpecificRecord
	{
		[JsonIgnore]
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""DominioObjetosDeValorEmbarcadorCargaContainer"",""namespace"":""com.alianca.mtms.emp.responsebuscarcte"",""fields"":[{""name"":""Codigo"",""type"":""int""},{""name"":""CodigoIntegracao"",""type"":""int""},{""name"":""Descricao"",""type"":""string""},{""name"":""Numero"",""type"":""string""},{""name"":""PesoLiquido"",""type"":""bytes""},{""name"":""Tara"",""type"":""int""},{""name"":""TipoPropriedade"",""type"":{""type"":""enum"",""name"":""DominioObjetosDeValorEmbarcadorEnumeradoresTipoPropriedadeContainer"",""namespace"":""com.alianca.mtms.emp.responsebuscarcte"",""symbols"":[""Nenhum"",""Proprio"",""Soc""]}},{""name"":""TipoContainer"",""type"":{""type"":""record"",""name"":""DominioObjetosDeValorEmbarcadorCargaTipoContainer"",""namespace"":""com.alianca.mtms.emp.responsebuscarcte"",""fields"":[{""name"":""Codigo"",""type"":""int""},{""name"":""CodigoDocumento"",""type"":""string""},{""name"":""CodigoIntegracao"",""type"":""int""},{""name"":""Descricao"",""type"":""string""},{""name"":""Valor"",""type"":""bytes""},{""name"":""Atualizar"",""type"":""boolean""},{""name"":""InativarCadastro"",""type"":""boolean""},{""name"":""MetrosCubicos"",""type"":""bytes""},{""name"":""Tara"",""type"":""bytes""},{""name"":""PesoLiquido"",""type"":""bytes""},{""name"":""TEU"",""type"":""string""},{""name"":""FFE"",""type"":""string""},{""name"":""PesoMaximo"",""type"":""bytes""}]}},{""name"":""InativarCadastro"",""type"":""boolean""},{""name"":""Atualizar"",""type"":""boolean""},{""name"":""Lacre1"",""type"":""string""},{""name"":""Lacre2"",""type"":""string""},{""name"":""Lacre3"",""type"":""string""},{""name"":""Volume"",""type"":""bytes""},{""name"":""DencidadeProduto"",""type"":""bytes""}]}");
		private int _Codigo;
		private int _CodigoIntegracao;
		private string _Descricao;
		private string _Numero;
		private byte[] _PesoLiquido;
		private int _Tara;
		private com.alianca.mtms.emp.responsebuscarcte.DominioObjetosDeValorEmbarcadorEnumeradoresTipoPropriedadeContainer _TipoPropriedade;
		private com.alianca.mtms.emp.responsebuscarcte.DominioObjetosDeValorEmbarcadorCargaTipoContainer _TipoContainer;
		private bool _InativarCadastro;
		private bool _Atualizar;
		private string _Lacre1;
		private string _Lacre2;
		private string _Lacre3;
		private byte[] _Volume;
		private byte[] _DencidadeProduto;

		[JsonIgnore]
		public virtual Schema Schema
		{
			get
			{
				return DominioObjetosDeValorEmbarcadorCargaContainer._SCHEMA;
			}
		}
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				this._Codigo = value;
			}
		}
		public int CodigoIntegracao
		{
			get
			{
				return this._CodigoIntegracao;
			}
			set
			{
				this._CodigoIntegracao = value;
			}
		}
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				this._Descricao = value;
			}
		}
		public string Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				this._Numero = value;
			}
		}
		public byte[] PesoLiquido
		{
			get
			{
				return this._PesoLiquido;
			}
			set
			{
				this._PesoLiquido = value;
			}
		}
		public int Tara
		{
			get
			{
				return this._Tara;
			}
			set
			{
				this._Tara = value;
			}
		}
		public com.alianca.mtms.emp.responsebuscarcte.DominioObjetosDeValorEmbarcadorEnumeradoresTipoPropriedadeContainer TipoPropriedade
		{
			get
			{
				return this._TipoPropriedade;
			}
			set
			{
				this._TipoPropriedade = value;
			}
		}
		public com.alianca.mtms.emp.responsebuscarcte.DominioObjetosDeValorEmbarcadorCargaTipoContainer TipoContainer
		{
			get
			{
				return this._TipoContainer;
			}
			set
			{
				this._TipoContainer = value;
			}
		}
		public bool InativarCadastro
		{
			get
			{
				return this._InativarCadastro;
			}
			set
			{
				this._InativarCadastro = value;
			}
		}
		public bool Atualizar
		{
			get
			{
				return this._Atualizar;
			}
			set
			{
				this._Atualizar = value;
			}
		}
		public string Lacre1
		{
			get
			{
				return this._Lacre1;
			}
			set
			{
				this._Lacre1 = value;
			}
		}
		public string Lacre2
		{
			get
			{
				return this._Lacre2;
			}
			set
			{
				this._Lacre2 = value;
			}
		}
		public string Lacre3
		{
			get
			{
				return this._Lacre3;
			}
			set
			{
				this._Lacre3 = value;
			}
		}
		public byte[] Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				this._Volume = value;
			}
		}
		public byte[] DencidadeProduto
		{
			get
			{
				return this._DencidadeProduto;
			}
			set
			{
				this._DencidadeProduto = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Codigo;
			case 1: return this.CodigoIntegracao;
			case 2: return this.Descricao;
			case 3: return this.Numero;
			case 4: return this.PesoLiquido;
			case 5: return this.Tara;
			case 6: return this.TipoPropriedade;
			case 7: return this.TipoContainer;
			case 8: return this.InativarCadastro;
			case 9: return this.Atualizar;
			case 10: return this.Lacre1;
			case 11: return this.Lacre2;
			case 12: return this.Lacre3;
			case 13: return this.Volume;
			case 14: return this.DencidadeProduto;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Codigo = (System.Int32)fieldValue; break;
			case 1: this.CodigoIntegracao = (System.Int32)fieldValue; break;
			case 2: this.Descricao = (System.String)fieldValue; break;
			case 3: this.Numero = (System.String)fieldValue; break;
			case 4: this.PesoLiquido = (System.Byte[])fieldValue; break;
			case 5: this.Tara = (System.Int32)fieldValue; break;
			case 6: this.TipoPropriedade = (com.alianca.mtms.emp.responsebuscarcte.DominioObjetosDeValorEmbarcadorEnumeradoresTipoPropriedadeContainer)fieldValue; break;
			case 7: this.TipoContainer = (com.alianca.mtms.emp.responsebuscarcte.DominioObjetosDeValorEmbarcadorCargaTipoContainer)fieldValue; break;
			case 8: this.InativarCadastro = (System.Boolean)fieldValue; break;
			case 9: this.Atualizar = (System.Boolean)fieldValue; break;
			case 10: this.Lacre1 = (System.String)fieldValue; break;
			case 11: this.Lacre2 = (System.String)fieldValue; break;
			case 12: this.Lacre3 = (System.String)fieldValue; break;
			case 13: this.Volume = (System.Byte[])fieldValue; break;
			case 14: this.DencidadeProduto = (System.Byte[])fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
