// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.alianca.mtms.emp.containerviagem
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	using Newtonsoft.Json;

	public partial class ContainerViagem : ISpecificRecord
	{

		[JsonIgnore]
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""ContainerViagem"",""namespace"":""com.alianca.mtms.emp.containerviagem"",""fields"":[{""name"":""CodigoViagem"",""type"":""int""},{""name"":""Containers"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""Container"",""namespace"":""Alianca.PushService.Domain.Models.Avro"",""fields"":[{""name"":""CodigoContainer"",""type"":""int""},{""name"":""CodigoPaisOrigem"",""type"":""int""},{""name"":""CodigoProgramacaoViagemContainer"",""type"":""int""},{""name"":""CodigoPropContainer"",""type"":""int""},{""name"":""CodigoTipoContainer"",""type"":""int""},{""name"":""CodigoVIagem"",""type"":""int""},{""name"":""IndicadorReutilizado"",""type"":""int""},{""name"":""lacres"",""type"":""string""},{""name"":""Nome"",""type"":""string""},{""name"":""NumeroCNPJ"",""type"":""string""},{""name"":""NumeroContainer"",""type"":""string""},{""name"":""NumeroProgramacao"",""type"":""string""},{""name"":""Observacao"",""type"":""string""},{""name"":""PesoTotal"",""type"":""double""},{""name"":""Sigla"",""type"":""string""},{""name"":""ValorTaraEspecifica"",""type"":""double""}]}}}]}");
		private int _CodigoViagem;
		private IList<Alianca.PushService.Domain.Models.Avro.Container> _Containers;

		[JsonIgnore]
		public virtual Schema Schema
		{
			get
			{
				return ContainerViagem._SCHEMA;
			}
		}
		public int CodigoViagem
		{
			get
			{
				return this._CodigoViagem;
			}
			set
			{
				this._CodigoViagem = value;
			}
		}
		public IList<Alianca.PushService.Domain.Models.Avro.Container> Containers
		{
			get
			{
				return this._Containers;
			}
			set
			{
				this._Containers = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.CodigoViagem;
			case 1: return this.Containers;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.CodigoViagem = (System.Int32)fieldValue; break;
			case 1: this.Containers = (IList<Alianca.PushService.Domain.Models.Avro.Container>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
