//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Resources.Logistica {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExcecaoCapacidadeCarregamento {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcecaoCapacidadeCarregamento() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Resources.Logistica.ExcecaoCapacidadeCarregamento", typeof(ExcecaoCapacidadeCarregamento).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Modelo de Veículo.
        /// </summary>
        public static string AdicionarModeloVeiculo {
            get {
                return ResourceManager.GetString("AdicionarModeloVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Exceção de Capacidade de Carregamento.
        /// </summary>
        public static string CadastrarExcecaoCapacidadeCarregamento {
            get {
                return ResourceManager.GetString("CadastrarExcecaoCapacidadeCarregamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidade.
        /// </summary>
        public static string Capacidade {
            get {
                return ResourceManager.GetString("Capacidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidade de Carregamento (Cubagem).
        /// </summary>
        public static string CapacidadeDeCarregamentoCubagem {
            get {
                return ResourceManager.GetString("CapacidadeDeCarregamentoCubagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidade de Carregamento (KG).
        /// </summary>
        public static string CapacidadedeCarregamentoKG {
            get {
                return ResourceManager.GetString("CapacidadedeCarregamentoKG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidade de Carregamento (Volume).
        /// </summary>
        public static string CapacidadeDeCarregamentoVolume {
            get {
                return ResourceManager.GetString("CapacidadeDeCarregamentoVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargas Excedentes.
        /// </summary>
        public static string CargasExcedentes {
            get {
                return ResourceManager.GetString("CargasExcedentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregamento Simultâneo.
        /// </summary>
        public static string CarregamentoSimultaneo {
            get {
                return ResourceManager.GetString("CarregamentoSimultaneo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car. Simultâneo.
        /// </summary>
        public static string CarSimultaneo {
            get {
                return ResourceManager.GetString("CarSimultaneo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de Carregamento.
        /// </summary>
        public static string CentroCarregamento {
            get {
                return ResourceManager.GetString("CentroCarregamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O centro de carregamento deve ser informado..
        /// </summary>
        public static string CentroCarregamentoDeveSerInformado {
            get {
                return ResourceManager.GetString("CentroCarregamentoDeveSerInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Final.
        /// </summary>
        public static string DataFinal {
            get {
                return ResourceManager.GetString("DataFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Final Obrigatória..
        /// </summary>
        public static string DataFinalObrigatoria {
            get {
                return ResourceManager.GetString("DataFinalObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Inicial.
        /// </summary>
        public static string DataInicial {
            get {
                return ResourceManager.GetString("DataInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia Semana.
        /// </summary>
        public static string DiaSemana {
            get {
                return ResourceManager.GetString("DiaSemana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dom.
        /// </summary>
        public static string Dom {
            get {
                return ResourceManager.GetString("Dom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceção de Capacidade de Carregamento.
        /// </summary>
        public static string ExcecaoCapacidadedeCarregamento {
            get {
                return ResourceManager.GetString("ExcecaoCapacidadedeCarregamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceções de Capacidade de Carregamento.
        /// </summary>
        public static string ExcecoesCapacidadeCarregamento {
            get {
                return ResourceManager.GetString("ExcecoesCapacidadeCarregamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excesso de Tempo.
        /// </summary>
        public static string ExcessoTempo {
            get {
                return ResourceManager.GetString("ExcessoTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluiu o registro.
        /// </summary>
        public static string ExcluiuRegistro {
            get {
                return ResourceManager.GetString("ExcluiuRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faixa de Carregamentos.
        /// </summary>
        public static string FaixaCarregamentos {
            get {
                return ResourceManager.GetString("FaixaCarregamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faixa de Carregamentos.
        /// </summary>
        public static string FaixaDeCarregamentos {
            get {
                return ResourceManager.GetString("FaixaDeCarregamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulário de Cadastro.
        /// </summary>
        public static string FormularioCadastro {
            get {
                return ResourceManager.GetString("FormularioCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar de outro dia.
        /// </summary>
        public static string ImportarOutroDia {
            get {
                return ResourceManager.GetString("ImportarOutroDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar para os demais dias.
        /// </summary>
        public static string ImportarParaDemaisDias {
            get {
                return ResourceManager.GetString("ImportarParaDemaisDias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar.
        /// </summary>
        public static string Limpar {
            get {
                return ResourceManager.GetString("Limpar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar o período de carregamento..
        /// </summary>
        public static string NaoFoiPossivelEncontrarPeriodoCarregamento {
            get {
                return ResourceManager.GetString("NaoFoiPossivelEncontrarPeriodoCarregamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar o período de carregamento tipo operação simultâneo..
        /// </summary>
        public static string NaoFoiPossivelEncontrarPeriodoCarregamentoTipoOperacaoSimultaneo {
            get {
                return ResourceManager.GetString("NaoFoiPossivelEncontrarPeriodoCarregamentoTipoOperacaoSimultaneo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar a previsão de carregamento..
        /// </summary>
        public static string NaoFoiPossivelEncontrarPrevisaoCarregamento {
            get {
                return ResourceManager.GetString("NaoFoiPossivelEncontrarPrevisaoCarregamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar o modelo veicular de carga..
        /// </summary>
        public static string NaoPossivelEncontrarModeloVeicularCarga {
            get {
                return ResourceManager.GetString("NaoPossivelEncontrarModeloVeicularCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar a rota..
        /// </summary>
        public static string NaoPossivelEncontrarRota {
            get {
                return ResourceManager.GetString("NaoPossivelEncontrarRota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período de Carregamento.
        /// </summary>
        public static string PeriodoCarregamento {
            get {
                return ResourceManager.GetString("PeriodoCarregamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período em Editação.
        /// </summary>
        public static string PeriodoEditacao {
            get {
                return ResourceManager.GetString("PeriodoEditacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período já existe.
        /// </summary>
        public static string PeriodoExiste {
            get {
                return ResourceManager.GetString("PeriodoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar Exceções de Capacidade de Carregamento.
        /// </summary>
        public static string PesquisarExcecoesCapacidadeCarregamento {
            get {
                return ResourceManager.GetString("PesquisarExcecoesCapacidadeCarregamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previsão de Carregamento.
        /// </summary>
        public static string PrevisaoCarregamento {
            get {
                return ResourceManager.GetString("PrevisaoCarregamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A previsão já existe.
        /// </summary>
        public static string PrevisaoJaExiste {
            get {
                return ResourceManager.GetString("PrevisaoJaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qtd. de Cargas Excedentes.
        /// </summary>
        public static string QtdCargasExcedentes {
            get {
                return ResourceManager.GetString("QtdCargasExcedentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qua.
        /// </summary>
        public static string Qua {
            get {
                return ResourceManager.GetString("Qua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de Cargas.
        /// </summary>
        public static string QuantidadeCargas {
            get {
                return ResourceManager.GetString("QuantidadeCargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade simultânea inválida.
        /// </summary>
        public static string QuantidadeSimultaneaInvalida {
            get {
                return ResourceManager.GetString("QuantidadeSimultaneaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qui.
        /// </summary>
        public static string Qui {
            get {
                return ResourceManager.GetString("Qui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rota.
        /// </summary>
        public static string Rota {
            get {
                return ResourceManager.GetString("Rota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sab.
        /// </summary>
        public static string Sab {
            get {
                return ResourceManager.GetString("Sab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seg.
        /// </summary>
        public static string Seg {
            get {
                return ResourceManager.GetString("Seg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugestão.
        /// </summary>
        public static string Sugestao {
            get {
                return ResourceManager.GetString("Sugestao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ter.
        /// </summary>
        public static string Ter {
            get {
                return ResourceManager.GetString("Ter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Término.
        /// </summary>
        public static string Termino {
            get {
                return ResourceManager.GetString("Termino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Operação.
        /// </summary>
        public static string TipoOperacao {
            get {
                return ResourceManager.GetString("TipoOperacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Operação já existe.
        /// </summary>
        public static string TipoOperacaoExiste {
            get {
                return ResourceManager.GetString("TipoOperacaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Operação.
        /// </summary>
        public static string TiposOperacao {
            get {
                return ResourceManager.GetString("TiposOperacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerância.
        /// </summary>
        public static string Tolerancia {
            get {
                return ResourceManager.GetString("Tolerancia", resourceCulture);
            }
        }
    }
}
