//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Resources.Logistica {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MotivoParadaCentro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MotivoParadaCentro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Resources.Logistica.MotivoParadaCentro", typeof(MotivoParadaCentro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string Adicionar {
            get {
                return ResourceManager.GetString("Adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar.
        /// </summary>
        public static string Atualizar {
            get {
                return ResourceManager.GetString("Atualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Motivo de Parada de Centro de Carregamento.
        /// </summary>
        public static string CadastrarMotivoParadaCentroCarregamento {
            get {
                return ResourceManager.GetString("CadastrarMotivoParadaCentroCarregamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro.
        /// </summary>
        public static string Centro {
            get {
                return ResourceManager.GetString("Centro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de Carregamento.
        /// </summary>
        public static string CentroCarregamento {
            get {
                return ResourceManager.GetString("CentroCarregamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Descricao {
            get {
                return ResourceManager.GetString("Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string Excluir {
            get {
                return ResourceManager.GetString("Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma quantidade informada com o tipo de operação .
        /// </summary>
        public static string JaExisteQuantidadeInformadaTipoOperação {
            get {
                return ResourceManager.GetString("JaExisteQuantidadeInformadaTipoOperação", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logística.
        /// </summary>
        public static string Logistica {
            get {
                return ResourceManager.GetString("Logistica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivos Parada de Centro de Carregamento.
        /// </summary>
        public static string MotivosParadaCentroCarregamento {
            get {
                return ResourceManager.GetString("MotivosParadaCentroCarregamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível cadastrar uma data retroativa.
        /// </summary>
        public static string NaoEPossívelCadastrarUmaDataRetroativa {
            get {
                return ResourceManager.GetString("NaoEPossívelCadastrarUmaDataRetroativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar o tipo de operação.
        /// </summary>
        public static string NãoFoiPossivelEncontrarOTipoDeOperação {
            get {
                return ResourceManager.GetString("NãoFoiPossivelEncontrarOTipoDeOperação", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O período inicial não pode ser maior que o período final.
        /// </summary>
        public static string OPeriodoInicialNaoPodeSerMaiorQueOPeriodoFinal {
            get {
                return ResourceManager.GetString("OPeriodoInicialNaoPodeSerMaiorQueOPeriodoFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período Final.
        /// </summary>
        public static string PeriodoFim {
            get {
                return ResourceManager.GetString("PeriodoFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período Inicial.
        /// </summary>
        public static string PeriodoInicio {
            get {
                return ResourceManager.GetString("PeriodoInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string Pesquisar {
            get {
                return ResourceManager.GetString("Pesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar Motivos de Parada de Centro de Carregamento.
        /// </summary>
        public static string PesquisarMotivosParadaCentroCarregamento {
            get {
                return ResourceManager.GetString("PesquisarMotivosParadaCentroCarregamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade.
        /// </summary>
        public static string Quantidade {
            get {
                return ResourceManager.GetString("Quantidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade parada.
        /// </summary>
        public static string QuantidadeParada {
            get {
                return ResourceManager.GetString("QuantidadeParada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string Situacao {
            get {
                return ResourceManager.GetString("Situacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Operação.
        /// </summary>
        public static string TipoOperacao {
            get {
                return ResourceManager.GetString("TipoOperacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Operação já existe.
        /// </summary>
        public static string TipoOperacaoJaExiste {
            get {
                return ResourceManager.GetString("TipoOperacaoJaExiste", resourceCulture);
            }
        }
    }
}
