using System;

namespace Dominio.ObjetosDeValor.Embarcador.Financeiro
{
    public class DocumentoEntradaItem
    {
        public NotaFiscal.Produto Produto { get; set; }
        public OrdemCompraMercadoria OrdemCompraMercadoria { get; set; }
        public Frota.OrdemServicoFrota OrdemServico { get; set; }
        public string CodigoProdutoFornecedor { get; set; }
        public string DescricaoProdutoFornecedor { get; set; }
        public string CodigoBarrasEAN { get; set; }
        public Dominio.ObjetosDeValor.Embarcador.Enumeradores.UnidadeDeMedida UnidadeMedida { get; set; }
        public CFOP CFOP { get; set; }
        public NaturezaDaOperacao NaturezaOperacao { get; set; }
        public TipoMovimento TipoMovimento { get; set; }
        public int Sequencial { get; set; }
        public decimal? Quantidade { get; set; }
        public decimal? ValorUnitario { get; set; }
        public decimal? Desconto { get; set; }
        public decimal? ValorTotal { get; set; }
        public string CSTICMS { get; set; }
        public decimal? AliquotaICMS { get; set; }
        public decimal? BaseCalculoICMS { get; set; }
        public decimal? ValorICMS { get; set; }
        public string CSTIPI { get; set; }
        public decimal? PercentualReducaoBaseCalculoIPI { get; set; }
        public decimal? AliquotaIPI { get; set; }
        public decimal? BaseCalculoIPI { get; set; }
        public decimal? ValorIPI { get; set; }
        public decimal? BaseCalculoICMSST { get; set; }
        public decimal? AliquotaICMSST { get; set; }
        public decimal? ValorICMSST { get; set; }
        public decimal? OutrasDespesas { get; set; }
        public decimal? ValorFrete { get; set; }
        public string CSTPIS { get; set; }
        public decimal? PercentualReducaoBaseCalculoPIS { get; set; }
        public decimal? BaseCalculoPIS { get; set; }
        public decimal? AliquotaPIS { get; set; }
        public decimal? ValorPIS { get; set; }
        public string CSTCOFINS { get; set; }
        public decimal? PercentualReducaoBaseCalculoCOFINS { get; set; }
        public decimal? BaseCalculoCOFINS { get; set; }
        public decimal? AliquotaCOFINS { get; set; }
        public decimal? ValorCOFINS { get; set; }
        public decimal? BaseCalculoCreditoPresumido { get; set; }
        public decimal? AliquotaCreditoPresumido { get; set; }
        public decimal? ValorCreditoPresumido { get; set; }
        public decimal? BaseCalculoDiferencial { get; set; }
        public decimal? AliquotaDiferencial { get; set; }
        public decimal? ValorDiferencial { get; set; }
        public decimal? ValorSeguro { get; set; }
        public decimal? ValorFreteFora { get; set; }
        public decimal? ValorOutrasDespesasFora { get; set; }
        public decimal? ValorDescontoFora { get; set; }
        public decimal? ValorImpostosFora { get; set; }
        public decimal? ValorDiferencialFreteFora { get; set; }
        public decimal? ValorICMSFreteFora { get; set; }
        public decimal? ValorCustoUnitario { get; set; }
        public decimal? ValorCustoTotal { get; set; }
        public string CalculoCustoProduto { get; set; }
        public string CESTProdutoFornecedor { get; set; }
        public string NCMProdutoFornecedor { get; set; }
        public decimal? ValorRetencaoPIS { get; set; }
        public decimal? ValorRetencaoCOFINS { get; set; }
        public decimal? ValorRetencaoINSS { get; set; }
        public decimal? ValorRetencaoIPI { get; set; }
        public decimal? ValorRetencaoCSLL { get; set; }
        public decimal? ValorRetencaoOutras { get; set; }
        public decimal? ValorRetencaoIR { get; set; }
        public decimal? ValorRetencaoISS { get; set; }
        public string Observacao { get; set; }
        public decimal FatorConversao { get; set; }
        public Veiculo Veiculo { get; set; }
        public DateTime? DataAbastecimento { get; set; }
        public int KMAbastecimento { get; set; }
        public int CodigoRegraEntradaDocumento { get; set; }
        public decimal? BaseSTRetido { get; set; }
        public decimal? ValorSTRetido { get; set; }
        public int Horimetro { get; set; }
        public Dominio.ObjetosDeValor.Embarcador.Veiculos.Equipamento Equipamento { get; set; }
        public int? NumeroFogoInicial { get; set; }
        public Dominio.ObjetosDeValor.Embarcador.Enumeradores.TipoAquisicaoPneu? TipoAquisicao { get; set; }
        public Dominio.ObjetosDeValor.Embarcador.Enumeradores.VidaPneu? VidaAtual { get; set; }
        public int CodigoAlmoxarifado { get; set; }
        public NotaFiscal.Produto ProdutoVinculado { get; set; }
        public decimal? QuantidadeProdutoVinculado { get; set; }
        public int CodigoLocalArmazenamento { get; set; }
        public string UnidadeMedidaFornecedor { get; set; }
        public decimal? QuantidadeFornecedor { get; set; }
        public decimal? ValorUnitarioFornecedor { get; set; }
        public CentroResultado CentroResultado { get; set; }
        public bool GeraRateioDespesaVeiculo { get; set; }
        public ObjetosDeValor.Embarcador.Enumeradores.OrigemMercadoria? OrigemMercadoria { get; set; }
        public bool EncerrarOrdemServico { get; set; }
        public decimal ValorAbastecimentoTabelaFornecedor { get; set; }
        public bool ValorAbastecimentoComDivergencia { get; set; }
    }
}
