//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicos.ServicoEFrete.Logon {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.ipc.adm.br/efrete/logon", ConfigurationName="ServicoEFrete.Logon.LogonServiceSoap")]
    public interface LogonServiceSoap {
        
        // CODEGEN: Generating message contract since message part namespace (http://schemas.ipc.adm.br/efrete/logon/objects) does not match the default value (http://schemas.ipc.adm.br/efrete/logon)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipc.adm.br/efrete/logon/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        Servicos.ServicoEFrete.Logon.LoginResponse1 Login(Servicos.ServicoEFrete.Logon.LoginRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipc.adm.br/efrete/logon/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicos.ServicoEFrete.Logon.LoginResponse1> LoginAsync(Servicos.ServicoEFrete.Logon.LoginRequest1 request);
        
        // CODEGEN: Generating message contract since message part namespace (http://schemas.ipc.adm.br/efrete/logon/objects) does not match the default value (http://schemas.ipc.adm.br/efrete/logon)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipc.adm.br/efrete/logon/Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        Servicos.ServicoEFrete.Logon.LogoutResponse1 Logout(Servicos.ServicoEFrete.Logon.LogoutRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipc.adm.br/efrete/logon/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicos.ServicoEFrete.Logon.LogoutResponse1> LogoutAsync(Servicos.ServicoEFrete.Logon.LogoutRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.ipc.adm.br/efrete/logon/objects")]
    public partial class LoginRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string integradorField;
        
        private int versaoField;
        
        private string usuarioField;
        
        private string senhaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Integrador {
            get {
                return this.integradorField;
            }
            set {
                this.integradorField = value;
                this.RaisePropertyChanged("Integrador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
                this.RaisePropertyChanged("Versao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
                this.RaisePropertyChanged("Senha");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LogoutRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.ipc.adm.br/efrete/objects")]
    public abstract partial class Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string integradorField;
        
        private int versaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Integrador {
            get {
                return this.integradorField;
            }
            set {
                this.integradorField = value;
                this.RaisePropertyChanged("Integrador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
                this.RaisePropertyChanged("Versao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.ipc.adm.br/efrete/logon/objects")]
    public partial class LogoutRequest : Request {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.ipc.adm.br/efrete/objects")]
    public partial class Excecao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mensagemField;
        
        private string codigoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LogoutResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.ipc.adm.br/efrete/objects")]
    public abstract partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int versaoField;
        
        private bool sucessoField;
        
        private Excecao excecaoField;
        
        private System.Nullable<long> protocoloServicoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
                this.RaisePropertyChanged("Versao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
                this.RaisePropertyChanged("Sucesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Excecao Excecao {
            get {
                return this.excecaoField;
            }
            set {
                this.excecaoField = value;
                this.RaisePropertyChanged("Excecao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<long> ProtocoloServico {
            get {
                return this.protocoloServicoField;
            }
            set {
                this.protocoloServicoField = value;
                this.RaisePropertyChanged("ProtocoloServico");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.ipc.adm.br/efrete/logon/objects")]
    public partial class LogoutResponse : Response {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.ipc.adm.br/efrete/logon/objects")]
    public partial class LoginResponse : Response {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://schemas.ipc.adm.br/efrete/logon", IsWrapped=true)]
    public partial class LoginRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.ipc.adm.br/efrete/logon/objects", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.ipc.adm.br/efrete/logon/objects")]
        public Servicos.ServicoEFrete.Logon.LoginRequest LoginRequest;
        
        public LoginRequest1() {
        }
        
        public LoginRequest1(Servicos.ServicoEFrete.Logon.LoginRequest LoginRequest) {
            this.LoginRequest = LoginRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://schemas.ipc.adm.br/efrete/logon", IsWrapped=true)]
    public partial class LoginResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.ipc.adm.br/efrete/logon/objects", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.ipc.adm.br/efrete/logon/objects", IsNullable=true)]
        public Servicos.ServicoEFrete.Logon.LoginResponse LoginResult;
        
        public LoginResponse1() {
        }
        
        public LoginResponse1(Servicos.ServicoEFrete.Logon.LoginResponse LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Logout", WrapperNamespace="http://schemas.ipc.adm.br/efrete/logon", IsWrapped=true)]
    public partial class LogoutRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.ipc.adm.br/efrete/logon/objects", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.ipc.adm.br/efrete/logon/objects")]
        public Servicos.ServicoEFrete.Logon.LogoutRequest LogoutRequest;
        
        public LogoutRequest1() {
        }
        
        public LogoutRequest1(Servicos.ServicoEFrete.Logon.LogoutRequest LogoutRequest) {
            this.LogoutRequest = LogoutRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogoutResponse", WrapperNamespace="http://schemas.ipc.adm.br/efrete/logon", IsWrapped=true)]
    public partial class LogoutResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.ipc.adm.br/efrete/logon/objects", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.ipc.adm.br/efrete/logon/objects", IsNullable=true)]
        public Servicos.ServicoEFrete.Logon.LogoutResponse LogoutResult;
        
        public LogoutResponse1() {
        }
        
        public LogoutResponse1(Servicos.ServicoEFrete.Logon.LogoutResponse LogoutResult) {
            this.LogoutResult = LogoutResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LogonServiceSoapChannel : Servicos.ServicoEFrete.Logon.LogonServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogonServiceSoapClient : System.ServiceModel.ClientBase<Servicos.ServicoEFrete.Logon.LogonServiceSoap>, Servicos.ServicoEFrete.Logon.LogonServiceSoap {
        
        public LogonServiceSoapClient() {
        }
        
        public LogonServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogonServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogonServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogonServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servicos.ServicoEFrete.Logon.LoginResponse1 Servicos.ServicoEFrete.Logon.LogonServiceSoap.Login(Servicos.ServicoEFrete.Logon.LoginRequest1 request) {
            return base.Channel.Login(request);
        }
        
        public Servicos.ServicoEFrete.Logon.LoginResponse Login(Servicos.ServicoEFrete.Logon.LoginRequest LoginRequest) {
            Servicos.ServicoEFrete.Logon.LoginRequest1 inValue = new Servicos.ServicoEFrete.Logon.LoginRequest1();
            inValue.LoginRequest = LoginRequest;
            Servicos.ServicoEFrete.Logon.LoginResponse1 retVal = ((Servicos.ServicoEFrete.Logon.LogonServiceSoap)(this)).Login(inValue);
            return retVal.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Servicos.ServicoEFrete.Logon.LoginResponse1> Servicos.ServicoEFrete.Logon.LogonServiceSoap.LoginAsync(Servicos.ServicoEFrete.Logon.LoginRequest1 request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Servicos.ServicoEFrete.Logon.LoginResponse1> LoginAsync(Servicos.ServicoEFrete.Logon.LoginRequest LoginRequest) {
            Servicos.ServicoEFrete.Logon.LoginRequest1 inValue = new Servicos.ServicoEFrete.Logon.LoginRequest1();
            inValue.LoginRequest = LoginRequest;
            return ((Servicos.ServicoEFrete.Logon.LogonServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servicos.ServicoEFrete.Logon.LogoutResponse1 Servicos.ServicoEFrete.Logon.LogonServiceSoap.Logout(Servicos.ServicoEFrete.Logon.LogoutRequest1 request) {
            return base.Channel.Logout(request);
        }
        
        public Servicos.ServicoEFrete.Logon.LogoutResponse Logout(Servicos.ServicoEFrete.Logon.LogoutRequest LogoutRequest) {
            Servicos.ServicoEFrete.Logon.LogoutRequest1 inValue = new Servicos.ServicoEFrete.Logon.LogoutRequest1();
            inValue.LogoutRequest = LogoutRequest;
            Servicos.ServicoEFrete.Logon.LogoutResponse1 retVal = ((Servicos.ServicoEFrete.Logon.LogonServiceSoap)(this)).Logout(inValue);
            return retVal.LogoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Servicos.ServicoEFrete.Logon.LogoutResponse1> Servicos.ServicoEFrete.Logon.LogonServiceSoap.LogoutAsync(Servicos.ServicoEFrete.Logon.LogoutRequest1 request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Servicos.ServicoEFrete.Logon.LogoutResponse1> LogoutAsync(Servicos.ServicoEFrete.Logon.LogoutRequest LogoutRequest) {
            Servicos.ServicoEFrete.Logon.LogoutRequest1 inValue = new Servicos.ServicoEFrete.Logon.LogoutRequest1();
            inValue.LogoutRequest = LogoutRequest;
            return ((Servicos.ServicoEFrete.Logon.LogonServiceSoap)(this)).LogoutAsync(inValue);
        }
    }
}
