// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.maersk.customer.smds.commercial.msk
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
    using Newtonsoft.Json;

    public partial class CustomerHierarchyInformation : ISpecificRecord
	{
        [JsonIgnore]
        public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""CustomerHierarchyInformation"",""namespace"":""com.maersk.customer.smds.commercial.msk"",""fields"":[{""name"":""guoCustomerCode"",""doc"":""This is Global Ultimate Owner Customer code"",""default"":null,""type"":[""null"",""string""]},{""name"":""guoLegalName"",""doc"":""This is Global Ultimate Owner Customer legal name"",""default"":null,""type"":[""null"",""string""]},{""name"":""hqCustomerCode"",""doc"":""This is Head Quarter Customer code"",""default"":null,""type"":[""null"",""string""]},{""name"":""hqLegalName"",""doc"":""This is Head Quarter Customer legal name"",""default"":null,""type"":[""null"",""string""]},{""name"":""hqStatus"",""doc"":""This is Head Quarter Status"",""default"":null,""type"":[""null"",""string""]},{""name"":""guoStatus"",""doc"":""This is Global Ultimate Owner Status"",""default"":null,""type"":[""null"",""string""]}]}");
		/// <summary>
		/// This is Global Ultimate Owner Customer code
		/// </summary>
		private string _guoCustomerCode;
		/// <summary>
		/// This is Global Ultimate Owner Customer legal name
		/// </summary>
		private string _guoLegalName;
		/// <summary>
		/// This is Head Quarter Customer code
		/// </summary>
		private string _hqCustomerCode;
		/// <summary>
		/// This is Head Quarter Customer legal name
		/// </summary>
		private string _hqLegalName;
		/// <summary>
		/// This is Head Quarter Status
		/// </summary>
		private string _hqStatus;
		/// <summary>
		/// This is Global Ultimate Owner Status
		/// </summary>
		private string _guoStatus;
        [JsonIgnore]
        public virtual Schema Schema
		{
			get
			{
				return CustomerHierarchyInformation._SCHEMA;
			}
		}
		/// <summary>
		/// This is Global Ultimate Owner Customer code
		/// </summary>
		public string guoCustomerCode
		{
			get
			{
				return this._guoCustomerCode;
			}
			set
			{
				this._guoCustomerCode = value;
			}
		}
		/// <summary>
		/// This is Global Ultimate Owner Customer legal name
		/// </summary>
		public string guoLegalName
		{
			get
			{
				return this._guoLegalName;
			}
			set
			{
				this._guoLegalName = value;
			}
		}
		/// <summary>
		/// This is Head Quarter Customer code
		/// </summary>
		public string hqCustomerCode
		{
			get
			{
				return this._hqCustomerCode;
			}
			set
			{
				this._hqCustomerCode = value;
			}
		}
		/// <summary>
		/// This is Head Quarter Customer legal name
		/// </summary>
		public string hqLegalName
		{
			get
			{
				return this._hqLegalName;
			}
			set
			{
				this._hqLegalName = value;
			}
		}
		/// <summary>
		/// This is Head Quarter Status
		/// </summary>
		public string hqStatus
		{
			get
			{
				return this._hqStatus;
			}
			set
			{
				this._hqStatus = value;
			}
		}
		/// <summary>
		/// This is Global Ultimate Owner Status
		/// </summary>
		public string guoStatus
		{
			get
			{
				return this._guoStatus;
			}
			set
			{
				this._guoStatus = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.guoCustomerCode;
			case 1: return this.guoLegalName;
			case 2: return this.hqCustomerCode;
			case 3: return this.hqLegalName;
			case 4: return this.hqStatus;
			case 5: return this.guoStatus;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.guoCustomerCode = (System.String)fieldValue; break;
			case 1: this.guoLegalName = (System.String)fieldValue; break;
			case 2: this.hqCustomerCode = (System.String)fieldValue; break;
			case 3: this.hqLegalName = (System.String)fieldValue; break;
			case 4: this.hqStatus = (System.String)fieldValue; break;
			case 5: this.guoStatus = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
