namespace Dominio.ObjetosDeValor.Enumerador
{
    public enum CodigoExcecao
    {
        NaoEspecificado = 0,
        RequisicaoDuplicada = 1,
        SelecaoQualquerVeiculoNaoConfirmada = 2,
        PercursoNaoConfigurado = 3,
        JornadaTrabalhoExcedida = 4,
        ExclusividadeCarregamento = 5,
        HorarioDescarregamentoIndisponivel = 6,
        CapacidadeGrupoPessoaAtigida = 7,
        PrazoCancelamentoCarregamentoExcedidoPeloFornecedor = 8,
        ToleranciaAlocacaoHorarioDescarregamentoAtingida = 9,
        PeriodosIndisponiveisFaixaHorarioSelecionada = 10,
        RegistroCanceladoOuAnulado = 11,
        DataCarregamentoRetroativa = 12,
        FalhaAoRealizarDownloadArquivo = 13,
        VeiculosInvalidosCarga = 14,
        PedidoVinculadoCarga = 15,
        FalhaAoRealizarIntegracao = 16,
        FalhaAoEnviarEmail = 17,
        DataBloqueada = 18,
        RejeicaoCancelamentoCarga = 19,
        HorarioCarregamentoInferiorAtual = 20,
        HorarioLimiteCarregamentoAtingido = 21,
        HorarioLimiteDescarregamentoAtingido = 22,
        MotoristaInvalidoOneTrust = 23,
        AgendamentoCodigoCargaDuplicado = 24,
        HorarioDescarregamentoInferiorAtual = 25,
        SeparacaoMercadoriaInformada = 26,
        MotoristaSemImagemCadastrada = 27,
        AlteracoesPedidosNaoConfirmada = 28,
        PrevisaoCarregamentoIndisponivel = 29,
        HorarioCarregamentoIndisponivel = 30,
        HorarioCarregamentoInferiorAoTolerado = 31,
        LicencaInvalida = 32,
        NenhumRegistroEncontrado = 33,
        FalhaAoBuscarTratativaIrregularidadeAtualDocumento = 34,
        NaoTemPedagioNaRota = 35,
        ProtocoloNaoEncontrado = 36,
        SaldoInsuficienteParaAprovar = 37,
        RegistroIgnorado = 38,
        NaoEPossivelEscalar = 39,
        UsuarioNaoAptoEscaladaParaRealizarEscalada = 40,
        UsuarioNaoAptoARetornarAoNivelUm = 41,
    }
}
