namespace Dominio.ObjetosDeValor.EDI.EBS
{
    public class NotaEntradaItem
    {
        public string TipoRegistro { get; set; }
        public string Codigo { get; set; }
        public decimal Quantidade1 { get; set; }
        public decimal Valor { get; set; }
        public decimal Quantidade2 { get; set; }
        public decimal Desconto { get; set; }
        public decimal BaseICMS { get; set; }
        public decimal AliquotaICMS { get; set; }
        public decimal ValorIPI { get; set; }
        public decimal BaseICMSST { get; set; }
        public decimal AliquotaIPI { get; set; }
        public decimal PercentualReducaoICMS { get; set; }
        public string CSTICMS { get; set; }
        public string Identificacao { get; set; }
        public string CSTIPI { get; set; }
        public decimal BaseIPI { get; set; }
        public string CSTPIS { get; set; }
        public decimal BasePIS { get; set; }
        public decimal AliquotaPIS { get; set; }
        public decimal QuantidadeBasePIS { get; set; }
        public decimal AliquotaPISReais { get; set; }
        public decimal ValorPIS { get; set; }
        public string CSTCOFINS { get; set; }
        public decimal BaseCOFINS { get; set; }
        public decimal AliquotaCOFINS { get; set; }
        public decimal ValorCOFINS { get; set; }
        public decimal QuantidadeBaseCOFINS { get; set; }
        public decimal AliquotaCOIFINSReais { get; set; }
        public decimal ValorICMSST { get; set; }
        public decimal AliquotaICMSST { get; set; }
        public decimal ValorICMS { get; set; }
        public string NaturezaItem { get; set; }
        public string Unidade { get; set; }
        public decimal BaseICMSDiferencial { get; set; }
        public decimal ICMSOrigemDiferencial { get; set; }
        public decimal ICMSInternoDiferencial { get; set; }
        public decimal ICMSRecolherDiferencial { get; set; }
        public decimal BaseICMSAntecipacao { get; set; }
        public decimal ICMSOrigemAntecipacao { get; set; }
        public decimal ICMSIternoAntecipacao { get; set; }
        public decimal ICMSRecolherAntecipacao { get; set; }
        public decimal BaseSTAntecipacao { get; set; }
        public decimal MVASTAntecipacao { get; set; }
        public decimal BaseAjustadaSTAntecipacao { get; set; }
        public decimal ICMSSTOrigemAntecipacao { get; set; }
        public decimal ICMSSTInternoAntecipacao { get; set; }
        public decimal ICMSSTRecolherAntecipacao { get; set; }
        public string CSOSN { get; set; }
        public decimal ICMSAntecipacaoParcial { get; set; }
        public decimal PercentualDescontoCondicional { get; set; }
        public string ProdutoIndustrializado { get; set; }
        public string Brancos { get; set; }
        public string UsoEBS { get; set; }
        public string Sequencia { get; set; }
        public decimal CreditoPIS { get; set; }
        public decimal CreditoCOFINS { get; set; }
        public decimal Frete { get; set; }
        public decimal Seguro { get; set; }
        public decimal Despesas { get; set; }
        public string SaidaNatureza { get; set; }
        public string SaidaOrigem { get; set; }
        public string SaidaCSTICMS { get; set; }
        public decimal SaidaBaseICMS { get; set; }
        public decimal SaidaAliquotaICMS { get; set; }
        public decimal SaidaValorICMS { get; set; }
        public decimal SaidaBaseICMSST { get; set; }
        public decimal SaidaAliquotaICMSST { get; set; }
        public decimal SaidaValorICMSST { get; set; }
        public string SaidaCSTIPI { get; set; }
        public decimal SaidaBaseIPI { get; set; }
        public decimal SaidaAliquotaIPI { get; set; }
        public decimal SaidaValorIPI { get; set; }
        public string SaidaCSTPIS { get; set; }
        public decimal SaidaBasePIS { get; set; }
        public decimal SaidaAliquotaPIS { get; set; }
        public decimal SaidaValorPIS { get; set; }
        public decimal SaidaQuantidadeBasePIS { get; set; }
        public decimal SaidaAliquotaValorPIS { get; set; }
        public string SaidaCSTCOFINS { get; set; }
        public decimal SaidaBaseCOFINS { get; set; }
        public decimal SaidaAliquotaCOFINS { get; set; }
        public decimal SaidaValorCOFINS { get; set; }
        public decimal SaidaQuantidadeBaseCOFINS { get; set; }
        public decimal SaidaAliquotaValorCOFINS { get; set; }
        public string Identificacao2 { get; set; }
        public string GTIN { get; set; }
        public decimal MVAOriginalAntecipacao { get; set; }

    }
}
