//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicos.ABFSat {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ads4wtrack.temsat.com.br/wstemsat1", ConfigurationName="ABFSat.wstemsat1Soap")]
    public interface wstemsat1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ads4wtrack.temsat.com.br/wstemsat1/WSRegistro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Servicos.ABFSat.Posicao[] WSRegistro(int Cliente, string Usuario, string Senha, int Inicial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ads4wtrack.temsat.com.br/wstemsat1/WSRegistro", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicos.ABFSat.Posicao[]> WSRegistroAsync(int Cliente, string Usuario, string Senha, int Inicial);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ads4wtrack.temsat.com.br/wstemsat1")]
    public partial class Posicao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idMensagemField;
        
        private string dataHoraField;
        
        private string idRastreadorField;
        
        private string placaField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private string estadoField;
        
        private string cidadeField;
        
        private string logradouroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdMensagem {
            get {
                return this.idMensagemField;
            }
            set {
                this.idMensagemField = value;
                this.RaisePropertyChanged("IdMensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DataHora {
            get {
                return this.dataHoraField;
            }
            set {
                this.dataHoraField = value;
                this.RaisePropertyChanged("DataHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IdRastreador {
            get {
                return this.idRastreadorField;
            }
            set {
                this.idRastreadorField = value;
                this.RaisePropertyChanged("IdRastreador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
                this.RaisePropertyChanged("Placa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
                this.RaisePropertyChanged("Cidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
                this.RaisePropertyChanged("Logradouro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wstemsat1SoapChannel : Servicos.ABFSat.wstemsat1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wstemsat1SoapClient : System.ServiceModel.ClientBase<Servicos.ABFSat.wstemsat1Soap>, Servicos.ABFSat.wstemsat1Soap {
        
        public wstemsat1SoapClient() {
        }
        
        public wstemsat1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wstemsat1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wstemsat1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wstemsat1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Servicos.ABFSat.Posicao[] WSRegistro(int Cliente, string Usuario, string Senha, int Inicial) {
            return base.Channel.WSRegistro(Cliente, Usuario, Senha, Inicial);
        }
        
        public System.Threading.Tasks.Task<Servicos.ABFSat.Posicao[]> WSRegistroAsync(int Cliente, string Usuario, string Senha, int Inicial) {
            return base.Channel.WSRegistroAsync(Cliente, Usuario, Senha, Inicial);
        }
    }
}
