using System;
using System.Collections.Generic;
using Dominio.ObjetosDeValor.Embarcador.Enumeradores;

namespace Dominio.ObjetosDeValor.Embarcador.Pedido
{
    public sealed class PedidoImportacaoSalvar
    {
        public Entidades.Empresa Empresa { get; set; }
        public Entidades.Embarcador.PreCargas.PreCarga PreCarga { get; set; }
        public List<NFe.NotaFiscal> Nfes { get; set; }
        public List<int> NotasParciais { get; set; }
        public List<int> CtesParciais { get; set; }
        public string NumeroPedido { get; set; }
        public string NumeroPedidoCliente { get; set; }
        public decimal QuantidadePalletsFacionada { get; set; }
        public decimal PesoPedido { get; set; }
        public decimal CubagemPedido { get; set; }
        public string NomeArquivoGerador { get; set; }
        public string GuidArquivoGerador { get; set; }
        public Entidades.Embarcador.Cargas.TipoDeCarga TipoCarga { get; set; }
        public Entidades.Embarcador.Cargas.ModeloVeicularCarga ModeloVeicularCarga { get; set; }
        public Entidades.Embarcador.Pedidos.TipoOperacao TipoOperacao { get; set; }
        public Dominio.Entidades.Embarcador.Financeiro.CentroResultado CentroResultado { get; set; }
        public Entidades.Cliente Remetente { get; set; }
        public Dominio.Entidades.Embarcador.Pessoas.GrupoPessoas GrupoPessoasRemetente { get; set; }
        public Entidades.Embarcador.Produtos.ProdutoEmbarcador ProdutoPrincipal { get; set; }
        public Entidades.Cliente Destinatario { get; set; }
        public Entidades.Cliente Expedidor { get; set; }
        public Entidades.Cliente Recebedor { get; set; }
        public Entidades.Cliente LocalExpedicao { get; set; }
        public Entidades.Embarcador.Filiais.Filial Filial { get; set; }
        public Entidades.RotaFrete RotaFrete { get; set; }
        public Frete.FreteValor FreteValor { get; set; }
        public Frete.FreteValor FreteValorFilialEmissora { get; set; }
        public Entidades.Usuario Usuario { get; set; }
        public DateTime DataHoraCarregamento { get; set; }
        public DateTime? DataHoraPrevisaoSaida { get; set; }
        public DateTime? DataHoraPrevisaoInicioViagem { get; set; }
        public Dominio.Enumeradores.TipoTomador TipoTomador { get; set; }
        public string TipoEmbarque { get; set; }
        public string Observacao { get; set; }
        public int OrdemColeta { get; set; }
        public DateTime? DataHoraDescarga { get; set; }
        public DateTime DataValidade { get; set; }
        public DateTime DataInicioJanelaDescarga { get; set; }
        public Entidades.Embarcador.Pedidos.PedidoProduto PedidoProduto { get; set; }
        public Entidades.Embarcador.Pedidos.CanalEntrega CanalEntrega { get; set; }
        public Entidades.Veiculo Veiculo { get; set; }
        public List<Entidades.Veiculo> Reboques { get; set; }
        public List<Entidades.Usuario> Motoristas { get; set; }
        public List<Entidades.Cliente> Fronteiras { get; set; }
        public string Adicional1 { get; set; }
        public string Adicional2 { get; set; }
        public string Adicional3 { get; set; }
        public string Adicional4 { get; set; }
        public string Adicional5 { get; set; }
        public string Adicional6 { get; set; }
        public string Adicional7 { get; set; }
        public bool Ajudante { get; set; }
        public int QuantidadeAjudantes { get; set; }
        public DateTime DataPrevEntrega { get; set; }
        public string NumeroCargaEncaixar { get; set; }
        public string NumeroControle { get; set; }
        public bool QuebraMultiplosCarregamentos { get; set; }
        public Entidades.Embarcador.WMS.Deposito Deposito { get; set; }
        public int QtdVolumes { get; set; }
        public decimal ValorTotalPedido { get; set; }
        public int QuantidadeVolumesPrevios { get; set; }
        public int NumeroNotaCliente { get; set; }
        public string ObservacaoAdicional { get; set; }
        public decimal GrossSales { get; set; }
        public Entidades.Localidade Cidade { get; set; }
        public DateTime? DataAlocacaoPedido { get; set; }
        public bool PossuiIsca { get; set; }
        public bool PossuiEtiquetagem { get; set; }
        public string NumeroOrdem { get; set; }
        public Dominio.Entidades.Embarcador.Pedidos.Container Container { get; set; }
        public DateTime? DataColetaContainer { get; set; }
        public DateTime? DataHoraPrevisaoColeta { get; set; }
        public int QtdDisponibilizada { get; set; }
        public int QtdNaoEmbarcadas { get; set; }
        public int UnidadesContabilidade { get; set; }
        public decimal AliquotaICMSContabilidade { get; set; }
        public decimal ValorICMSContabilidade { get; set; }
        public decimal PTAXContabilidade { get; set; }
        public decimal ValorUSDContabilidade { get; set; }
        public string PONumberContabilidade { get; set; }
        public Dominio.Entidades.Embarcador.Pessoas.GrupoPessoas GrupoPessoas { get; set; }
        public SituacaoAgendamentoEntregaPedido? SituacaoAgendamentoEntregaPedido { get; set; }
        public Dominio.Entidades.Embarcador.Pedidos.Porto PortoOrigem { get; set; }
        public Dominio.Entidades.Embarcador.Pedidos.Porto PortoDestino { get; set; }
        public Dominio.Entidades.Embarcador.Pedidos.PedidoViagemNavio PedidoViagemNavio { get; set; }
        public Dominio.Entidades.Embarcador.Pedidos.TipoTerminalImportacao TerminalOrigem { get; set; }
        public Dominio.Entidades.Embarcador.Pedidos.TipoTerminalImportacao TerminalDestino { get; set; }
        public string ObservacaoParaFaturamento { get; set; }
        public decimal ValorTotalNotasFiscais { get; set; }
        public DateTime? DataCriacaoPedidoERP { get; set; }
        public string ObservacaoInterna { get; set; }
        public decimal Distancia { get; set; }
        public string NumeroDoca { get; set; }
        public Entidades.Cliente Tomador { get; set; }
        public Entidades.Embarcador.Cargas.FaixaTemperatura FaixaTemperatura { get; set; }
        public Dominio.Enumeradores.TipoPagamento TipoPagamento { get; set; }

        public string NumeroEXP { get; set; }
        public Dominio.Entidades.Embarcador.Cargas.ViaTransporte ViaTransporte { get; set; }
        public string Temperatura { get; set; }
        public Entidades.Cliente Despachante { get; set; }
        public Entidades.Cliente PortoViagemOrigem { get; set; }
        public Entidades.Cliente PortoViagemDestino { get; set; }
        public Entidades.Cliente ClienteFinal { get; set; }
        public Entidades.Pais PaisDestino { get; set; }
        public ObjetosDeValor.Embarcador.Enumeradores.FretePrepaid FretePrepaid { get; set; }
        public string NotaMercadoLivre { get; set; }
        public string SiglaFaturamentoMercadoLivre { get; set; }
        public string PFMercadoLivre { get; set; }
        public string ItemFaturadoMercadoLivre { get; set; }
        public Entidades.Localidade LocalidadePedidoDestino { get; set; }
        public string EnderecoPedidoDestino { get; set; }
        public string NumeroPedidoDestino { get; set; }
        public string ComplementoPedidoDestino { get; set; }
        public string CEPPedidoDestino { get; set; }
        public string BairroPedidoDestino { get; set; }
        public string TelefonePedidoDestino { get; set; }
        public string IEPedidoDestino { get; set; }
        public decimal DistanciaCarga { get; set; }
        public Dominio.Entidades.Embarcador.Pessoas.ClienteOutroEndereco CodigoEnderecoSecundario { get; set; }
        public bool PedidoImportadoPorPlanilha { get; set; }
        public Dominio.Entidades.Embarcador.Pedidos.Pedido NumeroPedidoOrigem { get; set; }
        public bool EssePedidopossuiPedidoBonificacao { get; set; }
        public bool EssePedidopossuiPedidoVenda { get; set; }
        public string NumeroPedidoVinculado { get; set; }
        public DateTime? DataPrevisaoTerminoCarregamento { get; set; }
        public Dominio.Entidades.Embarcador.Logistica.CentroCarregamento CentroCarregamento { get; set; }
        public bool DevolucaoPacotes { get; set; }
        public Dominio.Entidades.Embarcador.Logistica.CentroCustoViagem CentroDeCustoViagem { get; set; }
        public Dominio.Entidades.Embarcador.Escrituracao.ContratoFreteCliente ContratoFreteCliente { get; set; }
        public string Canal { get; set; }
        public Entidades.Localidade Origem { get; set; }
        public int Rota { get; set; }
        public string Facility { get; set; }
        public Entidades.Embarcador.Cargas.Carga CargaExistente { get; set; }
    }
}